[project]
name = "pyfa"
version = "2.68.0"  # TODO: make scripts read this instead of version.yml
description = "Python fitting assistant, a ship fitting tool for EVE Online"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.11"

# wxpython has special handling, to resolve conflicts between needs of having binary build in CI
# and building from source locally (to link to proper system libs instead of ubuntu-specific ones)
dependencies = [
    "logbook==1.7.0.post0",
    "numpy==1.26.2",
    "matplotlib==3.8.2",
    "python-dateutil==2.8.2",
    "requests==2.31.0",
    "sqlalchemy==2.0.51",
    "cryptography==42.0.4",
    "markdown2==2.4.11",
    "packaging==23.2",
    "roman==4.1",
    "beautifulsoup4==4.12.2",
    "pyyaml==6.0.1",
    "python-jose==3.3.0",
    "requests-cache==1.1.1",
]

[dependency-groups]
dev = [
    "ruff==0.15.5",
]
packaging = [
    "pyinstaller==6.21.0",
]

wx-binary = [
    "wxPython==4.3.1+ubuntu2204 ; sys_platform == 'linux'",
    "wxPython==4.3.1 ; sys_platform != 'linux'",
]
wx-source = [
    "wxPython==4.3.1",
]

[tool.uv]
package = false
default-groups = ["dev", "wx-source"]
conflicts = [[{ group = "wx-binary" }, { group = "wx-source" }]]

[[tool.uv.index]]
name = "wxpython-linux"
url = "https://github.com/wxWidgets/Phoenix/releases/expanded_assets/wxPython-4.3.1"
format = "flat"
explicit = true

[tool.uv.sources]
wxpython = [{ index = "wxpython-linux", group = "wx-binary", marker = "sys_platform == 'linux'" }]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = [
    "E203",
    "E731",
    "F401",
    "E722",
    "E741",
]

[tool.ruff.format]
# Not using formatting yet (and unsure if ever will)
exclude = ["*"]
