__all__ = ["resourcesViewFull", "resourcesViewMinimal",
           "resistancesViewFull", "resistancesViewMinimal",
           "rechargeViewFull", "rechargeViewMinimal",
           "firepowerViewFull", "firepowerViewMinimal",
           "capacitorViewFull", "capacitorViewMinimal",
           "targetingMiscViewFull", "targetingMiscViewMinimal",
           "priceViewFull", "priceViewMinimal",
           "miningyieldViewFull", "miningyieldViewMinimal",
           "droneViewFull", "droneViewMinimal",
           "cargoViewFull", "cargoViewMinimal"]
