class Conversions(object):
    instance = None

    @classmethod
    def getInstance(cls):
        if cls.instance is None:
            cls.instance = Conversions()

        return cls.instance

    def __init__(self):
        self.PACKS = {}

        """
        Conversion pack for Citadel release
        """
        self.PACKS['releaseApril2016'] = {
            # Renamed items
            "Capital Inefficient Armor Repair Unit"      : "CONCORD Capital Armor Repairer",
            "Capital Neutron Saturation Injector I"      : "CONCORD Capital Shield Booster",
            "Limited Mega Ion Siege Blaster I"           : "CONCORD Ion Siege Blaster",
            "Dual 1000mm 'Scout' Accelerator Cannon"     : "CONCORD Dual 1000mm Railgun",
            "Dual Modal Giga Pulse Laser I"              : "CONCORD Dual Giga Pulse Laser",
            "Dual Giga Modal Laser I"                    : "CONCORD Dual Giga Beam Laser",
            "'Limos' XL Cruise Launcher I"               : "CONCORD XL Cruise Missile Launcher",
            "Shock 'Limos' XL Torpedo Bay I"             : "CONCORD XL Torpedo Launcher",
            "Quad 3500mm Gallium Cannon"                 : "CONCORD Quad 3500mm Siege Artillery",
            "6x2500mm Heavy Gallium Repeating Cannon"    : "CONCORD Hexa 2500mm Repeating Cannon",
            "Capital Murky Remote Capacitor Transmitter" : "CONCORD Capital Remote Capacitor Transmitter",
            "Ion Siege Blaster Cannon I"                 : "Ion Siege Blaster I",
            "6x2500mm Repeating Cannon I"                : "Hexa 2500mm Repeating Cannon I",
            "Templar"                                    : "Templar I",
            "Dragonfly"                                  : "Dragonfly I",
            "Firbolg"                                    : "Firbolg I",
            "Einherji"                                   : "Einherji I",
            "Gjallarhorn"                                : "'Gjallarhorn' Explosive Doomsday",
            "Drone Control Unit I"                       : "Fighter Support Unit I",
            "Judgement"                                  : "'Judgment' Electromagnetic Doomsday",
            "Oblivion"                                   : "'Oblivion' Kinetic Doomsday",
            "Aurora Ominae"                              : "'Aurora Ominae' Thermal Doomsday",
            "Advanced Drone Interfacing"                 : "Fighter Hangar Management",
            "Remote ECM Burst I"                         : "ECM Jammer Burst Projector",
            "Projected Electronic Counter Measures"      : "Burst Projector Operation",
            "Cyclops"                                    : "Cyclops I",
            "Fighter Bombers"                            : "Heavy Fighters",
            "Malleus"                                    : "Malleus I",
            "Tyrfing"                                    : "Tyrfing I",
            "Mantis"                                     : "Mantis I",
            "XL Cruise Launcher I"                       : "XL Cruise Missile Launcher I",
            "Armor Resistance Phasing"                   : "Resistance Phasing",
            "Unit D-34343's Modified Drone Control Unit" : "Unit D-34343's Modified Fighter Support Unit",
            "Unit F-435454's Modified Drone Control Unit": "Unit F-435454's Modified Fighter Support Unit",
            "Unit P-343554's Modified Drone Control Unit": "Unit P-343554's Modified Fighter Support Unit",
            "Unit W-634's Modified Drone Control Unit"   : "Unit W-634's Modified Fighter Support Unit",
            "Heavy Shadow Serpentis Stasis Grappler"     : "Shadow Serpentis Heavy Stasis Grappler",
            "Heavy Domination Stasis Grappler"           : "Domination Heavy Stasis Grappler",
        }

        """
        Conversion pack for Carnyx Module Tiericide
        """
        self.PACKS['releaseCarnyx'] = {
            # Renamed items
            "1MN Microwarpdrive I"                            : "5MN Microwarpdrive I",
            "1MN Microwarpdrive II"                           : "5MN Microwarpdrive II",
            "Prototype 100MN Microwarpdrive I"                : "500MN Cold-Gas Enduring Microwarpdrive",
            "Experimental 100MN Afterburner I"                : "100MN Monopropellant Enduring Afterburner",
            "Upgraded 1MN Microwarpdrive I"                   : "5MN Cold-Gas Enduring Microwarpdrive",
            "Limited 1MN Microwarpdrive I"                    : "5MN Y-T8 Compact Microwarpdrive",
            "Experimental 10MN Microwarpdrive I"              : "50MN Cold-Gas Enduring Microwarpdrive",
            "Limited 1MN Afterburner I"                       : "1MN Y-S8 Compact Afterburner",
            "Experimental 1MN Afterburner I"                  : "1MN Monopropellant Enduring Afterburner",
            "Experimental 10MN Afterburner I"                 : "10MN Monopropellant Enduring Afterburner",
            "Large Azeotropic Ward Salubrity I"               : "Large Azeotropic Restrained Shield Extender",
            "Small Azeotropic Ward Salubrity I"               : "Small Azeotropic Restrained Shield Extender",
            "Medium Azeotropic Ward Salubrity I"              : "Medium Azeotropic Restrained Shield Extender",
            "Medium F-S9 Regolith Shield Induction"           : "Medium F-S9 Regolith Compact Shield Extender",
            "Small F-S9 Regolith Shield Induction"            : "Small F-S9 Regolith Compact Shield Extender",
            "Large F-S9 Regolith Shield Induction"            : "Large F-S9 Regolith Compact Shield Extender",
            "1600mm Reinforced Steel Plates I"                : "1600mm Steel Plates I",
            "100mm Reinforced Steel Plates I"                 : "100mm Steel Plates I",
            "200mm Reinforced Steel Plates I"                 : "200mm Steel Plates I",
            "400mm Reinforced Steel Plates I"                 : "400mm Steel Plates I",
            "800mm Reinforced Steel Plates I"                 : "800mm Steel Plates I",
            "400mm Reinforced Rolled Tungsten Plates I"       : "400mm Rolled Tungsten Compact Plates",
            "400mm Reinforced Crystalline Carbonide Plates I" : "400mm Crystalline Carbonide Restrained Plates",
            "800mm Reinforced Rolled Tungsten Plates I"       : "800mm Rolled Tungsten Compact Plates",
            "800mm Reinforced Crystalline Carbonide Plates I" : "800mm Crystalline Carbonide Restrained Plates",
            "1600mm Reinforced Rolled Tungsten Plates I"      : "1600mm Rolled Tungsten Compact Plates",
            "1600mm Reinforced Crystalline Carbonide Plates I": "1600mm Crystalline Carbonide Restrained Plates",
            "100mm Reinforced Rolled Tungsten Plates I"       : "100mm Rolled Tungsten Compact Plates",
            "100mm Reinforced Crystalline Carbonide Plates I" : "100mm Crystalline Carbonide Restrained Plates",
            "200mm Reinforced Rolled Tungsten Plates I"       : "200mm Rolled Tungsten Compact Plates",
            "200mm Reinforced Crystalline Carbonide Plates I" : "200mm Crystalline Carbonide Restrained Plates",
            "10MN Microwarpdrive I"                           : "50MN Microwarpdrive I",
            "100MN Microwarpdrive I"                          : "500MN Microwarpdrive I",
            "10MN Microwarpdrive II"                          : "50MN Microwarpdrive II",
            "100MN Microwarpdrive II"                         : "500MN Microwarpdrive II",
            "Domination 100MN Microwarpdrive"                 : "Domination 500MN Microwarpdrive",
            "Shadow Serpentis 100MN Microwarpdrive"           : "Shadow Serpentis 500MN Microwarpdrive",
            "Domination 10MN Microwarpdrive"                  : "Domination 50MN Microwarpdrive",
            "Shadow Serpentis 10MN Microwarpdrive"            : "Shadow Serpentis 50MN Microwarpdrive",
            "Domination 1MN Microwarpdrive"                   : "Domination 5MN Microwarpdrive",
            "Shadow Serpentis 1MN Microwarpdrive"             : "Shadow Serpentis 5MN Microwarpdrive",
            "Mizuro's Modified 100MN Microwarpdrive"          : "Mizuro's Modified 500MN Microwarpdrive",
            "Hakim's Modified 100MN Microwarpdrive"           : "Hakim's Modified 500MN Microwarpdrive",
            "Gotan's Modified 100MN Microwarpdrive"           : "Gotan's Modified 500MN Microwarpdrive",
            "Tobias' Modified 100MN Microwarpdrive"           : "Tobias' Modified 500MN Microwarpdrive",
            "Brynn's Modified 100MN Microwarpdrive"           : "Brynn's Modified 500MN Microwarpdrive",
            "Tuvan's Modified 100MN Microwarpdrive"           : "Tuvan's Modified 500MN Microwarpdrive",
            "Setele's Modified 100MN Microwarpdrive"          : "Setele's Modified 500MN Microwarpdrive",
            "Cormack's Modified 100MN Microwarpdrive"         : "Cormack's Modified 500MN Microwarpdrive",
            "Republic Fleet 1MN Microwarpdrive"               : "Republic Fleet 5MN Microwarpdrive",
            "Republic Fleet 10MN Microwarpdrive"              : "Republic Fleet 50MN Microwarpdrive",
            "Republic Fleet 100MN Microwarpdrive"             : "Republic Fleet 500MN Microwarpdrive",
            "Federation Navy 1MN Microwarpdrive"              : "Federation Navy 5MN Microwarpdrive",
            "Federation Navy 10MN Microwarpdrive"             : "Federation Navy 50MN Microwarpdrive",
            "Federation Navy 100MN Microwarpdrive"            : "Federation Navy 500MN Microwarpdrive",
            "Coreli C-Type 1MN Microwarpdrive"                : "Coreli C-Type 5MN Microwarpdrive",
            "Corelum C-Type 10MN Microwarpdrive"              : "Corelum C-Type 50MN Microwarpdrive",
            "Core C-Type 100MN Microwarpdrive"                : "Core C-Type 500MN Microwarpdrive",
            "Coreli B-Type 1MN Microwarpdrive"                : "Coreli B-Type 5MN Microwarpdrive",
            "Corelum B-Type 10MN Microwarpdrive"              : "Corelum B-Type 50MN Microwarpdrive",
            "Core B-Type 100MN Microwarpdrive"                : "Core B-Type 500MN Microwarpdrive",
            "Coreli A-Type 1MN Microwarpdrive"                : "Coreli A-Type 5MN Microwarpdrive",
            "Corelum A-Type 10MN Microwarpdrive"              : "Corelum A-Type 50MN Microwarpdrive",
            "Core A-Type 100MN Microwarpdrive"                : "Core A-Type 500MN Microwarpdrive",
            "Core X-Type 100MN Microwarpdrive"                : "Core X-Type 500MN Microwarpdrive",
            "Gistii C-Type 1MN Microwarpdrive"                : "Gistii C-Type 5MN Microwarpdrive",
            "Gistum C-Type 10MN Microwarpdrive"               : "Gistum C-Type 50MN Microwarpdrive",
            "Gist C-Type 100MN Microwarpdrive"                : "Gist C-Type 500MN Microwarpdrive",
            "Gistii B-Type 1MN Microwarpdrive"                : "Gistii B-Type 5MN Microwarpdrive",
            "Gistum B-Type 10MN Microwarpdrive"               : "Gistum B-Type 50MN Microwarpdrive",
            "Gist B-Type 100MN Microwarpdrive"                : "Gist B-Type 500MN Microwarpdrive",
            "Gistii A-Type 1MN Microwarpdrive"                : "Gistii A-Type 5MN Microwarpdrive",
            "Gistum A-Type 10MN Microwarpdrive"               : "Gistum A-Type 50MN Microwarpdrive",
            "Gist A-Type 100MN Microwarpdrive"                : "Gist A-Type 500MN Microwarpdrive",
            "Gist X-Type 100MN Microwarpdrive"                : "Gist X-Type 500MN Microwarpdrive",
            "100mm Reinforced Steel Plates II"                : "100mm Steel Plates II",
            "200mm Reinforced Steel Plates II"                : "200mm Steel Plates II",
            "400mm Reinforced Steel Plates II"                : "400mm Steel Plates II",
            "800mm Reinforced Steel Plates II"                : "800mm Steel Plates II",
            "1600mm Reinforced Steel Plates II"               : "1600mm Steel Plates II",
            "Micro 'Trapper' Shield Extender"                 : "Small 'Trapper' Shield Extender",
            "1MN Analog Booster Rockets"                      : "1MN Analog Booster Afterburner",
            "10MN Analog Booster Rockets"                     : "10MN Analog Booster Afterburner",
            "100MN Analog Booster Rockets"                    : "100MN Analog Booster Afterburner",
            "1MN Digital Booster Rockets"                     : "5MN Digital Booster Microwarpdrive",
            "10MN Digital Booster Rockets"                    : "50MN Digital Booster Microwarpdrive",
            "100MN Digital Booster Rockets"                   : "500MN Digital Booster Microwarpdrive",
            "Civilian Afterburner"                            : "1MN Civilian Afterburner",
            "'Abatis' 100mm Reinforced Steel Plates I"        : "'Abatis' 100mm Steel Plates",
            "'Bailey' 1600mm Reinforced Steel Plates I"       : "'Bailey' 1600mm Steel Plates",
            "'Chainmail' 200mm Reinforced Steel Plates I"     : "'Chainmail' 200mm Steel Plates",
            "'Bastion' 400mm Reinforced Steel Plates I"       : "'Bastion' 400mm Steel Plates",
            "'Citadella' 50mm Reinforced Steel Plates I"      : "'Citadella' 100mm Steel Plates",
            "'Barbican' 800mm Reinforced Steel Plates I"      : "'Barbican' 800mm Steel Plates",
            "Syndicate 100mm Reinforced Steel Plates"         : "Syndicate 100mm Steel Plates",
            "Syndicate 1600mm Reinforced Steel Plates"        : "Syndicate 1600mm Steel Plates",
            "Syndicate 200mm Reinforced Steel Plates"         : "Syndicate 200mm Steel Plates",
            "Syndicate 400mm Reinforced Steel Plates"         : "Syndicate 400mm Steel Plates",
            "Syndicate 800mm Reinforced Steel Plates"         : "Syndicate 800mm Steel Plates",
            "Imperial Navy 100mm Reinforced Steel Plates"     : "Imperial Navy 100mm Steel Plates",
            "Federation Navy 100mm Reinforced Steel Plates"   : "Federation Navy 100mm Steel Plates",
            "Imperial Navy 1600mm Reinforced Steel Plates"    : "Imperial Navy 1600mm Steel Plates",
            "Federation Navy 1600mm Reinforced Steel Plates"  : "Federation Navy 1600mm Steel Plates",
            "Imperial Navy 200mm Reinforced Steel Plates"     : "Imperial Navy 200mm Steel Plates",
            "Federation Navy 200mm Reinforced Steel Plates"   : "Federation Navy 200mm Steel Plates",
            "Imperial Navy 400mm Reinforced Steel Plates"     : "Imperial Navy 400mm Steel Plates",
            "Federation Navy 400mm Reinforced Steel Plates"   : "Federation Navy 400mm Steel Plates",
            "Imperial Navy 800mm Reinforced Steel Plates"     : "Imperial Navy 800mm Steel Plates",
            "Federation Navy 800mm Reinforced Steel Plates"   : "Federation Navy 800mm Steel Plates",
            "Polarized Small Pulse Laser"                     : "Polarized Small Focused Pulse Laser",
            # Converted items
            "Large Subordinate Screen Stabilizer I"           : "Large F-S9 Regolith Compact Shield Extender",
            "Large Supplemental Barrier Emitter I"            : "Large Azeotropic Restrained Shield Extender",
            "Medium Subordinate Screen Stabilizer I"          : "Medium F-S9 Regolith Compact Shield Extender",
            "Medium Supplemental Barrier Emitter I"           : "Medium Azeotropic Restrained Shield Extender",
            "Micro Azeotropic Ward Salubrity I"               : "Small 'Trapper' Shield Extender",
            "Micro F-S9 Regolith Shield Induction"            : "Small 'Trapper' Shield Extender",
            "Micro Shield Extender I"                         : "Small 'Trapper' Shield Extender",
            "Micro Shield Extender II"                        : "Small 'Trapper' Shield Extender",
            "Micro Subordinate Screen Stabilizer I"           : "Small 'Trapper' Shield Extender",
            "Micro Supplemental Barrier Emitter I"            : "Small 'Trapper' Shield Extender",
            "Small Subordinate Screen Stabilizer I"           : "Small F-S9 Regolith Compact Shield Extender",
            "Small Supplemental Barrier Emitter I"            : "Small Azeotropic Restrained Shield Extender",
            "100mm Reinforced Nanofiber Plates I"             : "100mm Crystalline Carbonide Restrained Plates",
            "100mm Reinforced Titanium Plates I"              : "100mm Rolled Tungsten Compact Plates",
            "1600mm Reinforced Nanofiber Plates I"            : "1600mm Crystalline Carbonide Restrained Plates",
            "1600mm Reinforced Titanium Plates I"             : "1600mm Rolled Tungsten Compact Plates",
            "200mm Reinforced Nanofiber Plates I"             : "200mm Crystalline Carbonide Restrained Plates",
            "200mm Reinforced Titanium Plates I"              : "200mm Rolled Tungsten Compact Plates",
            "400mm Reinforced Nanofiber Plates I"             : "400mm Crystalline Carbonide Restrained Plates",
            "400mm Reinforced Titanium Plates I"              : "400mm Rolled Tungsten Compact Plates",
            "50mm Reinforced Crystalline Carbonide Plates I"  : "'Citadella' 100mm Steel Plates",
            "50mm Reinforced Nanofiber Plates I"              : "'Citadella' 100mm Steel Plates",
            "50mm Reinforced Rolled Tungsten Plates I"        : "'Citadella' 100mm Steel Plates",
            "50mm Reinforced Steel Plates I"                  : "'Citadella' 100mm Steel Plates",
            "50mm Reinforced Steel Plates II"                 : "'Citadella' 100mm Steel Plates",
            "50mm Reinforced Titanium Plates I"               : "'Citadella' 100mm Steel Plates",
            "800mm Reinforced Nanofiber Plates I"             : "800mm Crystalline Carbonide Restrained Plates",
            "800mm Reinforced Titanium Plates I"              : "800mm Rolled Tungsten Compact Plates",
        }

        """
        Conversion pack for December 2015 release (no release name)
        """
        self.PACKS['releaseDecember15'] = {
            # Renamed items
            "Medium 'Gremlin' Power Core Disruptor I"                 : "Medium Gremlin Compact Energy Neutralizer",
            "Medium Coaxial Remote Armor Repairer"                    : "Medium Coaxial Compact Remote Armor Repairer",
            "'Distributor' Tracking Disruptor I"                      : "'Distributor' Guidance Disruptor I",
            "Type-D Power Core Modification: Shield Flux"             : "Type-D Restrained Shield Flux Coil",
            "Large Coaxial Remote Armor Repairer"                     : "Large Coaxial Compact Remote Armor Repairer",
            "Heavy 'Knave' Energy Drain"                              : "Heavy Knave Scoped Energy Nosferatu",
            "F-392 Baker Nunn Tracking Disruptor I"                   : "Baker Nunn Enduring Tracking Disruptor I",
            "'Ditch' Medium Energy Neutralizer I"                     : "Medium 'Ditch' Energy Neutralizer",
            "DDO Photometry Tracking Disruptor I"                     : "DDO Scoped Tracking Disruptor I",
            "Small S95a Remote Shield Booster"                        : "Small S95a Scoped Remote Shield Booster",
            "Large S95a Remote Shield Booster"                        : "Large S95a Scoped Remote Shield Booster",
            "'Abandon' Tracking Disruptor I"                          : "C-IR Compact Guidance Disruptor I",
            "500W Infectious Power System Malfunction"                : "Heavy Infectious Scoped Energy Neutralizer",
            "Heavy 'Gremlin' Power Core Disruptor I"                  : "Heavy Gremlin Compact Energy Neutralizer",
            "Medium 'Solace' Remote Armor Repairer"                   : "Medium Solace Scoped Remote Armor Repairer",
            "Small Coaxial Remote Armor Repairer"                     : "Small Coaxial Compact Remote Armor Repairer",
            "Basic Shield Flux Coil"                                  : "'Basic' Shield Flux Coil",
            "Large I-ax Remote Armor Repairer"                        : "Large I-ax Enduring Remote Armor Repairer",
            "Basic Shield Power Relay"                                : "'Basic' Shield Power Relay",
            "Capital Coaxial Remote Armor Repairer"                   : "CONCORD Capital Remote Armor Repairer",
            "Medium 'Ghoul' Energy Siphon I"                          : "Medium Ghoul Compact Energy Nosferatu",
            "Medium S95a Remote Shield Booster"                       : "Medium S95a Scoped Remote Shield Booster",
            "Mark I Generator Refitting: Shield Flux"                 : "Mark I Compact Shield Flux Coil",
            "Large 'Solace' Remote Armor Repairer"                    : "Large Solace Scoped Remote Armor Repairer",
            "Large Asymmetric Remote Shield Booster"                  : "Large Asymmetric Enduring Remote Shield Booster",
            "M51 Iterative Shield Regenerator"                        : "M51 Benefactor Compact Shield Recharger",
            "Small 'Knave' Energy Drain"                              : "Small Knave Scoped Energy Nosferatu",
            "Medium Murky Remote Shield Booster"                      : "Medium Murky Compact Remote Shield Booster",
            "Small Murky Remote Shield Booster"                       : "Small Murky Compact Remote Shield Booster",
            "Capital Murky Remote Shield Booster"                     : "CONCORD Capital Remote Shield Booster",
            "'Caltrop' Small Energy Neutralizer I"                    : "Small 'Caltrop' Energy Neutralizer",
            "Small I-ax Remote Armor Repairer"                        : "Small I-ax Enduring Remote Armor Repairer",
            "'Vrykolakas' Heavy Nosferatu I"                          : "Heavy 'Vrykolakas' Energy Nosferatu",
            "Heavy 'Ghoul' Energy Siphon I"                           : "Heavy Ghoul Compact Energy Nosferatu",
            "Small Asymmetric Remote Shield Booster"                  : "Small Asymmetric Enduring Remote Shield Booster",
            "Small 'Gremlin' Power Core Disruptor I"                  : "Small Gremlin Compact Energy Neutralizer",
            "'Strigoi' Medium Nosferatu I"                            : "Medium 'Strigoi' Energy Nosferatu",
            "'Upir' Small Nosferatu I"                                : "Small 'Upir' Energy Nosferatu",
            "Balmer Series Tracking Disruptor I"                      : "Balmer Series Compact Tracking Disruptor I",
            "Small 'Solace' Remote Armor Repairer"                    : "Small Solace Scoped Remote Armor Repairer",
            "'Moat' Heavy Energy Neutralizer I"                       : "Heavy 'Moat' Energy Neutralizer",
            "Small 'Ghoul' Energy Siphon I"                           : "Small Ghoul Compact Energy Nosferatu",
            "5W Infectious Power System Malfunction"                  : "Small Infectious Scoped Energy Neutralizer",
            "50W Infectious Power System Malfunction"                 : "Medium Infectious Scoped Energy Neutralizer",
            "Type-D Power Core Modification: Shield Power Relay"      : "Type-D Restrained Shield Power Relay",
            "Micro Remote Shield Booster I"                           : "'Micro' Remote Shield Booster",
            "Medium I-ax Remote Armor Repairer"                       : "Medium I-ax Enduring Remote Armor Repairer",
            "Medium Asymmetric Remote Shield Booster"                 : "Medium Asymmetric Enduring Remote Shield Booster",
            "Large Murky Remote Shield Booster"                       : "Large Murky Compact Remote Shield Booster",
            "Medium 'Knave' Energy Drain"                             : "Medium Knave Scoped Energy Nosferatu",
            "Mark I Generator Refitting: Shield Power Relay"          : "Mark I Compact Shield Power Relay",

            # Converted items
            "Medium Unstable Power Fluctuator I"                      : "Medium Gremlin Compact Energy Neutralizer",
            "'Brotherhood' Small Remote Armor Repairer"               : "'Beatnik' Small Remote Armor Repairer",
            "Beta Reactor Control: Shield Flux I"                     : "Type-D Restrained Shield Flux Coil",
            "E500 Prototype Energy Vampire"                           : "Heavy Knave Scoped Energy Nosferatu",
            "Heavy Rudimentary Energy Destabilizer I"                 : "Heavy Infectious Scoped Energy Neutralizer",
            "Heavy Unstable Power Fluctuator I"                       : "Heavy Gremlin Compact Energy Neutralizer",
            "Medium 'Arup' Remote Armor Repairer"                     : "Medium Solace Scoped Remote Armor Repairer",
            "Alpha Reactor Shield Flux"                               : "'Basic' Shield Flux Coil",
            "Marked Generator Refitting: Shield Flux"                 : "'Basic' Shield Flux Coil",
            "Partial Power Plant Manager: Shield Flux"                : "'Basic' Shield Flux Coil",
            "Type-E Power Core Modification: Shield Flux"             : "'Basic' Shield Flux Coil",
            "Alpha Reactor Shield Power Relay"                        : "'Basic' Shield Power Relay",
            "Marked Generator Refitting: Shield Power Relay"          : "'Basic' Shield Power Relay",
            "Partial Power Plant Manager: Shield Power Relay"         : "'Basic' Shield Power Relay",
            "Type-E Power Core Modification: Shield Power Relay"      : "'Basic' Shield Power Relay",
            "Small 'Arup' Remote Armor Repairer"                      : "Small Solace Scoped Remote Armor Repairer",
            "Medium Diminishing Power System Drain I"                 : "Medium Ghoul Compact Energy Nosferatu",
            "Local Power Plant Manager: Reaction Shield Flux I"       : "Mark I Compact Shield Flux Coil",
            "Large 'Arup' Remote Armor Repairer"                      : "Large Solace Scoped Remote Armor Repairer",
            "Passive Barrier Compensator I"                           : "M51 Benefactor Compact Shield Recharger",
            "'Benefactor' Ward Reconstructor"                         : "M51 Benefactor Compact Shield Recharger",
            "Supplemental Screen Generator I"                         : "M51 Benefactor Compact Shield Recharger",
            "E5 Prototype Energy Vampire"                             : "Small Knave Scoped Energy Nosferatu",
            "Medium 'Atonement' Remote Shield Booster"                : "Medium Murky Compact Remote Shield Booster",
            "Small 'Atonement' Remote Shield Booster"                 : "Small Murky Compact Remote Shield Booster",
            "Heavy Diminishing Power System Drain I"                  : "Heavy Ghoul Compact Energy Nosferatu",
            "Small Unstable Power Fluctuator I"                       : "Small Gremlin Compact Energy Neutralizer",
            "Local Power Plant Manager: Reaction Shield Power Relay I": "Mark I Compact Shield Power Relay",
            "'Pacifier' Large Remote Armor Repairer"                  : "'Peace' Large Remote Armor Repairer",
            "Small Diminishing Power System Drain I"                  : "Small Ghoul Compact Energy Nosferatu",
            "Small Rudimentary Energy Destabilizer I"                 : "Small Infectious Scoped Energy Neutralizer",
            "Medium Rudimentary Energy Destabilizer I"                : "Medium Infectious Scoped Energy Neutralizer",
            "Beta Reactor Control: Shield Power Relay I"              : "Type-D Restrained Shield Power Relay",
            "Micro Asymmetric Remote Shield Booster"                  : "'Micro' Remote Shield Booster",
            "Micro Murky Remote Shield Booster"                       : "'Micro' Remote Shield Booster",
            "Micro 'Atonement' Remote Shield Booster"                 : "'Micro' Remote Shield Booster",
            "Micro S95a Remote Shield Booster"                        : "'Micro' Remote Shield Booster",
            "Large 'Atonement' Remote Shield Booster"                 : "Large Murky Compact Remote Shield Booster",
            "E50 Prototype Energy Vampire"                            : "Medium Knave Scoped Energy Nosferatu",
        }

        # TODO: This date is wrong :(
        """
        Conversion pack for January 2016 (YC118.1) release
        """
        self.PACKS['releaseFeb2016'] = {
            # Renamed items
            "Capital Coaxial Remote Armor Repairer Blueprint": "CONCORD Capital Remote Armor Repairer Blueprint",
            "Capital Murky Remote Shield Booster Blueprint"  : "CONCORD Capital Remote Shield Booster Blueprint",
        }

        # TODO: This date is wrong :(
        """
        Conversion pack for January 2016 (YC118.1) release
        """
        self.PACKS['releaseFeb2016'] = {
            # Renamed items
            "Micro' Remote Shield Booster"                : "'Micro' Remote Shield Booster",
            "C-IR Compact Guidance Disruptor I"           : "C-IR Compact Guidance Disruptor",
            "'Distributor' Guidance Disruptor I"          : "'Distributor' Guidance Disruptor",
            "'Distributor' Guidance Disruptor I Blueprint": "'Distributor' Guidance Disruptor Blueprint",
            "Highstroke Scoped Guidance Disruptor I"      : "Highstroke Scoped Guidance Disruptor",
            "A-211 Enduring Guidance Disruptor I"         : "A-211 Enduring Guidance Disruptor",
        }

        """
        Conversion pack for January 2016 (YC118.1) release
        """
        self.PACKS['releaseMar2016'] = {
            # Renamed items
            "Basic Gyrostabilizer"                            : "'Basic' Gyrostabilizer",
            "Basic Damage Control"                            : "'Basic' Damage Control",
            "Micro Capacitor Battery I"                       : "'Micro' Cap Battery",
            "ECM Burst I"                                     : "Burst Jammer I",
            "Small Capacitor Battery I"                       : "Small Cap Battery I",
            "Basic Heat Sink"                                 : "'Basic' Heat Sink",
            "ECM - Ion Field Projector I"                     : "Magnetometric ECM I",
            "Basic Signal Amplifier"                          : "'Basic' Signal Amplifier",
            "Basic Tracking Enhancer"                         : "'Basic' Tracking Enhancer",
            "ECM - Spatial Destabilizer I"                    : "Gravimetric ECM I",
            "ECM - White Noise Generator I"                   : "Radar ECM I",
            "ECM - Multispectral Jammer I"                    : "Multispectral ECM I",
            "ECM - Phase Inverter I"                          : "Ladar ECM I",
            "Medium Capacitor Battery I"                      : "Medium Cap Battery I",
            "Large Capacitor Battery I"                       : "Large Cap Battery I",
            "ECM Burst II"                                    : "Burst Jammer II",
            "Guristas Nova Citadel Cruise Missile"            : "Guristas Nova XL Cruise Missile",
            "Guristas Scourge Citadel Cruise Missile"         : "Guristas Scourge XL Cruise Missile",
            "Guristas Inferno Citadel Cruise Missile"         : "Guristas Inferno XL Cruise Missile",
            "Guristas Mjolnir Citadel Cruise Missile"         : "Guristas Mjolnir XL Cruise Missile",
            "ECM - Phase Inverter II"                         : "Ladar ECM II",
            "ECM - Ion Field Projector II"                    : "Magnetometric ECM II",
            "ECM - Multispectral Jammer II"                   : "Multispectral ECM II",
            "ECM - Spatial Destabilizer II"                   : "Gravimetric ECM II",
            "ECM - White Noise Generator II"                  : "Radar ECM II",
            "Small Capacitor Battery II"                      : "Small Cap Battery II",
            "Medium Capacitor Battery II"                     : "Medium Cap Battery II",
            "Large Capacitor Battery II"                      : "Large Cap Battery II",
            "'Limos' Citadel Cruise Launcher I"               : "'Limos' XL Cruise Launcher I",
            "Shock 'Limos' Citadel Torpedo Bay I"             : "Shock 'Limos' XL Torpedo Bay I",
            "X5 Prototype Engine Enervator"                   : "X5 Enduring Stasis Webifier",
            "Fleeting Propulsion Inhibitor I"                 : "Fleeting Compact Stasis Webifier",
            "Caldari Fuel Block"                              : "Nitrogen Fuel Block",
            "Minmatar Fuel Block"                             : "Hydrogen Fuel Block",
            "Amarr Fuel Block"                                : "Helium Fuel Block",
            "Gallente Fuel Block"                             : "Oxygen Fuel Block",
            "Small Ld-Acid Capacitor Battery I"               : "Small Compact Pb-Acid Cap Battery ",
            "Large Ld-Acid Capacitor Battery I"               : "Large Compact Pb-Acid Cap Battery",
            "F-23 Reciprocal Remote Sensor Booster"           : "F-23 Compact Remote Sensor Booster",
            "Coadjunct Linked Remote Sensor Booster"          : "Coadjunct Scoped Remote Sensor Booster",
            "Linked Remote Sensor Booster"                    : "Linked Enduring Sensor Booster",
            "Low Frequency Sensor Suppressor I"               : "LFT Enduring Sensor Dampener",
            "Kapteyn Sensor Array Inhibitor I"                : "Kapteyn Compact Sensor Dampener",
            "Phased Muon Sensor Disruptor I"                  : "Phased Muon Scoped Sensor Dampener",
            "F-293 Nutation Remote Tracking Computer"         : "F-293 Scoped Remote Tracking Computer",
            "Phase Switching Remote Tracking Computer"        : "P-S Compact Remote Tracking Computer",
            "Alfven Surface Remote Tracking Computer"         : "Alfven Enduring Remote Tracking Computer",
            "'Deluge' ECM Burst I"                            : "Deluge Enduring Burst Jammer",
            "'Rash' ECM Emission I"                           : "Rash Compact Burst Jammer",
            "'Cetus' ECM Shockwave I"                         : "Cetus Scoped Burst Jammer",
            "J5 Prototype Warp Disruptor I"                   : "J5 Enduring Warp Disruptor",
            "Faint Warp Disruptor I"                          : "Faint Scoped Warp Disruptor",
            "Initiated Warp Disruptor I"                      : "Initiated Compact Warp Disruptor",
            "J5b Phased Prototype Warp Scrambler I"           : "J5b Enduring Warp Scrambler",
            "Faint Epsilon Warp Scrambler I"                  : "Faint Epsilon Scoped Warp Scrambler",
            "Initiated Harmonic Warp Scrambler I"             : "Initiated Compact Warp Scrambler",
            "Internal Force Field Array I"                    : "IFFA Compact Damage Control",
            "Extruded Heat Sink I"                            : "Extruded Compact Heat Sink",
            "Counterbalanced Weapon Mounts I"                 : "Counterbalanced Compact Gyrostabilizer",
            "Medium Ld-Acid Capacitor Battery I"              : "Medium Compact Pb-Acid Cap Battery",
            "Alumel-Wired Sensor Augmentation"                : "Alumel-Wired Enduring Sensor Booster",
            "F-90 Positional Sensor Subroutines"              : "F-90 Compact Sensor Booster",
            "Optical Tracking Computer I"                     : "Optical Compact Tracking Computer",
            "F-12 Nonlinear Tracking Processor"               : "F-12 Enduring Tracking Computer",
            "F-89 Synchronized Signal Amplifier"              : "F-89 Compact Signal Amplifier",
            "Fourier Transform Tracking Program"              : "Fourier Compact Tracking Enhancer",
            "Initiated Multispectral ECM I"                   : "Initiated Enduring Multispectral ECM",
            "Basic Magnetic Field Stabilizer"                 : "'Basic' Magnetic Field Stabilizer",
            "Magnetic Vortex Stabilizer I"                    : "Vortex Compact Magnetic Field Stabilizer",
            "Mizuro's Modified Warp Disruptor"                : "Mizuro's Modified Heavy Warp Disruptor",
            "Hakim's Modified Warp Disruptor"                 : "Hakim's Modified Heavy Warp Disruptor",
            "Gotan's Modified Warp Disruptor"                 : "Gotan's Modified Heavy Warp Disruptor",
            "Tobias' Modified Warp Disruptor"                 : "Tobias' Modified Heavy Warp Disruptor",
            "Mizuro's Modified Warp Scrambler"                : "Mizuro's Modified Heavy Warp Scrambler",
            "Hakim's Modified Warp Scrambler"                 : "Hakim's Modified Heavy Warp Scrambler",
            "Gotan's Modified Warp Scrambler"                 : "Gotan's Modified Heavy Warp Scrambler",
            "Tobias' Modified Warp Scrambler"                 : "Tobias' Modified Heavy Warp Scrambler",
            "Cross-linked Bolt Array I"                       : "Crosslink Compact Ballistic Control System",
            "Citadel Torpedo Battery"                         : "XL Torpedo Battery",
            "Mjolnir Citadel Torpedo"                         : "Mjolnir XL Torpedo",
            "Scourge Citadel Torpedo"                         : "Scourge XL Torpedo",
            "Inferno Citadel Torpedo"                         : "Inferno XL Torpedo",
            "Nova Citadel Torpedo"                            : "Nova XL Torpedo",
            "Peripheral Weapon Navigation Diameter"           : "Peripheral Compact Target Painter",
            "Parallel Weapon Navigation Transmitter"          : "Parallel Enduring Target Painter",
            "Phased Weapon Navigation Array Generation Extron": "Phased Scoped Target Painter",
            "Induced Ion Field ECM I"                         : "Morpheus Enduring Magnetometric ECM",
            "Compulsive Ion Field ECM I"                      : "Aergia Compact Magnetometric ECM",
            "'Hypnos' Ion Field ECM I"                        : "Hypnos Scoped Magnetometric ECM",
            "Induced Multispectral ECM I"                     : "Induced Compact Multispectral ECM",
            "Compulsive Multispectral ECM I"                  : "Compulsive Scoped Multispectral ECM",
            "Languid Phase Inversion ECM I"                   : "Languid Enduring Ladar ECM",
            "Halting Phase Inversion ECM I"                   : "Halting Compact Ladar ECM",
            "Enfeebling Phase Inversion ECM I"                : "Enfeebling Scoped Ladar ECM",
            "FZ-3a Disruptive Spatial Destabilizer ECM"       : "FZ-3a Enduring Gravimetric ECM",
            "CZ-4 Concussive Spatial Destabilizer ECM"        : "CZ-4 Compact Gravimetric ECM",
            "BZ-5 Neutralizing Spatial Destabilizer ECM"      : "BZ-5 Scoped Gravimetric ECM",
            "'Gloom' White Noise ECM"                         : "Gloom Enduring Radar ECM",
            "'Shade' White Noise ECM"                         : "Shade Compact Radar ECM",
            "'Umbra' White Noise ECM"                         : "Umbra Scoped Radar ECM",
            "Dread Guristas ECM Multispectral Jammer"         : "Dread Guristas Multispectral ECM",
            "Kaikka's Modified ECM Multispectral Jammer"      : "Kaikka's Modified Multispectral ECM",
            "Thon's Modified ECM Multispectral Jammer"        : "Thon's Modified Multispectral ECM",
            "Vepas' Modified ECM Multispectral Jammer"        : "Vepas' Modified Multispectral ECM",
            "Estamel's Modified ECM Multispectral Jammer"     : "Estamel's Modified Multispectral ECM",
            "Citadel Torpedo Launcher I"                      : "XL Torpedo Launcher I",
            "'Marshall' Ion Field Projector"                  : "'Marshall' Magnetometric ECM",
            "'Gambler' Phase Inverter"                        : "'Gambler' Ladar ECM",
            "'Plunderer' Spatial Destabilizer"                : "'Plunderer' Gravimetric ECM",
            "'Heist' White Noise Generator"                   : "'Heist' Radar ECM",
            "'Ghost' ECM Burst"                               : "'Ghost' Burst Jammer",
            "'Full Duplex' Ballistic Targeting System"        : "'Full Duplex' Ballistic Control System",
            "'Kindred' Stabilization Actuator I"              : "'Kindred' Gyrostabilizer",
            "Process-Interruptive Warp Disruptor"             : "'Interruptive' Warp Disruptor",
            "'Inception' Target Painter I"                    : "'Inception' Target Painter",
            "Citadel Torpedoes"                               : "XL Torpedoes",
            "'Shady' ECCM - Gravimetric I"                    : "'Shady' Sensor Booster",
            "'Monopoly' Magnetic Field Stabilizer I"          : "'Monopoly' Magnetic Field Stabilizer",
            "'Bootleg' ECCM Projector I"                      : "'Bootleg' Remote Sensor Booster",
            "'Marketeer' Tracking Computer I"                 : "'Marketeer' Tracking Computer",
            "'Executive' Remote Sensor Dampener I"            : "'Executive' Remote Sensor Dampener",
            "'Radical' Damage Control I"                      : "'Radical' Damage Control",
            "'Crucible' Small Capacitor Battery I"            : "'Crucible' Small Cap Battery",
            "'Censer' Medium Capacitor Battery I"             : "'Censer' Medium Cap Battery",
            "'Thurifer' Large Capacitor Battery I"            : "'Thurifer' Large Cap Battery",
            "Guristas Citadel Torpedo Battery"                : "Guristas XL Torpedo Battery",
            "Dread Guristas Citadel Torpedo Battery"          : "Dread Guristas XL Torpedo Battery",
            "Legion ECM Ion Field Projector"                  : "Legion Magnetometric ECM",
            "Legion ECM Multispectral Jammer"                 : "Legion Multispectral ECM",
            "Legion ECM Phase Inverter"                       : "Legion Ladar ECM",
            "Legion ECM Spatial Destabilizer"                 : "Legion Gravimetric ECM",
            "Legion ECM White Noise Generator"                : "Legion Radar ECM",
            "Guristas Nova Citadel Torpedo"                   : "Guristas Nova XL Torpedo",
            "Guristas Inferno Citadel Torpedo"                : "Guristas Inferno XL Torpedo",
            "Guristas Scourge Citadel Torpedo"                : "Guristas Scourge XL Torpedo",
            "Guristas Mjolnir Citadel Torpedo"                : "Guristas Mjolnir XL Torpedo",
            "Citadel Cruise Missiles"                         : "XL Cruise Missiles",
            "Scourge Citadel Cruise Missile"                  : "Scourge XL Cruise Missile",
            "Nova Citadel Cruise Missile"                     : "Nova XL Cruise Missile",
            "Inferno Citadel Cruise Missile"                  : "Inferno XL Cruise Missile",
            "Mjolnir Citadel Cruise Missile"                  : "Mjolnir XL Cruise Missile",
            "Citadel Cruise Launcher I"                       : "XL Cruise Launcher I",

            # Converted items
            "Muon Coil Bolt Array I"                          : "Crosslink Compact Ballistic Control System",
            "Multiphasic Bolt Array I"                        : "Crosslink Compact Ballistic Control System",
            "'Pandemonium' Ballistic Enhancement"             : "Crosslink Compact Ballistic Control System",
            "Piercing ECCM Emitter I"                         : "Coadjunct Scoped Remote Sensor Booster",
            "1Z-3 Subversive ECM Eruption"                    : "Cetus Scoped Burst Jammer",
            "ECCM - Radar I"                                  : "Sensor Booster I",
            "ECCM - Ladar I"                                  : "Sensor Booster I",
            "ECCM - Magnetometric I"                          : "Sensor Booster I",
            "ECCM - Gravimetric I"                            : "Sensor Booster I",
            "ECCM - Omni I"                                   : "Sensor Booster I",
            "Beta-Nought Tracking Mode"                       : "'Basic' Tracking Enhancer",
            "Azimuth Descalloping Tracking Enhancer"          : "'Basic' Tracking Enhancer",
            "F-AQ Delay-Line Scan Tracking Subroutines"       : "'Basic' Tracking Enhancer",
            "Beam Parallax Tracking Program"                  : "'Basic' Tracking Enhancer",
            "GLFF Containment Field"                          : "'Basic' Damage Control",
            "Interior Force Field Array"                      : "'Basic' Damage Control",
            "F84 Local Damage System"                         : "'Basic' Damage Control",
            "Systematic Damage Control"                       : "'Basic' Damage Control",
            "'Boss' Remote Sensor Booster"                    : "'Bootleg' Remote Sensor Booster",
            "'Entrepreneur' Remote Sensor Booster"            : "'Bootleg' Remote Sensor Booster",
            "Fleeting Progressive Warp Scrambler I"           : "Faint Epsilon Scoped Warp Scrambler",
            "ECCM Projector I"                                : "Remote Sensor Booster I",
            "Sigma-Nought Tracking Mode I"                    : "Fourier Compact Tracking Enhancer",
            "Auto-Gain Control Tracking Enhancer I"           : "Fourier Compact Tracking Enhancer",
            "F-aQ Phase Code Tracking Subroutines"            : "Fourier Compact Tracking Enhancer",
            "Monophonic Stabilization Actuator I"             : "'Kindred' Gyrostabilizer",
            "Initiated Ion Field ECM I"                       : "Hypnos Scoped Magnetometric ECM",
            "Insulated Stabilizer Array"                      : "'Basic' Magnetic Field Stabilizer",
            "Linear Flux Stabilizer"                          : "'Basic' Magnetic Field Stabilizer",
            "Gauss Field Balancer"                            : "'Basic' Magnetic Field Stabilizer",
            "Magnetic Vortex Stabilizer"                      : "'Basic' Magnetic Field Stabilizer",
            "'Capitalist' Magnetic Field Stabilizer I"        : "'Monopoly' Magnetic Field Stabilizer",
            "Emergency Damage Control I"                      : "IFFA Compact Damage Control",
            "F85 Peripheral Damage System I"                  : "IFFA Compact Damage Control",
            "Pseudoelectron Containment Field I"              : "IFFA Compact Damage Control",
            "Micro Ld-Acid Capacitor Battery I"               : "'Micro' Cap Battery",
            "Micro Ohm Capacitor Reserve I"                   : "'Micro' Cap Battery",
            "Micro F-4a Ld-Sulfate Capacitor Charge Unit"     : "'Micro' Cap Battery",
            "Micro Peroxide Capacitor Power Cell"             : "'Micro' Cap Battery",
            "Micro Capacitor Battery II"                      : "'Micro' Cap Battery",
            "Lateral Gyrostabilizer"                          : "'Basic' Gyrostabilizer",
            "F-M2 Weapon Inertial Suspensor"                  : "'Basic' Gyrostabilizer",
            "Hydraulic Stabilization Actuator"                : "'Basic' Gyrostabilizer",
            "Stabilized Weapon Mounts"                        : "'Basic' Gyrostabilizer",
            "'Hypnos' Multispectral ECM I"                    : "Compulsive Scoped Multispectral ECM",
            "Fleeting Warp Disruptor I"                       : "Faint Scoped Warp Disruptor",
            "'Mangonel' Heat Sink I"                          : "'Trebuchet' Heat Sink I",
            "Heat Exhaust System"                             : "'Basic' Heat Sink",
            "C3S Convection Thermal Radiator"                 : "'Basic' Heat Sink",
            "'Boreas' Coolant System"                         : "'Basic' Heat Sink",
            "Stamped Heat Sink"                               : "'Basic' Heat Sink",
            "Extra Radar ECCM Scanning Array I"               : "F-90 Compact Sensor Booster",
            "Extra Ladar ECCM Scanning Array I"               : "F-90 Compact Sensor Booster",
            "Extra Gravimetric ECCM Scanning Array I"         : "F-90 Compact Sensor Booster",
            "Extra Magnetometric ECCM Scanning Array I"       : "F-90 Compact Sensor Booster",
            "Gravimetric Positional ECCM Sensor System I"     : "F-90 Compact Sensor Booster",
            "Radar Positional ECCM Sensor System I"           : "F-90 Compact Sensor Booster",
            "Omni Positional ECCM Sensor System I"            : "F-90 Compact Sensor Booster",
            "Ladar Positional ECCM Sensor System I"           : "F-90 Compact Sensor Booster",
            "Magnetometric Positional ECCM Sensor System I"   : "F-90 Compact Sensor Booster",
            "Conjunctive Radar ECCM Scanning Array I"         : "F-90 Compact Sensor Booster",
            "Conjunctive Ladar ECCM Scanning Array I"         : "F-90 Compact Sensor Booster",
            "Conjunctive Gravimetric ECCM Scanning Array I"   : "F-90 Compact Sensor Booster",
            "Conjunctive Magnetometric ECCM Scanning Array I" : "F-90 Compact Sensor Booster",
            "Supplemental Scanning CPU I"                     : "F-90 Compact Sensor Booster",
            "'Gonzo' Damage Control I"                        : "'Radical' Damage Control",
            "'Penumbra' White Noise ECM"                      : "Umbra Scoped Radar ECM",
            "ECCM - Omni II"                                  : "Sensor Booster II",
            "ECCM - Gravimetric II"                           : "Sensor Booster II",
            "ECCM - Ladar II"                                 : "Sensor Booster II",
            "ECCM - Magnetometric II"                         : "Sensor Booster II",
            "ECCM - Radar II"                                 : "Sensor Booster II",
            "Scattering ECCM Projector I"                     : "Linked Enduring Sensor Booster",
            "Gravimetric Backup Array I"                      : "Signal Amplifier I",
            "Ladar Backup Array I"                            : "Signal Amplifier I",
            "Magnetometric Backup Array I"                    : "Signal Amplifier I",
            "Multi Sensor Backup Array I"                     : "Signal Amplifier I",
            "RADAR Backup Array I"                            : "Signal Amplifier I",
            "Large Ohm Capacitor Reserve I"                   : "Large Compact Pb-Acid Cap Battery",
            "Large F-4a Ld-Sulfate Capacitor Charge Unit"     : "Large Compact Pb-Acid Cap Battery",
            "Large Peroxide Capacitor Power Cell"             : "Large Compact Pb-Acid Cap Battery",
            "ECCM Projector II"                               : "Remote Sensor Booster II",
            "Cross-Lateral Gyrostabilizer I"                  : "Counterbalanced Compact Gyrostabilizer",
            "F-M3 Munition Inertial Suspensor"                : "Counterbalanced Compact Gyrostabilizer",
            "Pneumatic Stabilization Actuator I"              : "Counterbalanced Compact Gyrostabilizer",
            "'Langour' Drive Disruptor I"                     : "X5 Enduring Stasis Webifier",
            "Patterned Stasis Web I"                          : "Fleeting Compact Stasis Webifier",
            "'Tycoon' Remote Tracking Computer"               : "'Enterprise' Remote Tracking Computer",
            "'Economist' Tracking Computer I"                 : "'Marketeer' Tracking Computer",
            "Gravimetric Backup Array II"                     : "Signal Amplifier II",
            "Ladar Backup Array II"                           : "Signal Amplifier II",
            "Magnetometric Backup Array II"                   : "Signal Amplifier II",
            "Multi Sensor Backup Array II"                    : "Signal Amplifier II",
            "RADAR Backup Array II"                           : "Signal Amplifier II",
            "Faint Phase Inversion ECM I"                     : "Enfeebling Scoped Ladar ECM",
            "'Prayer' Remote Tracking Computer"               : "P-S Compact Remote Tracking Computer",
            "Partial Weapon Navigation"                       : "Phased Scoped Target Painter",
            "Basic RADAR Backup Array"                        : "'Basic' Signal Amplifier",
            "Basic Ladar Backup Array"                        : "'Basic' Signal Amplifier",
            "Basic Gravimetric Backup Array"                  : "'Basic' Signal Amplifier",
            "Basic Magnetometric Backup Array"                : "'Basic' Signal Amplifier",
            "Basic Multi Sensor Backup Array"                 : "'Basic' Signal Amplifier",
            "Emergency Magnetometric Scanners"                : "'Basic' Signal Amplifier",
            "Emergency Multi-Frequency Scanners"              : "'Basic' Signal Amplifier",
            "Emergency RADAR Scanners"                        : "'Basic' Signal Amplifier",
            "Emergency Ladar Scanners"                        : "'Basic' Signal Amplifier",
            "Emergency Gravimetric Scanners"                  : "'Basic' Signal Amplifier",
            "Sealed RADAR Backup Cluster"                     : "'Basic' Signal Amplifier",
            "Sealed Magnetometric Backup Cluster"             : "'Basic' Signal Amplifier",
            "Sealed Multi-Frequency Backup Cluster"           : "'Basic' Signal Amplifier",
            "Sealed Ladar Backup Cluster"                     : "'Basic' Signal Amplifier",
            "Sealed Gravimetric Backup Cluster"               : "'Basic' Signal Amplifier",
            "Surplus RADAR Reserve Array"                     : "'Basic' Signal Amplifier",
            "F-42 Reiterative RADAR Backup Sensors"           : "'Basic' Signal Amplifier",
            "Surplus Magnetometric Reserve Array"             : "'Basic' Signal Amplifier",
            "F-42 Reiterative Magnetometric Backup Sensors"   : "'Basic' Signal Amplifier",
            "Surplus Multi-Frequency Reserve Array"           : "'Basic' Signal Amplifier",
            "F-42 Reiterative Multi-Frequency Backup Sensors" : "'Basic' Signal Amplifier",
            "Surplus Ladar Reserve Array"                     : "'Basic' Signal Amplifier",
            "F-42 Reiterative Ladar Backup Sensors"           : "'Basic' Signal Amplifier",
            "Surplus Gravimetric Reserve Array"               : "'Basic' Signal Amplifier",
            "F-42 Reiterative Gravimetric Backup Sensors"     : "'Basic' Signal Amplifier",
            "Amplitude Signal Enhancer"                       : "'Basic' Signal Amplifier",
            "'Acolyth' Signal Booster"                        : "'Basic' Signal Amplifier",
            "Type-E Discriminative Signal Augmentation"       : "'Basic' Signal Amplifier",
            "F-90 Positional Signal Amplifier"                : "'Basic' Signal Amplifier",
            "Gravimetric Firewall"                            : "'Firewall' Signal Amplifier",
            "Ladar Firewall"                                  : "'Firewall' Signal Amplifier",
            "Magnetometric Firewall"                          : "'Firewall' Signal Amplifier",
            "Multi Sensor Firewall"                           : "'Firewall' Signal Amplifier",
            "RADAR Firewall"                                  : "'Firewall' Signal Amplifier",
            "'Pacifier' Large Remote Armor Repairer"          : "'Peace' Large Remote Armor Repairer",
            "Monopulse Tracking Mechanism I"                  : "F-12 Enduring Tracking Computer",
            "Alumel Radar ECCM Sensor Array I"                : "Alumel-Wired Enduring Sensor Booster",
            "Alumel Ladar ECCM Sensor Array I"                : "Alumel-Wired Enduring Sensor Booster",
            "Alumel Gravimetric ECCM Sensor Array I"          : "Alumel-Wired Enduring Sensor Booster",
            "Alumel Omni ECCM Sensor Array I"                 : "Alumel-Wired Enduring Sensor Booster",
            "Alumel Magnetometric ECCM Sensor Array I"        : "Alumel-Wired Enduring Sensor Booster",
            "Supplemental Ladar ECCM Scanning Array I"        : "Alumel-Wired Enduring Sensor Booster",
            "Supplemental Gravimetric ECCM Scanning Array I"  : "Alumel-Wired Enduring Sensor Booster",
            "Supplemental Omni ECCM Scanning Array I"         : "Alumel-Wired Enduring Sensor Booster",
            "Supplemental Radar ECCM Scanning Array I"        : "Alumel-Wired Enduring Sensor Booster",
            "Supplemental Magnetometric ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
            "Incremental Radar ECCM Scanning Array I"         : "Alumel-Wired Enduring Sensor Booster",
            "Incremental Ladar ECCM Scanning Array I"         : "Alumel-Wired Enduring Sensor Booster",
            "Incremental Gravimetric ECCM Scanning Array I"   : "Alumel-Wired Enduring Sensor Booster",
            "Incremental Magnetometric ECCM Scanning Array I" : "Alumel-Wired Enduring Sensor Booster",
            "Prototype ECCM Radar Sensor Cluster"             : "Alumel-Wired Enduring Sensor Booster",
            "Prototype ECCM Ladar Sensor Cluster"             : "Alumel-Wired Enduring Sensor Booster",
            "Prototype ECCM Gravimetric Sensor Cluster"       : "Alumel-Wired Enduring Sensor Booster",
            "Prototype ECCM Omni Sensor Cluster"              : "Alumel-Wired Enduring Sensor Booster",
            "Prototype ECCM Magnetometric Sensor Cluster"     : "Alumel-Wired Enduring Sensor Booster",
            "Prototype Sensor Booster"                        : "Alumel-Wired Enduring Sensor Booster",
            "Thermal Exhaust System I"                        : "Extruded Compact Heat Sink",
            "C4S Coiled Circuit Thermal Radiator"             : "Extruded Compact Heat Sink",
            "'Skadi' Coolant System I"                        : "Extruded Compact Heat Sink",
            "'Forger' ECCM - Magnetometric I"                 : "'Shady' Sensor Booster",
            "Insulated Stabilizer Array I"                    : "Vortex Compact Magnetic Field Stabilizer",
            "Linear Flux Stabilizer I"                        : "Vortex Compact Magnetic Field Stabilizer",
            "Gauss Field Balancer I"                          : "Vortex Compact Magnetic Field Stabilizer",
            "'Broker' Remote Sensor Dampener I"               : "'Executive' Remote Sensor Dampener",
            "'Orion' Tracking CPU I"                          : "Optical Compact Tracking Computer",
            "Spot Pulsing ECCM I"                             : "F-23 Compact Remote Sensor Booster",
            "Phased Muon ECCM Caster I"                       : "F-23 Compact Remote Sensor Booster",
            "Connected Remote Sensor Booster"                 : "F-23 Compact Remote Sensor Booster",
            "Small Ohm Capacitor Reserve I"                   : "Small Compact Pb-Acid Cap Battery",
            "Small F-4a Ld-Sulfate Capacitor Charge Unit"     : "Small Compact Pb-Acid Cap Battery",
            "Small Peroxide Capacitor Power Cell"             : "Small Compact Pb-Acid Cap Battery",
            "FZ-3 Subversive Spatial Destabilizer ECM"        : "BZ-5 Scoped Gravimetric ECM",
            "Medium Ohm Capacitor Reserve I"                  : "Medium Compact Pb-Acid Cap Battery",
            "Medium F-4a Ld-Sulfate Capacitor Charge Unit"    : "Medium Compact Pb-Acid Cap Battery",
            "Medium Peroxide Capacitor Power Cell"            : "Medium Compact Pb-Acid Cap Battery",
            "Ballistic 'Purge' Targeting System I"            : "'Full Duplex' Ballistic Control System",
            "Protected Gravimetric Backup Cluster I"          : "F-89 Compact Signal Amplifier",
            "Protected Ladar Backup Cluster I"                : "F-89 Compact Signal Amplifier",
            "Protected Magnetometric Backup Cluster I"        : "F-89 Compact Signal Amplifier",
            "Protected Multi-Frequency Backup Cluster I"      : "F-89 Compact Signal Amplifier",
            "Protected RADAR Backup Cluster I"                : "F-89 Compact Signal Amplifier",
            "Reserve Gravimetric Scanners"                    : "F-89 Compact Signal Amplifier",
            "Reserve Ladar Scanners"                          : "F-89 Compact Signal Amplifier",
            "Reserve Magnetometric Scanners"                  : "F-89 Compact Signal Amplifier",
            "Reserve Multi-Frequency Scanners"                : "F-89 Compact Signal Amplifier",
            "Reserve RADAR Scanners"                          : "F-89 Compact Signal Amplifier",
            "Secure Gravimetric Backup Cluster I"             : "F-89 Compact Signal Amplifier",
            "Secure Ladar Backup Cluster I"                   : "F-89 Compact Signal Amplifier",
            "Secure Magnetometric Backup Cluster I"           : "F-89 Compact Signal Amplifier",
            "Secure Radar Backup Cluster I"                   : "F-89 Compact Signal Amplifier",
            "F-43 Repetitive Gravimetric Backup Sensors"      : "F-89 Compact Signal Amplifier",
            "F-43 Repetitive Ladar Backup Sensors"            : "F-89 Compact Signal Amplifier",
            "F-43 Repetitive Magnetometric Backup Sensors"    : "F-89 Compact Signal Amplifier",
            "F-43 Repetitive Multi-Frequency Backup Sensors"  : "F-89 Compact Signal Amplifier",
            "F-43 Repetitive RADAR Backup Sensors"            : "F-89 Compact Signal Amplifier",
            "Shielded Gravimetric Backup Cluster I"           : "F-89 Compact Signal Amplifier",
            "Shielded Ladar Backup Cluster I"                 : "F-89 Compact Signal Amplifier",
            "Shielded Magnetometric Backup Cluster I"         : "F-89 Compact Signal Amplifier",
            "Shielded Radar Backup Cluster I"                 : "F-89 Compact Signal Amplifier",
            "Surrogate Gravimetric Reserve Array I"           : "F-89 Compact Signal Amplifier",
            "Surrogate Ladar Reserve Array I"                 : "F-89 Compact Signal Amplifier",
            "Surrogate Magnetometric Reserve Array I"         : "F-89 Compact Signal Amplifier",
            "Surrogate Multi-Frequency Reserve Array I"       : "F-89 Compact Signal Amplifier",
            "Surrogate RADAR Reserve Array I"                 : "F-89 Compact Signal Amplifier",
            "Warded Gravimetric Backup Cluster I"             : "F-89 Compact Signal Amplifier",
            "Warded Ladar Backup Cluster I"                   : "F-89 Compact Signal Amplifier",
            "Warded Magnetometric Backup Cluster I"           : "F-89 Compact Signal Amplifier",
            "Warded Radar Backup Cluster I"                   : "F-89 Compact Signal Amplifier",
            "'Mendicant' Signal Booster I"                    : "F-89 Compact Signal Amplifier",
            "Wavelength Signal Enhancer I"                    : "F-89 Compact Signal Amplifier",
            "Type-D Attenuation Signal Augmentation"          : "F-89 Compact Signal Amplifier",
            "Indirect Scanning Dampening Unit I"              : "Phased Muon Scoped Sensor Dampener",
        }

        """
        Conversion pack for Ascension release
        """
        self.PACKS['releaseNov2016'] = {
            # Renamed items
            "Armored Warfare Mindlink"        : "Armored Command Mindlink",
            "Siege Warfare Mindlink"          : "Shield Command Mindlink",
            "Information Warfare Mindlink"    : "Information Command Mindlink",
            "Skirmish Warfare Mindlink"       : "Skirmish Command Mindlink",
            "Imperial Navy Warfare Mindlink"  : "Imperial Navy Command Mindlink",
            "Federation Navy Warfare Mindlink": "Federation Navy Command Mindlink",
            "Republic Fleet Warfare Mindlink" : "Republic Fleet Command Mindlink",
            "Caldari Navy Warfare Mindlink"   : "Caldari Navy Command Mindlink",
            "Excavator Drone"                 : "'Excavator' Mining Drone",
        }

        """
        Conversion pack for Oceanus Module Tiericide
        """
        self.PACKS['releaseOceanus'] = {
            "Basic Capacitor Flux Coil"                           : "'Basic' Capacitor Flux Coil",
            "Basic LADAR Backup Array"                            : "Basic Ladar Backup Array",
            "LADAR Backup Array I"                                : "Ladar Backup Array I",
            "LADAR Backup Array II"                               : "Ladar Backup Array II",
            "'Regard' Remote Capacitor Transmitter"               : "Small 'Regard' Remote Capacitor Transmitter",
            "Prototype Freight Sensors"                           : "Enduring Cargo Scanner",
            "PL-0 Shipment Probe"                                 : "Scoped Cargo Scanner",
            "Reserve LADAR Scanners"                              : "Reserve Ladar Scanners",
            "Emergency LADAR Scanners"                            : "Emergency Ladar Scanners",
            "Protected LADAR Backup Cluster I"                    : "Protected Ladar Backup Cluster I",
            "Sealed LADAR Backup Cluster"                         : "Sealed Ladar Backup Cluster",
            "Surrogate LADAR Reserve Array I"                     : "Surrogate Ladar Reserve Array I",
            "F-43 Repetitive LADAR Backup Sensors"                : "F-43 Repetitive Ladar Backup Sensors",
            "Surplus LADAR Reserve Array"                         : "Surplus Ladar Reserve Array",
            "F-42 Reiterative LADAR Backup Sensors"               : "F-42 Reiterative Ladar Backup Sensors",
            "Rudimentary Ship Scanner I"                          : "Compact Ship Scanner",
            "Residual Survey Scanner I"                           : "Scoped Survey Scanner",
            "Upgraded 'Malkuth' Light Missile Launcher"           : "Compact Light Missile Launcher",
            "Limited 'Limos' Light Missile Launcher"              : "Ample Light Missile Launcher",
            "Beta Reactor Control: Capacitor Flux I"              : "Compact Capacitor Flux Coil",
            "Type-D Power Core Modification: Capacitor Flux"      : "Restrained Capacitor Flux Coil",
            "Type-D Power Core Modification: Reaction Control"    : "Compact Reactor Control Unit",
            "LADAR Firewall"                                      : "Ladar Firewall",
            "Interior Type-E Cargo Identifier"                    : "Scoped Cargo Scanner",
            "Ta3 Perfunctory Vessel Probe"                        : "Compact Ship Scanner",
            "Speculative Ship Identifier I"                       : "Compact Ship Scanner",
            "Practical Type-E Ship Probe"                         : "Compact Ship Scanner",
            "ML-3 Amphilotite Mining Probe"                       : "Scoped Survey Scanner",
            "Rock-Scanning Sensor Array I"                        : "Scoped Survey Scanner",
            "'Dactyl' Type-E Asteroid Analyzer"                   : "Scoped Survey Scanner",
            "Partial Power Plant Manager: Capacitor Flux"         : "'Basic' Capacitor Flux Coil",
            "Alpha Reactor Control: Capacitor Flux"               : "'Basic' Capacitor Flux Coil",
            "Type-E Power Core Modification: Capacitor Flux"      : "'Basic' Capacitor Flux Coil",
            "Marked Generator Refitting: Capacitor Flux"          : "'Basic' Capacitor Flux Coil",
            "Local Power Plant Manager: Capacitor Flux I"         : "Restrained Capacitor Flux Coil",
            "Mark I Generator Refitting: Capacitor Flux"          : "Compact Capacitor Flux Coil",
            "Nanoelectrical Co-Processor"                         : "Basic Co-Processor",
            "Nanomechanical CPU Enhancer"                         : "Basic Co-Processor",
            "Quantum Co-Processor"                                : "Basic Co-Processor",
            "Photonic CPU Enhancer"                               : "Basic Co-Processor",
            "Nanomechanical CPU Enhancer I"                       : "Upgraded Co-Processor",
            "Quantum Co-Processor I"                              : "Upgraded Co-Processor",
            "Photonic CPU Enhancer I"                             : "Upgraded Co-Processor",
            "Partial Power Plant Manager: Reaction Control"       : "Basic Reactor Control Unit",
            "Alpha Reactor Control: Reaction Control"             : "Basic Reactor Control Unit",
            "Marked Generator Refitting: Reaction Control"        : "Basic Reactor Control Unit",
            "Local Power Plant Manager: Reaction Control I is now": "Compact Reactor Control Unit",
            "Mark I Generator Refitting: Reaction Control"        : "Compact Reactor Control Unit",
            "Beta Reactor Control: Reaction Control I"            : "Compact Reactor Control Unit",
            "Micro B88 Core Augmentation"                         : "Compact Micro Auxiliary Power Core",
            "Micro K-Exhaust Core Augmentation"                   : "Compact Micro Auxiliary Power Core",
            "Micro 'Vigor' Core Augmentation"                     : "Navy Micro Auxiliary Power Core",
            "Prototype 'Arbalest' Light Missile Launcher"         : "Compact Light Missile Launcher",
            "Experimental TE-2100 Light Missile Launcher"         : "Ample Light Missile Launcher",
        }

        """
        Conversion pack for Parallax renames
        """
        self.PACKS['releaseParallax'] = {
            # Renamed items
            "Basic Thermic Plating"                           : "Basic Thermal Plating",
            "Thermic Plating I"                               : "Thermal Plating I",
            "Thermic Plating II"                              : "Thermal Plating II",
            "Basic Thermic Dissipation Amplifier"             : "Basic Thermal Dissipation Amplifier",
            "Thermic Dissipation Field I"                     : "Thermal Dissipation Field I",
            "Thermic Dissipation Field II"                    : "Thermal Dissipation Field II",
            "Thermic Dissipation Amplifier I"                 : "Thermal Dissipation Amplifier I",
            "Thermic Dissipation Amplifier II"                : "Thermal Dissipation Amplifier II",
            "Supplemental Thermic Dissipation Amplifier"      : "Supplemental Thermal Dissipation Amplifier",
            "Upgraded Thermic Dissipation Amplifier I"        : "Upgraded Thermal Dissipation Amplifier I",
            "Limited Thermic Dissipation Field I"             : "Limited Thermal Dissipation Field I",
            "Basic Energized Thermic Membrane"                : "Basic Energized Thermal Membrane",
            "Energized Thermic Membrane I"                    : "Energized Thermal Membrane I",
            "Energized Thermic Membrane II"                   : "Energized Thermal Membrane II",
            "Armor Thermic Hardener I"                        : "Armor Thermal Hardener I",
            "Thermic Shield Compensation"                     : "Thermal Shield Compensation",
            "Armor Thermic Hardener II"                       : "Armor Thermal Hardener II",
            "Dread Guristas Thermic Dissipation Field"        : "Dread Guristas Thermal Dissipation Field",
            "True Sansha Armor Thermic Hardener"              : "True Sansha Armor Thermal Hardener",
            "Dark Blood Armor Thermic Hardener"               : "Dark Blood Armor Thermal Hardener",
            "Domination Armor Thermic Hardener"               : "Domination Armor Thermal Hardener",
            "Domination Thermic Dissipation Field"            : "Domination Thermal Dissipation Field",
            "Domination Thermic Plating"                      : "Domination Thermal Plating",
            "True Sansha Thermic Plating"                     : "True Sansha Thermal Plating",
            "Dark Blood Thermic Plating"                      : "Dark Blood Thermal Plating",
            "Domination Thermic Dissipation Amplifier"        : "Domination Thermal Dissipation Amplifier",
            "Dread Guristas Thermic Dissipation Amplifier"    : "Dread Guristas Thermal Dissipation Amplifier",
            "Shadow Serpentis Thermic Plating"                : "Shadow Serpentis Thermal Plating",
            "Shadow Serpentis Armor Thermic Hardener"         : "Shadow Serpentis Armor Thermal Hardener",
            "Dark Blood Energized Thermic Membrane"           : "Dark Blood Energized Thermal Membrane",
            "True Sansha Energized Thermic Membrane"          : "True Sansha Energized Thermal Membrane",
            "Shadow Serpentis Energized Thermic Membrane"     : "Shadow Serpentis Energized Thermal Membrane",
            "Mizuro's Modified Thermic Plating"               : "Mizuro's Modified Thermal Plating",
            "Gotan's Modified Thermic Plating"                : "Gotan's Modified Thermal Plating",
            "Hakim's Modified Thermic Dissipation Amplifier"  : "Hakim's Modified Thermal Dissipation Amplifier",
            "Tobias' Modified Thermic Dissipation Amplifier"  : "Tobias' Modified Thermal Dissipation Amplifier",
            "Kaikka's Modified Thermic Dissipation Amplifier" : "Kaikka's Modified Thermal Dissipation Amplifier",
            "Thon's Modified Thermic Dissipation Amplifier"   : "Thon's Modified Thermal Dissipation Amplifier",
            "Vepas' Modified Thermic Dissipation Amplifier"   : "Vepas' Modified Thermal Dissipation Amplifier",
            "Estamel's Modified Thermic Dissipation Amplifier": "Estamel's Modified Thermal Dissipation Amplifier",
            "Kaikka's Modified Thermic Dissipation Field"     : "Kaikka's Modified Thermal Dissipation Field",
            "Thon's Modified Thermic Dissipation Field"       : "Thon's Modified Thermal Dissipation Field",
            "Vepas's Modified Thermic Dissipation Field"      : "Vepas's Modified Thermal Dissipation Field",
            "Estamel's Modified Thermic Dissipation Field"    : "Estamel's Modified Thermal Dissipation Field",
            "Brokara's Modified Thermic Plating"              : "Brokara's Modified Thermal Plating",
            "Tairei's Modified Thermic Plating"               : "Tairei's Modified Thermal Plating",
            "Selynne's Modified Thermic Plating"              : "Selynne's Modified Thermal Plating",
            "Raysere's Modified Thermic Plating"              : "Raysere's Modified Thermal Plating",
            "Vizan's Modified Thermic Plating"                : "Vizan's Modified Thermal Plating",
            "Ahremen's Modified Thermic Plating"              : "Ahremen's Modified Thermal Plating",
            "Chelm's Modified Thermic Plating"                : "Chelm's Modified Thermal Plating",
            "Draclira's Modified Thermic Plating"             : "Draclira's Modified Thermal Plating",
            "Brokara's Modified Energized Thermic Membrane"   : "Brokara's Modified Energized Thermal Membrane",
            "Tairei's Modified Energized Thermic Membrane"    : "Tairei's Modified Energized Thermal Membrane",
            "Selynne's Modified Energized Thermic Membrane"   : "Selynne's Modified Energized Thermal Membrane",
            "Raysere's Modified Energized Thermic Membrane"   : "Raysere's Modified Energized Thermal Membrane",
            "Vizan's Modified Energized Thermic Membrane"     : "Vizan's Modified Energized Thermal Membrane",
            "Ahremen's Modified Energized Thermic Membrane"   : "Ahremen's Modified Energized Thermal Membrane",
            "Chelm's Modified Energized Thermic Membrane"     : "Chelm's Modified Energized Thermal Membrane",
            "Draclira's Modified Energized Thermic Membrane"  : "Draclira's Modified Energized Thermal Membrane",
            "Brokara's Modified Armor Thermic Hardener"       : "Brokara's Modified Armor Thermal Hardener",
            "Tairei's Modified Armor Thermic Hardener"        : "Tairei's Modified Armor Thermal Hardener",
            "Selynne's Modified Armor Thermic Hardener"       : "Selynne's Modified Armor Thermal Hardener",
            "Raysere's Modified Armor Thermic Hardener"       : "Raysere's Modified Armor Thermal Hardener",
            "Vizan's Modified Armor Thermic Hardener"         : "Vizan's Modified Armor Thermal Hardener",
            "Ahremen's Modified Armor Thermic Hardener"       : "Ahremen's Modified Armor Thermal Hardener",
            "Chelm's Modified Armor Thermic Hardener"         : "Chelm's Modified Armor Thermal Hardener",
            "Draclira's Modified Armor Thermic Hardener"      : "Draclira's Modified Armor Thermal Hardener",
            "Brynn's Modified Thermic Plating"                : "Brynn's Modified Thermal Plating",
            "Tuvan's Modified Thermic Plating"                : "Tuvan's Modified Thermal Plating",
            "Setele's Modified Thermic Plating"               : "Setele's Modified Thermal Plating",
            "Cormack's Modified Thermic Plating"              : "Cormack's Modified Thermal Plating",
            "Brynn's Modified Energized Thermic Membrane"     : "Brynn's Modified Energized Thermal Membrane",
            "Tuvan's Modified Energized Thermic Membrane"     : "Tuvan's Modified Energized Thermal Membrane",
            "Setele's Modified Energized Thermic Membrane"    : "Setele's Modified Energized Thermal Membrane",
            "Cormack's Modified Energized Thermic Membrane"   : "Cormack's Modified Energized Thermal Membrane",
            "Brynn's Modified Armor Thermic Hardener"         : "Brynn's Modified Armor Thermal Hardener",
            "Tuvan's Modified Armor Thermic Hardener"         : "Tuvan's Modified Armor Thermal Hardener",
            "Setele's Modified Armor Thermic Hardener"        : "Setele's Modified Armor Thermal Hardener",
            "Cormack's Modified Armor Thermic Hardener"       : "Cormack's Modified Armor Thermal Hardener",
            "Shaqil's Modified Energized Thermic Membrane"    : "Shaqil's Modified Energized Thermal Membrane",
            "Imperial Navy Thermic Plating"                   : "Imperial Navy Thermal Plating",
            "Republic Fleet Thermic Plating"                  : "Republic Fleet Thermal Plating",
            "Imperial Navy Armor Thermic Hardener"            : "Imperial Navy Armor Thermal Hardener",
            "Republic Fleet Armor Thermic Hardener"           : "Republic Fleet Armor Thermal Hardener",
            "Imperial Navy Energized Thermic Membrane"        : "Imperial Navy Energized Thermal Membrane",
            "Federation Navy Energized Thermic Membrane"      : "Federation Navy Energized Thermal Membrane",
            "Caldari Navy Thermic Dissipation Amplifier"      : "Caldari Navy Thermal Dissipation Amplifier",
            "Republic Fleet Thermic Dissipation Amplifier"    : "Republic Fleet Thermal Dissipation Amplifier",
            "Upgraded Thermic Plating I"                      : "Upgraded Thermal Plating I",
            "Limited Thermic Plating I"                       : "Limited Thermal Plating I",
            "Experimental Thermic Plating I"                  : "Experimental Thermal Plating I",
            "Prototype Thermic Plating I"                     : "Prototype Thermal Plating I",
            "Upgraded Armor Thermic Hardener I"               : "Upgraded Armor Thermal Hardener I",
            "Limited Armor Thermic Hardener I"                : "Limited Armor Thermal Hardener I",
            "Experimental Armor Thermic Hardener I"           : "Experimental Armor Thermal Hardener I",
            "Prototype Armor Thermic Hardener I"              : "Prototype Armor Thermal Hardener I",
            "Upgraded Energized Thermic Membrane I"           : "Upgraded Energized Thermal Membrane I",
            "Limited Energized Thermic Membrane I"            : "Limited Energized Thermal Membrane I",
            "Experimental Energized Thermic Membrane I"       : "Experimental Energized Thermal Membrane I",
            "Prototype Energized Thermic Membrane I"          : "Prototype Energized Thermal Membrane I",
            "Caldari Navy Thermic Dissipation Field"          : "Caldari Navy Thermal Dissipation Field",
            "Ammatar Navy Armor Thermic Hardener"             : "Ammatar Navy Armor Thermal Hardener",
            "Ammatar Navy Energized Thermic Membrane"         : "Ammatar Navy Energized Thermal Membrane",
            "Federation Navy Thermic Plating"                 : "Federation Navy Thermal Plating",
            "Federation Navy Armor Thermic Hardener"          : "Federation Navy Armor Thermal Hardener",
            "Corpii C-Type Thermic Plating"                   : "Corpii C-Type Thermal Plating",
            "Centii C-Type Thermic Plating"                   : "Centii C-Type Thermal Plating",
            "Corpii B-Type Thermic Plating"                   : "Corpii B-Type Thermal Plating",
            "Centii B-Type Thermic Plating"                   : "Centii B-Type Thermal Plating",
            "Corpii A-Type Thermic Plating"                   : "Corpii A-Type Thermal Plating",
            "Centii A-Type Thermic Plating"                   : "Centii A-Type Thermal Plating",
            "Coreli C-Type Thermic Plating"                   : "Coreli C-Type Thermal Plating",
            "Coreli B-Type Thermic Plating"                   : "Coreli B-Type Thermal Plating",
            "Coreli A-Type Thermic Plating"                   : "Coreli A-Type Thermal Plating",
            "Corelum C-Type Energized Thermic Membrane"       : "Corelum C-Type Energized Thermal Membrane",
            "Corelum B-Type Energized Thermic Membrane"       : "Corelum B-Type Energized Thermal Membrane",
            "Corelum A-Type Energized Thermic Membrane"       : "Corelum A-Type Energized Thermal Membrane",
            "Corpum C-Type Energized Thermic Membrane"        : "Corpum C-Type Energized Thermal Membrane",
            "Centum C-Type Energized Thermic Membrane"        : "Centum C-Type Energized Thermal Membrane",
            "Corpum B-Type Energized Thermic Membrane"        : "Corpum B-Type Energized Thermal Membrane",
            "Centum B-Type Energized Thermic Membrane"        : "Centum B-Type Energized Thermal Membrane",
            "Corpum A-Type Energized Thermic Membrane"        : "Corpum A-Type Energized Thermal Membrane",
            "Centum A-Type Energized Thermic Membrane"        : "Centum A-Type Energized Thermal Membrane",
            "Corpus C-Type Armor Thermic Hardener"            : "Corpus C-Type Armor Thermal Hardener",
            "Centus C-Type Armor Thermic Hardener"            : "Centus C-Type Armor Thermal Hardener",
            "Corpus B-Type Armor Thermic Hardener"            : "Corpus B-Type Armor Thermal Hardener",
            "Centus B-Type Armor Thermic Hardener"            : "Centus B-Type Armor Thermal Hardener",
            "Corpus A-Type Armor Thermic Hardener"            : "Corpus A-Type Armor Thermal Hardener",
            "Centus A-Type Armor Thermic Hardener"            : "Centus A-Type Armor Thermal Hardener",
            "Corpus X-Type Armor Thermic Hardener"            : "Corpus X-Type Armor Thermal Hardener",
            "Centus X-Type Armor Thermic Hardener"            : "Centus X-Type Armor Thermal Hardener",
            "Core C-Type Armor Thermic Hardener"              : "Core C-Type Armor Thermal Hardener",
            "Core B-Type Armor Thermic Hardener"              : "Core B-Type Armor Thermal Hardener",
            "Core A-Type Armor Thermic Hardener"              : "Core A-Type Armor Thermal Hardener",
            "Core X-Type Armor Thermic Hardener"              : "Core X-Type Armor Thermal Hardener",
            "Pithum C-Type Thermic Dissipation Amplifier"     : "Pithum C-Type Thermal Dissipation Amplifier",
            "Pithum B-Type Thermic Dissipation Amplifier"     : "Pithum B-Type Thermal Dissipation Amplifier",
            "Pithum A-Type Thermic Dissipation Amplifier"     : "Pithum A-Type Thermal Dissipation Amplifier",
            "Gistum C-Type Thermic Dissipation Amplifier"     : "Gistum C-Type Thermal Dissipation Amplifier",
            "Gistum B-Type Thermic Dissipation Amplifier"     : "Gistum B-Type Thermal Dissipation Amplifier",
            "Gistum A-Type Thermic Dissipation Amplifier"     : "Gistum A-Type Thermal Dissipation Amplifier",
            "Gist C-Type Thermic Dissipation Field"           : "Gist C-Type Thermal Dissipation Field",
            "Pith C-Type Thermic Dissipation Field"           : "Pith C-Type Thermal Dissipation Field",
            "Gist B-Type Thermic Dissipation Field"           : "Gist B-Type Thermal Dissipation Field",
            "Pith B-Type Thermic Dissipation Field"           : "Pith B-Type Thermal Dissipation Field",
            "Gist A-Type Thermic Dissipation Field"           : "Gist A-Type Thermal Dissipation Field",
            "Pith A-Type Thermic Dissipation Field"           : "Pith A-Type Thermal Dissipation Field",
            "Gist X-Type Thermic Dissipation Field"           : "Gist X-Type Thermal Dissipation Field",
            "Pith X-Type Thermic Dissipation Field"           : "Pith X-Type Thermal Dissipation Field",
            "'High Noon' Thermic Dissipation Amplifier"       : "'High Noon' Thermal Dissipation Amplifier",
            "'Desert Heat' Thermic Dissipation Field"         : "'Desert Heat' Thermal Dissipation Field",
            "Thermic Armor Compensation"                      : "Thermal Armor Compensation",
            "'Moonshine' Energized Thermic Membrane I"        : "'Moonshine' Energized Thermal Membrane I",
            "Large Anti-Thermic Pump I"                       : "Large Anti-Thermal Pump I",
            "Large Anti-Thermic Pump II"                      : "Large Anti-Thermal Pump II",
            "Khanid Navy Armor Thermic Hardener"              : "Khanid Navy Armor Thermal Hardener",
            "Khanid Navy Energized Thermic Membrane"          : "Khanid Navy Energized Thermal Membrane",
            "Khanid Navy Thermic Plating"                     : "Khanid Navy Thermal Plating",
            "Civilian Thermic Dissipation Field"              : "Civilian Thermal Dissipation Field",
            "Small Anti-Thermic Pump I"                       : "Small Anti-Thermal Pump I",
            "Medium Anti-Thermic Pump I"                      : "Medium Anti-Thermal Pump I",
            "Capital Anti-Thermic Pump I"                     : "Capital Anti-Thermal Pump I",
            "Small Anti-Thermic Pump II"                      : "Small Anti-Thermal Pump II",
            "Medium Anti-Thermic Pump II"                     : "Medium Anti-Thermal Pump II",
            "Capital Anti-Thermic Pump II"                    : "Capital Anti-Thermal Pump II",
            "Ammatar Navy Thermic Plating"                    : "Ammatar Navy Thermal Plating",
        }

        """
        Conversion pack for Proteus Module Tiericide
        """
        self.PACKS['releaseProteus'] = {
            # Renamed items
            "Basic Capacitor Recharger"                            : "'Basic' Capacitor Recharger",
            "Basic Capacitor Power Relay"                          : "'Basic' Capacitor Power Relay",
            "Basic Overdrive Injector System"                      : "'Basic' Overdrive Injector System",
            "Basic Reinforced Bulkheads"                           : "'Basic' Reinforced Bulkheads",
            "Basic Nanofiber Internal Structure"                   : "'Basic' Nanofiber Internal Structure",
            "Basic Expanded Cargohold"                             : "'Basic' Expanded Cargohold",
            "Basic Inertia Stabilizers"                            : "'Basic' Inertial Stabilizers",
            "Inertia Stabilizers I"                                : "Inertial Stabilizers I",
            "Inertia Stabilizers II"                               : "Inertial Stabilizers II",
            "Basic Power Diagnostic System"                        : "'Basic' Power Diagnostic System",
            "Eutectic Capacitor Charge Array"                      : "Eutectic Compact Cap Recharger",
            "Cu Vapor Particle Bore Stream I"                      : "Particle Bore Compact Mining Laser",
            "Type-D Altered SS Expanded Cargo"                     : "Type-D Restrained Expanded Cargo",
            "Type-D Altered SS Inertial Stabilizers"               : "Type-D Restrained Inertial Stabilizers",
            "Type-D Altered SS Nanofiber Structure"                : "Type-D Restrained Nanofiber Structure",
            "Type-D Altered SS Overdrive Injector"                 : "Type-D Restrained Overdrive Injector",
            "Type-D Altered SS Reinforced Bulkheads"               : "Type-D Restrained Reinforced Bulkheads",
            "Mark I Modified SS Reinforced Bulkheads"              : "Mark I Compact Reinforced Bulkheads",
            "Type-D Power Core Modification: Capacitor Power Relay": "Type-D Restrained Capacitor Power Relay",
            "Mark I Generator Refitting: Capacitor Power Relay"    : "Mark I Compact Capacitor Power Relay",
            "Mark I Generator Refitting: Diagnostic System"        : "Mark I Compact Power Diagnostic System",
            "Synthetic Hull Conversion Overdrive Injector I"       : "Synthetic Hull Conversion Overdrive Injector",
            "Synthetic Hull Conversion Reinforced Bulkheads I"     : "Synthetic Hull Conversion Reinforced Bulkheads",
            "Synthetic Hull Conversion Inertia Stabilizers I"      : "Synthetic Hull Conversion Inertia Stabilizers",
            "Synthetic Hull Conversion Nanofiber Structure I"      : "Synthetic Hull Conversion Nanofiber Structure",
            "Elara Mining Laser Upgrade"                           : "Elara Restrained Mining Laser Upgrade",
            "Carpo Mining Laser Upgrade"                           : "'Carpo' Mining Laser Upgrade",
            "Aoede Mining Laser Upgrade"                           : "'Aoede' Mining Laser Upgrade",
            "Frigoris Ice Harvester Upgrade"                       : "Frigoris Restrained Ice Harvester Upgrade",
            "Anguis Ice Harvester Upgrade"                         : "'Anguis' Ice Harvester Upgrade",
            "Ingenii Ice Harvester Upgrade"                        : "'Ingenii' Ice Harvester Upgrade",
            "Limited Expanded 'Archiver' Cargo I"                  : "Limited Expanded 'Archiver' Cargo",
            "EP-S Gaussian Excavation Pulse"                       : "EP-S Gaussian Scoped Mining Laser",

            # Converted items
            "Alpha Reactor Control: Diagnostic System"             : "'Basic' Power Diagnostic System",
            "Marked Generator Refitting: Diagnostic System"        : "'Basic' Power Diagnostic System",
            "Partial Power Plant Manager: Diagnostic System"       : "'Basic' Power Diagnostic System",
            "Type-E Power Core Modification: Diagnostic System"    : "'Basic' Power Diagnostic System",
            "Type-E Power Core Modification: Reaction Control"     : "'Basic' Power Diagnostic System",
            "Local Hull Conversion Reinforced Bulkheads I"         : "Type-D Restrained Reinforced Bulkheads",
            "Beta Hull Mod Reinforced Bulkheads"                   : "Mark I Compact Reinforced Bulkheads",
            "Beta Hull Mod Inertial Stabilizers"                   : "Type-D Restrained Inertial Stabilizers",
            "Local Hull Conversion Inertial Stabilizers I"         : "Type-D Restrained Inertial Stabilizers",
            "Mark I Modified SS Inertial Stabilizers"              : "Type-D Restrained Inertial Stabilizers",
            "Marked Modified SS Inertial Stabilizers"              : "Type-D Restrained Inertial Stabilizers",
            "Beta Reactor Control: Diagnostic System I"            : "Mark I Compact Power Diagnostic System",
            "Local Power Plant Manager: Diagnostic System I"       : "Mark I Compact Power Diagnostic System",
            "Type-D Power Core Modification: Diagnostic System"    : "Mark I Compact Power Diagnostic System",
            "Alpha Hull Mod Expanded Cargo"                        : "'Basic' Expanded Cargohold",
            "Marked Modified SS Expanded Cargo"                    : "'Basic' Expanded Cargohold",
            "Partial Hull Conversion Expanded Cargo"               : "'Basic' Expanded Cargohold",
            "Type-E Altered SS Expanded Cargo"                     : "'Basic' Expanded Cargohold",
            "AGM Capacitor Charge Array"                           : "'Basic' Capacitor Recharger",
            "F-a10 Buffer Capacitor Regenerator"                   : "'Basic' Capacitor Recharger",
            "Industrial Capacitor Recharger"                       : "'Basic' Capacitor Recharger",
            "Secondary Parallel Link-Capacitor"                    : "'Basic' Capacitor Recharger",
            "Beta Reactor Control: Capacitor Power Relay I"        : "Mark I Compact Capacitor Power Relay",
            "Alpha Hull Mod Overdrive Injector"                    : "'Basic' Overdrive Injector System",
            "Marked Modified SS Overdrive Injector"                : "'Basic' Overdrive Injector System",
            "Partial Hull Conversion Overdrive Injector"           : "'Basic' Overdrive Injector System",
            "Type-E Altered SS Overdrive Injector"                 : "'Basic' Overdrive Injector System",
            "Erin Mining Laser Upgrade"                            : "Elara Restrained Mining Laser Upgrade",
            "Alpha Hull Mod Reinforced Bulkheads"                  : "'Basic' Reinforced Bulkheads",
            "Marked Modified SS Reinforced Bulkheads"              : "'Basic' Reinforced Bulkheads",
            "Partial Hull Conversion Reinforced Bulkheads"         : "'Basic' Reinforced Bulkheads",
            "Type-E Altered SS Reinforced Bulkheads"               : "'Basic' Reinforced Bulkheads",
            "Alpha Hull Mod Nanofiber Structure"                   : "'Basic' Nanofiber Internal Structure",
            "Marked Modified SS Nanofiber Structure"               : "'Basic' Nanofiber Internal Structure",
            "Partial Hull Conversion Nanofiber Structure"          : "'Basic' Nanofiber Internal Structure",
            "Type-E Altered SS Nanofiber Structure"                : "'Basic' Nanofiber Internal Structure",
            "Crisium Ice Harvester Upgrade"                        : "Frigoris Restrained Ice Harvester Upgrade",
            "Beta Hull Mod Nanofiber Structure"                    : "Type-D Restrained Nanofiber Structure",
            "Local Hull Conversion Nanofiber Structure I"          : "Type-D Restrained Nanofiber Structure",
            "Mark I Modified SS Nanofiber Structure"               : "Type-D Restrained Nanofiber Structure",
            "Local Power Plant Manager: Capacity Power Relay I"    : "Type-D Restrained Capacitor Power Relay",
            "EP-R Argon Ion Basic Excavation Pulse"                : "Single Diode Basic Mining Laser",
            "Rubin Basic Particle Bore Stream"                     : "Single Diode Basic Mining Laser",
            "Xenon Basic Drilling Beam"                            : "Single Diode Basic Mining Laser",
            "Barton Reactor Capacitor Recharger I"                 : "Eutectic Compact Cap Recharger",
            "F-b10 Nominal Capacitor Regenerator"                  : "Eutectic Compact Cap Recharger",
            "Fixed Parallel Link-Capacitor I"                      : "Eutectic Compact Cap Recharger",
            "Beta Hull Mod Expanded Cargo"                         : "Type-D Restrained Expanded Cargo",
            "Local Hull Conversion Expanded Cargo I"               : "Type-D Restrained Expanded Cargo",
            "Mark I Modified SS Expanded Cargo"                    : "Type-D Restrained Expanded Cargo",
            "Dual Diode Mining Laser I"                            : "EP-S Gaussian Scoped Mining Laser",
            "Alpha Hull Mod Inertial Stabilizers"                  : "'Basic' Inertial Stabilizers",
            "Partial Hull Conversion Inertial Stabilizers"         : "'Basic' Inertial Stabilizers",
            "Type-E Altered SS Inertial Stabilizers"               : "'Basic' Inertial Stabilizers",
            "Alpha Reactor Control: Capacitor Power Relay"         : "'Basic' Capacitor Power Relay",
            "Marked Generator Refitting: Capacitor Power Relay"    : "'Basic' Capacitor Power Relay",
            "Partial Power Plant Manager: Capacity Power Relay"    : "'Basic' Capacitor Power Relay",
            "Type-E Power Core Modification: Capacitor Power Relay": "'Basic' Capacitor Power Relay",
            "XeCl Drilling Beam I"                                 : "Particle Bore Compact Mining Laser",
            "Beta Hull Mod Overdrive Injector"                     : "Type-D Restrained Overdrive Injector",
            "Local Hull Conversion Overdrive Injector I"           : "Type-D Restrained Overdrive Injector",
            "Mark I Modified SS Overdrive Injector"                : "Type-D Restrained Overdrive Injector",
        }

        """
        Conversion pack for Tiamat Module Tiericide
        """
        self.PACKS['releaseTiamat'] = {
            "Enduring Cargo Scanner"            : "Type-E Enduring Cargo Scanner",
            "Scoped Cargo Scanner"              : "PL-0 Scoped Cargo Scanner",
            "Compact Ship Scanner"              : "Ta3 Compact Ship Scanner",
            "Scoped Survey Scanner"             : "ML-3 Scoped Survey Scanner",
            "Compact Light Missile Launcher"    : "Arbalest Compact Light Missile Launcher",
            "Ample Light Missile Launcher"      : "TE-2100 Ample Light Missile Launcher",
            "Compact Capacitor Flux Coil"       : "Mark I Compact Capacitor Flux Coil",
            "Restrained Capacitor Flux Coil"    : "Type-D Restrained Capacitor Flux Coil",
            "Compact Reactor Control Unit"      : "Mark I Compact Reactor Control Unit",
            "Upgraded Co-Processor"             : "Photonic Upgraded Co-Processor",
            "Compact Micro Auxiliary Power Core": "Vigor Compact Micro Auxiliary Power Core",
        }

        """
        Conversion pack for skinned ships to their base hull. Unlike other conversion
        packs, the name of this file is important as it is used in service.market to
        flag as unpublished

        See GH issue #67 on why this is needed
        """
        self.PACKS['skinnedShips'] = {
            "Miasmos Amastris Edition"         : "Miasmos Quafe Ultra Edition",
            "Miasmos Quafe Ultramarine Edition": "Miasmos Quafe Ultra Edition",
            "Rattlesnake Victory Edition"      : "Rattlesnake",
            "Stratios Emergency Responder"     : "Stratios",
        }
