CONVERSIONS = {
    # Renamed items
    "Large Rudimentary Concussion Bomb I": "'Concussion' Compact Large Graviton Smartbomb",
    "Small Rudimentary Concussion Bomb I": "'Concussion' Compact Small Graviton Smartbomb",
    "Large 'Vehemence' Shockwave Charge": "'Vehemence' Compact Large EMP Smartbomb",
    "Small 'Vehemence' Shockwave Charge": "'Vehemence' Compact Small EMP Smartbomb",
    "Medium Rudimentary Concussion Bomb I": "'Concussion' Compact Medium Graviton Smartbomb",
    "Medium 'Vehemence' Shockwave Charge": "'Vehemence' Compact Medium EMP Smartbomb",
    "Small 'Notos' Explosive Charge I": "'Notos' Compact Small Proton Smartbomb",
    "Medium 'Notos' Explosive Charge I": "'Notos' Compact Medium Proton Smartbomb",
    "Large 'Notos' Explosive Charge I": "'Notos' Compact Large Proton Smartbomb",
    "Small YF-12a Smartbomb": "'YF-12a' Compact Small Plasma Smartbomb",
    "Medium YF-12a Smartbomb": "'YF-12a' Compact Medium Plasma Smartbomb",
    "Large YF-12a Smartbomb": "'YF-12a' Compact Large Plasma Smartbomb",
    "Small Degenerative Concussion Bomb I": "'Degenerative' Small Proton Smartbomb",
    "Small Degenerative Concussion Bomb I Blueprint": "'Degenerative' Small Proton Smartbomb Blueprint",
    "Medium Degenerative Concussion Bomb I": "'Dwindling' Medium Proton Smartbomb",
    "Medium Degenerative Concussion Bomb I Blueprint": "'Dwindling' Medium Proton Smartbomb Blueprint",
    "Large Degenerative Concussion Bomb I": "'Regressive' Large Proton Smartbomb",
    "Large Degenerative Concussion Bomb I Blueprint": "'Regressive' Large Proton Smartbomb Blueprint",
    "'Pike' Small EMP Smartbomb I": "'Pike' Small EMP Smartbomb",
    "'Lance' Medium EMP Smartbomb I": "'Lance' Medium EMP Smartbomb",
    "'Warhammer' Large EMP Smartbomb I": "'Warhammer' Large EMP Smartbomb",
}
