"""
Conversion pack for May 2020 release
"""

CONVERSIONS = {
    # Renamed items, extracted via diff file
    "Adaptive Invulnerability Shield Hardener I": "Multispectrum Shield Hardener I",
    "Gistum C-Type Adaptive Invulnerability Shield Hardener": "Gistum C-Type Multispectrum Shield Hardener",
    "Adaptive Invulnerability Shield Hardener II": "Multispectrum Shield Hardener II",
    "Anti-Explosive Shield Hardener I": "Explosive Shield Hardener I",
    "Anti-Kinetic Shield Hardener I": "Kinetic Shield Hardener I",
    "Anti-EM Shield Hardener I": "EM Shield Hardener I",
    "Anti-Thermal Shield Hardener I": "Thermal Shield Hardener I",
    "Anti-Explosive Shield Hardener II": "Explosive Shield Hardener II",
    "Anti-Kinetic Shield Hardener II": "Kinetic Shield Hardener II",
    "Anti-EM Shield Hardener II": "EM Shield Hardener II",
    "Anti-Thermal Shield Hardener II": "Thermal Shield Hardener II",
    "Gistum B-Type Adaptive Invulnerability Shield Hardener": "Gistum B-Type Multispectrum Shield Hardener",
    "Gistum A-Type Adaptive Invulnerability Shield Hardener": "Gistum A-Type Multispectrum Shield Hardener",
    "Pithum A-Type Adaptive Invulnerability Shield Hardener": "Pithum A-Type Multispectrum Shield Hardener",
    "Pithum B-Type Adaptive Invulnerability Shield Hardener": "Pithum B-Type Multispectrum Shield Hardener",
    "Pithum C-Type Adaptive Invulnerability Shield Hardener": "Pithum C-Type Multispectrum Shield Hardener",
    "Compact Anti-Kinetic Shield Hardener": "Compact Kinetic Shield Hardener",
    "Compact Anti-EM Shield Hardener": "Compact EM Shield Hardener",
    "Compact Adaptive Invulnerability Shield Hardener": "Compact Multispectrum Shield Hardener",
    "Compact Anti-Explosive Shield Hardener": "Compact Explosive Shield Hardener",
    "Compact Anti-Thermal Shield Hardener": "Compact Thermal Shield Hardener",
    "Armor Thermal Hardener I": "Thermal Armor Hardener I",
    "Armor EM Hardener I": "EM Armor Hardener I",
    "Armor Explosive Hardener I": "Explosive Armor Hardener I",
    "Armor Kinetic Hardener I": "Kinetic Armor Hardener I",
    "Armor EM Hardener II": "EM Armor Hardener II",
    "Armor Kinetic Hardener II": "Kinetic Armor Hardener II",
    "Armor Explosive Hardener II": "Explosive Armor Hardener II",
    "Armor Thermal Hardener II": "Thermal Armor Hardener II",
    "Dread Guristas Anti-EM Shield Hardener": "Dread Guristas EM Shield Hardener",
    "Dread Guristas Anti-Thermal Shield Hardener": "Dread Guristas Thermal Shield Hardener",
    "Dread Guristas Anti-Explosive Shield Hardener": "Dread Guristas Explosive Shield Hardener",
    "Dread Guristas Anti-Kinetic Shield Hardener": "Dread Guristas Kinetic Shield Hardener",
    "Dread Guristas Adaptive Invulnerability Shield Hardener": "Dread Guristas Multispectrum Shield Hardener",
    "True Sansha Armor EM Hardener": "True Sansha EM Armor Hardener",
    "Dark Blood Armor EM Hardener": "Dark Blood EM Armor Hardener",
    "True Sansha Armor Explosive Hardener": "True Sansha Explosive Armor Hardener",
    "Dark Blood Armor Explosive Hardener": "Dark Blood Explosive Armor Hardener",
    "True Sansha Armor Kinetic Hardener": "True Sansha Kinetic Armor Hardener",
    "Dark Blood Armor Kinetic Hardener": "Dark Blood Kinetic Armor Hardener",
    "True Sansha Armor Thermal Hardener": "True Sansha Thermal Armor Hardener",
    "Dark Blood Armor Thermal Hardener": "Dark Blood Thermal Armor Hardener",
    "Domination Armor EM Hardener": "Domination EM Armor Hardener",
    "Domination Armor Explosive Hardener": "Domination Explosive Armor Hardener",
    "Domination Armor Kinetic Hardener": "Domination Kinetic Armor Hardener",
    "Domination Armor Thermal Hardener": "Domination Thermal Armor Hardener",
    "Domination Anti-EM Shield Hardener": "Domination EM Shield Hardener",
    "Domination Anti-Thermal Shield Hardener": "Domination Thermal Shield Hardener",
    "Domination Anti-Explosive Shield Hardener": "Domination Explosive Shield Hardener",
    "Domination Anti-Kinetic Shield Hardener": "Domination Kinetic Shield Hardener",
    "Domination Adaptive Invulnerability Shield Hardener": "Domination Multispectrum Shield Hardener",
    "Shadow Serpentis Armor EM Hardener": "Shadow Serpentis EM Armor Hardener",
    "Shadow Serpentis Armor Explosive Hardener": "Shadow Serpentis Explosive Armor Hardener",
    "Shadow Serpentis Armor Kinetic Hardener": "Shadow Serpentis Kinetic Armor Hardener",
    "Shadow Serpentis Armor Thermal Hardener": "Shadow Serpentis Thermal Armor Hardener",
    "Kaikka's Modified Anti-Kinetic Shield Hardener": "Kaikka's Modified Kinetic Shield Hardener",
    "Thon's Modified Anti-Kinetic Shield Hardener": "Thon's Modified Kinetic Shield Hardener",
    "Vepas's Modified Anti-Kinetic Shield Hardener": "Vepas's Modified Kinetic Shield Hardener",
    "Estamel's Modified Anti-Kinetic Shield Hardener": "Estamel's Modified Kinetic Shield Hardener",
    "Kaikka's Modified Anti-EM Shield Hardener": "Kaikka's Modified EM Shield Hardener",
    "Thon's Modified Anti-EM Shield Hardener": "Thon's Modified EM Shield Hardener",
    "Vepas's Modified Anti-EM Shield Hardener": "Vepas's Modified EM Shield Hardener",
    "Estamel's Modified Anti-EM Shield Hardener": "Estamel's Modified EM Shield Hardener",
    "Kaikka's Modified Anti-Explosive Shield Hardener": "Kaikka's Modified Explosive Shield Hardener",
    "Thon's Modified Anti-Explosive Shield Hardener": "Thon's Modified Explosive Shield Hardener",
    "Vepas's Modified Anti-Explosive Shield Hardener": "Vepas's Modified Explosive Shield Hardener",
    "Estamel's Modified Anti-Explosive Shield Hardener": "Estamel's Modified Explosive Shield Hardener",
    "Kaikka's Modified Anti-Thermal Shield Hardener": "Kaikka's Modified Thermal Shield Hardener",
    "Thon's Modified Anti-Thermal Shield Hardener": "Thon's Modified Thermal Shield Hardener",
    "Vepas's Modified Anti-Thermal Shield Hardener": "Vepas's Modified Thermal Shield Hardener",
    "Estamel's Modified Anti-Thermal Shield Hardener": "Estamel's Modified Thermal Shield Hardener",
    "Kaikka's Modified Adaptive Invulnerability Shield Hardener": "Kaikka's Modified Multispectrum Shield Hardener",
    "Thon's Modified Adaptive Invulnerability Shield Hardener": "Thon's Modified Multispectrum Shield Hardener",
    "Vepas's Modified Adaptive Invulnerability Shield Hardener": "Vepas's Modified Multispectrum Shield Hardener",
    "Estamel's Modified Adaptive Invulnerability Shield Hardener": "Estamel's Modified Multispectrum Shield Hardener",
    "Brokara's Modified Armor EM Hardener": "Brokara's Modified EM Armor Hardener",
    "Tairei's Modified Armor EM Hardener": "Tairei's Modified EM Armor Hardener",
    "Selynne's Modified Armor EM Hardener": "Selynne's Modified EM Armor Hardener",
    "Raysere's Modified Armor EM Hardener": "Raysere's Modified EM Armor Hardener",
    "Vizan's Modified Armor EM Hardener": "Vizan's Modified EM Armor Hardener",
    "Ahremen's Modified Armor EM Hardener": "Ahremen's Modified EM Armor Hardener",
    "Chelm's Modified Armor EM Hardener": "Chelm's Modified EM Armor Hardener",
    "Draclira's Modified Armor EM Hardener": "Draclira's Modified EM Armor Hardener",
    "Brokara's Modified Armor Thermal Hardener": "Brokara's Modified Thermal Armor Hardener",
    "Tairei's Modified Armor Thermal Hardener": "Tairei's Modified Thermal Armor Hardener",
    "Selynne's Modified Armor Thermal Hardener": "Selynne's Modified Thermal Armor Hardener",
    "Raysere's Modified Armor Thermal Hardener": "Raysere's Modified Thermal Armor Hardener",
    "Vizan's Modified Armor Thermal Hardener": "Vizan's Modified Thermal Armor Hardener",
    "Ahremen's Modified Armor Thermal Hardener": "Ahremen's Modified Thermal Armor Hardener",
    "Chelm's Modified Armor Thermal Hardener": "Chelm's Modified Thermal Armor Hardener",
    "Draclira's Modified Armor Thermal Hardener": "Draclira's Modified Thermal Armor Hardener",
    "Brokara's Modified Armor Kinetic Hardener": "Brokara's Modified Kinetic Armor Hardener",
    "Tairei's Modified Armor Kinetic Hardener": "Tairei's Modified Kinetic Armor Hardener",
    "Selynne's Modified Armor Kinetic Hardener": "Selynne's Modified Kinetic Armor Hardener",
    "Raysere's Modified Armor Kinetic Hardener": "Raysere's Modified Kinetic Armor Hardener",
    "Vizan's Modified Armor Kinetic Hardener": "Vizan's Modified Kinetic Armor Hardener",
    "Ahremen's Modified Armor Kinetic Hardener": "Ahremen's Modified Kinetic Armor Hardener",
    "Chelm's Modified Armor Kinetic Hardener": "Chelm's Modified Kinetic Armor Hardener",
    "Draclira's Modified Armor Kinetic Hardener": "Draclira's Modified Kinetic Armor Hardener",
    "Brokara's Modified Armor Explosive Hardener": "Brokara's Modified Explosive Armor Hardener",
    "Tairei's Modified Armor Explosive Hardener": "Tairei's Modified Explosive Armor Hardener",
    "Selynne's Modified Armor Explosive Hardener": "Selynne's Modified Explosive Armor Hardener",
    "Raysere's Modified Armor Explosive Hardener": "Raysere's Modified Explosive Armor Hardener",
    "Vizan's Modified Armor Explosive Hardener": "Vizan's Modified Explosive Armor Hardener",
    "Ahremen's Modified Armor Explosive Hardener": "Ahremen's Modified Explosive Armor Hardener",
    "Chelm's Modified Armor Explosive Hardener": "Chelm's Modified Explosive Armor Hardener",
    "Draclira's Modified Armor Explosive Hardener": "Draclira's Modified Explosive Armor Hardener",
    "Brynn's Modified Armor EM Hardener": "Brynn's Modified EM Armor Hardener",
    "Tuvan's Modified Armor EM Hardener": "Tuvan's Modified EM Armor Hardener",
    "Setele's Modified Armor EM Hardener": "Setele's Modified EM Armor Hardener",
    "Cormack's Modified Armor EM Hardener": "Cormack's Modified EM Armor Hardener",
    "Brynn's Modified Armor Thermal Hardener": "Brynn's Modified Thermal Armor Hardener",
    "Tuvan's Modified Armor Thermal Hardener": "Tuvan's Modified Thermal Armor Hardener",
    "Setele's Modified Armor Thermal Hardener": "Setele's Modified Thermal Armor Hardener",
    "Cormack's Modified Armor Thermal Hardener": "Cormack's Modified Thermal Armor Hardener",
    "Brynn's Modified Armor Kinetic Hardener": "Brynn's Modified Kinetic Armor Hardener",
    "Tuvan's Modified Armor Kinetic Hardener": "Tuvan's Modified Kinetic Armor Hardener",
    "Setele's Modified Armor Kinetic Hardener": "Setele's Modified Kinetic Armor Hardener",
    "Cormack's Modified Armor Kinetic Hardener": "Cormack's Modified Kinetic Armor Hardener",
    "Brynn's Modified Armor Explosive Hardener": "Brynn's Modified Explosive Armor Hardener",
    "Tuvan's Modified Armor Explosive Hardener": "Tuvan's Modified Explosive Armor Hardener",
    "Setele's Modified Armor Explosive Hardener": "Setele's Modified Explosive Armor Hardener",
    "Cormack's Modified Armor Explosive Hardener": "Cormack's Modified Explosive Armor Hardener",
    "Imperial Navy Armor Thermal Hardener": "Imperial Navy Thermal Armor Hardener",
    "Imperial Navy Armor Kinetic Hardener": "Imperial Navy Kinetic Armor Hardener",
    "Imperial Navy Armor Explosive Hardener": "Imperial Navy Explosive Armor Hardener",
    "Imperial Navy Armor EM Hardener": "Imperial Navy EM Armor Hardener",
    "Republic Fleet Armor Thermal Hardener": "Republic Fleet Thermal Armor Hardener",
    "Republic Fleet Armor Kinetic Hardener": "Republic Fleet Kinetic Armor Hardener",
    "Republic Fleet Armor Explosive Hardener": "Republic Fleet Explosive Armor Hardener",
    "Republic Fleet Armor EM Hardener": "Republic Fleet EM Armor Hardener",
    "Experimental Armor EM Hardener I": "Experimental Enduring EM Armor Hardener I",
    "Prototype Armor EM Hardener I": "Prototype Compact EM Armor Hardener I",
    "Experimental Armor Explosive Hardener I": "Experimental Enduring Explosive Armor Hardener I",
    "Prototype Armor Explosive Hardener I": "Prototype Compact Explosive Armor Hardener I",
    "Experimental Armor Kinetic Hardener I": "Experimental Enduring Kinetic Armor Hardener I",
    "Prototype Armor Kinetic Hardener I": "Prototype Compact Kinetic Armor Hardener I",
    "Experimental Armor Thermal Hardener I": "Experimental Enduring Thermal Armor Hardener I",
    "Prototype Armor Thermal Hardener I": "Prototype Compact Thermal Armor Hardener I",
    "Caldari Navy Anti-Kinetic Shield Hardener": "Caldari Navy Kinetic Shield Hardener",
    "Caldari Navy Anti-Explosive Shield Hardener": "Caldari Navy Explosive Shield Hardener",
    "Caldari Navy Anti-Thermal Shield Hardener": "Caldari Navy Thermal Shield Hardener",
    "Caldari Navy Adaptive Invulnerability Shield Hardener": "Caldari Navy Multispectrum Shield Hardener",
    "Caldari Navy Anti-EM Shield Hardener": "Caldari Navy EM Shield Hardener",
    "Ammatar Navy Armor EM Hardener": "Ammatar Navy EM Armor Hardener",
    "Ammatar Navy Armor Explosive Hardener": "Ammatar Navy Explosive Armor Hardener",
    "Ammatar Navy Armor Kinetic Hardener": "Ammatar Navy Kinetic Armor Hardener",
    "Ammatar Navy Armor Thermal Hardener": "Ammatar Navy Thermal Armor Hardener",
    "Federation Navy Armor EM Hardener": "Federation Navy EM Armor Hardener",
    "Federation Navy Armor Explosive Hardener": "Federation Navy Explosive Armor Hardener",
    "Federation Navy Armor Kinetic Hardener": "Federation Navy Kinetic Armor Hardener",
    "Federation Navy Armor Thermal Hardener": "Federation Navy Thermal Armor Hardener",
    "Corpus C-Type Armor EM Hardener": "Corpus C-Type EM Armor Hardener",
    "Centus C-Type Armor EM Hardener": "Centus C-Type EM Armor Hardener",
    "Corpus C-Type Armor Explosive Hardener": "Corpus C-Type Explosive Armor Hardener",
    "Centus C-Type Armor Explosive Hardener": "Centus C-Type Explosive Armor Hardener",
    "Corpus C-Type Armor Kinetic Hardener": "Corpus C-Type Kinetic Armor Hardener",
    "Centus C-Type Armor Kinetic Hardener": "Centus C-Type Kinetic Armor Hardener",
    "Corpus C-Type Armor Thermal Hardener": "Corpus C-Type Thermal Armor Hardener",
    "Centus C-Type Armor Thermal Hardener": "Centus C-Type Thermal Armor Hardener",
    "Corpus B-Type Armor EM Hardener": "Corpus B-Type EM Armor Hardener",
    "Centus B-Type Armor EM Hardener": "Centus B-Type EM Armor Hardener",
    "Corpus B-Type Armor Explosive Hardener": "Corpus B-Type Explosive Armor Hardener",
    "Centus B-Type Armor Explosive Hardener": "Centus B-Type Explosive Armor Hardener",
    "Corpus B-Type Armor Kinetic Hardener": "Corpus B-Type Kinetic Armor Hardener",
    "Centus B-Type Armor Kinetic Hardener": "Centus B-Type Kinetic Armor Hardener",
    "Corpus B-Type Armor Thermal Hardener": "Corpus B-Type Thermal Armor Hardener",
    "Centus B-Type Armor Thermal Hardener": "Centus B-Type Thermal Armor Hardener",
    "Corpus A-Type Armor Thermal Hardener": "Corpus A-Type Thermal Armor Hardener",
    "Centus A-Type Armor Thermal Hardener": "Centus A-Type Thermal Armor Hardener",
    "Corpus A-Type Armor Kinetic Hardener": "Corpus A-Type Kinetic Armor Hardener",
    "Centus A-Type Armor Kinetic Hardener": "Centus A-Type Kinetic Armor Hardener",
    "Corpus A-Type Armor Explosive Hardener": "Corpus A-Type Explosive Armor Hardener",
    "Centus A-Type Armor Explosive Hardener": "Centus A-Type Explosive Armor Hardener",
    "Corpus A-Type Armor EM Hardener": "Corpus A-Type EM Armor Hardener",
    "Centus A-Type Armor EM Hardener": "Centus A-Type EM Armor Hardener",
    "Corpus X-Type Armor EM Hardener": "Corpus X-Type EM Armor Hardener",
    "Centus X-Type Armor EM Hardener": "Centus X-Type EM Armor Hardener",
    "Corpus X-Type Armor Explosive Hardener": "Corpus X-Type Explosive Armor Hardener",
    "Centus X-Type Armor Explosive Hardener": "Centus X-Type Explosive Armor Hardener",
    "Corpus X-Type Armor Kinetic Hardener": "Corpus X-Type Kinetic Armor Hardener",
    "Centus X-Type Armor Kinetic Hardener": "Centus X-Type Kinetic Armor Hardener",
    "Corpus X-Type Armor Thermal Hardener": "Corpus X-Type Thermal Armor Hardener",
    "Centus X-Type Armor Thermal Hardener": "Centus X-Type Thermal Armor Hardener",
    "Core C-Type Armor EM Hardener": "Core C-Type EM Armor Hardener",
    "Core C-Type Armor Explosive Hardener": "Core C-Type Explosive Armor Hardener",
    "Core C-Type Armor Kinetic Hardener": "Core C-Type Kinetic Armor Hardener",
    "Core C-Type Armor Thermal Hardener": "Core C-Type Thermal Armor Hardener",
    "Core B-Type Armor EM Hardener": "Core B-Type EM Armor Hardener",
    "Core B-Type Armor Explosive Hardener": "Core B-Type Explosive Armor Hardener",
    "Core B-Type Armor Kinetic Hardener": "Core B-Type Kinetic Armor Hardener",
    "Core B-Type Armor Thermal Hardener": "Core B-Type Thermal Armor Hardener",
    "Core A-Type Armor EM Hardener": "Core A-Type EM Armor Hardener",
    "Core A-Type Armor Explosive Hardener": "Core A-Type Explosive Armor Hardener",
    "Core A-Type Armor Kinetic Hardener": "Core A-Type Kinetic Armor Hardener",
    "Core A-Type Armor Thermal Hardener": "Core A-Type Thermal Armor Hardener",
    "Core X-Type Armor EM Hardener": "Core X-Type EM Armor Hardener",
    "Core X-Type Armor Explosive Hardener": "Core X-Type Explosive Armor Hardener",
    "Core X-Type Armor Kinetic Hardener": "Core X-Type Kinetic Armor Hardener",
    "Core X-Type Armor Thermal Hardener": "Core X-Type Thermal Armor Hardener",
    "Gist C-Type Anti-Kinetic Shield Hardener": "Gist C-Type Kinetic Shield Hardener",
    "Pith C-Type Anti-Kinetic Shield Hardener": "Pith C-Type Kinetic Shield Hardener",
    "Gist C-Type Anti-Explosive Shield Hardener": "Gist C-Type Explosive Shield Hardener",
    "Pith C-Type Anti-Explosive Shield Hardener": "Pith C-Type Explosive Shield Hardener",
    "Gist C-Type Anti-Thermal Shield Hardener": "Gist C-Type Thermal Shield Hardener",
    "Pith C-Type Anti-Thermal Shield Hardener": "Pith C-Type Thermal Shield Hardener",
    "Gist C-Type Anti-EM Shield Hardener": "Gist C-Type EM Shield Hardener",
    "Pith C-Type Anti-EM Shield Hardener": "Pith C-Type EM Shield Hardener",
    "Gist B-Type Anti-EM Shield Hardener": "Gist B-Type EM Shield Hardener",
    "Pith B-Type Anti-EM Shield Hardener": "Pith B-Type EM Shield Hardener",
    "Gist B-Type Anti-Thermal Shield Hardener": "Gist B-Type Thermal Shield Hardener",
    "Pith B-Type Anti-Thermal Shield Hardener": "Pith B-Type Thermal Shield Hardener",
    "Gist B-Type Anti-Explosive Shield Hardener": "Gist B-Type Explosive Shield Hardener",
    "Pith B-Type Anti-Explosive Shield Hardener": "Pith B-Type Explosive Shield Hardener",
    "Gist B-Type Anti-Kinetic Shield Hardener": "Gist B-Type Kinetic Shield Hardener",
    "Pith B-Type Anti-Kinetic Shield Hardener": "Pith B-Type Kinetic Shield Hardener",
    "Gist A-Type Anti-Kinetic Shield Hardener": "Gist A-Type Kinetic Shield Hardener",
    "Pith A-Type Anti-Kinetic Shield Hardener": "Pith A-Type Kinetic Shield Hardener",
    "Gist A-Type Anti-Explosive Shield Hardener": "Gist A-Type Explosive Shield Hardener",
    "Pith A-Type Anti-Explosive Shield Hardener": "Pith A-Type Explosive Shield Hardener",
    "Gist A-Type Anti-Thermal Shield Hardener": "Gist A-Type Thermal Shield Hardener",
    "Pith A-Type Anti-Thermal Shield Hardener": "Pith A-Type Thermal Shield Hardener",
    "Gist A-Type Anti-EM Shield Hardener": "Gist A-Type EM Shield Hardener",
    "Pith A-Type Anti-EM Shield Hardener": "Pith A-Type EM Shield Hardener",
    "Gist X-Type Anti-EM Shield Hardener": "Gist X-Type EM Shield Hardener",
    "Pith X-Type Anti-EM Shield Hardener": "Pith X-Type EM Shield Hardener",
    "Gist X-Type Anti-Thermal Shield Hardener": "Gist X-Type Thermal Shield Hardener",
    "Pith X-Type Anti-Thermal Shield Hardener": "Pith X-Type Thermal Shield Hardener",
    "Gist X-Type Anti-Explosive Shield Hardener": "Gist X-Type Explosive Shield Hardener",
    "Pith X-Type Anti-Explosive Shield Hardener": "Pith X-Type Explosive Shield Hardener",
    "Gist X-Type Anti-Kinetic Shield Hardener": "Gist X-Type Kinetic Shield Hardener",
    "Pith X-Type Anti-Kinetic Shield Hardener": "Pith X-Type Kinetic Shield Hardener",
    "'Nugget' Anti-Kinetic Shield Hardener": "'Nugget' Kinetic Shield Hardener",
    "'Desert Heat' Anti-Thermal Shield Hardener": "'Desert Heat' Thermal Shield Hardener",
    "'Posse' Adaptive Invulnerability Shield Hardener": "'Posse' Multispectrum Shield Hardener",
    "'Poacher' Anti-EM Shield Hardener": "'Poacher' EM Shield Hardener",
    "'Snake Eyes' Anti-Explosive Shield Hardener": "'Snake Eyes' Explosive Shield Hardener",
    "Large Anti-EM Pump I": "Large EM Armor Reinforcer I",
    "Large Anti-Explosive Pump I": "Large Explosive Armor Reinforcer I",
    "Large Anti-Kinetic Pump I": "Large Kinetic Armor Reinforcer I",
    "Large Anti-Thermal Pump I": "Large Thermal Armor Reinforcer I",
    "Large Anti-EM Screen Reinforcer I": "Large EM Shield Reinforcer I",
    "Large Anti-Explosive Screen Reinforcer I": "Large Explosive Shield Reinforcer I",
    "Large Anti-Kinetic Screen Reinforcer I": "Large Kinetic Shield Reinforcer I",
    "Large Anti-Thermal Screen Reinforcer I": "Large Thermal Shield Reinforcer I",
    "Large Anti-EM Pump II": "Large EM Armor Reinforcer II",
    "Large Anti-Explosive Pump II": "Large Explosive Armor Reinforcer II",
    "Large Anti-Kinetic Pump II": "Large Kinetic Armor Reinforcer II",
    "Large Anti-Thermal Pump II": "Large Thermal Armor Reinforcer II",
    "Large Anti-EM Screen Reinforcer II": "Large EM Shield Reinforcer II",
    "Large Anti-Explosive Screen Reinforcer II": "Large Explosive Shield Reinforcer II",
    "Large Anti-Kinetic Screen Reinforcer II": "Large Kinetic Shield Reinforcer II",
    "Large Anti-Thermal Screen Reinforcer II": "Large Thermal Shield Reinforcer II",
    "Khanid Navy Armor EM Hardener": "Khanid Navy EM Armor Hardener",
    "Khanid Navy Armor Explosive Hardener": "Khanid Navy Explosive Armor Hardener",
    "Khanid Navy Armor Kinetic Hardener": "Khanid Navy Kinetic Armor Hardener",
    "Khanid Navy Armor Thermal Hardener": "Khanid Navy Thermal Armor Hardener",
    "Civilian Anti-Thermal Shield Hardener": "Civilian Thermal Shield Hardener",
    "Civilian Anti-EM Shield Hardener": "Civilian EM Shield Hardener",
    "Civilian Anti-Explosive Shield Hardener": "Civilian Explosive Shield Hardener",
    "Civilian Anti-Kinetic Shield Hardener": "Civilian Kinetic Shield Hardener",
    "Small Anti-EM Pump I": "Small EM Armor Reinforcer I",
    "Medium Anti-EM Pump I": "Medium EM Armor Reinforcer I",
    "Capital Anti-EM Pump I": "Capital EM Armor Reinforcer I",
    "Small Anti-EM Pump II": "Small EM Armor Reinforcer II",
    "Medium Anti-EM Pump II": "Medium EM Armor Reinforcer II",
    "Capital Anti-EM Pump II": "Capital EM Armor Reinforcer II",
    "Small Anti-Explosive Pump I": "Small Explosive Armor Reinforcer I",
    "Medium Anti-Explosive Pump I": "Medium Explosive Armor Reinforcer I",
    "Capital Anti-Explosive Pump I": "Capital Explosive Armor Reinforcer I",
    "Small Anti-Explosive Pump II": "Small Explosive Armor Reinforcer II",
    "Medium Anti-Explosive Pump II": "Medium Explosive Armor Reinforcer II",
    "Capital Anti-Explosive Pump II": "Capital Explosive Armor Reinforcer II",
    "Small Anti-Kinetic Pump I": "Small Kinetic Armor Reinforcer I",
    "Medium Anti-Kinetic Pump I": "Medium Kinetic Armor Reinforcer I",
    "Capital Anti-Kinetic Pump I": "Capital Kinetic Armor Reinforcer I",
    "Small Anti-Kinetic Pump II": "Small Kinetic Armor Reinforcer II",
    "Medium Anti-Kinetic Pump II": "Medium Kinetic Armor Reinforcer II",
    "Capital Anti-Kinetic Pump II": "Capital Kinetic Armor Reinforcer II",
    "Small Anti-Thermal Pump I": "Small Thermal Armor Reinforcer I",
    "Medium Anti-Thermal Pump I": "Medium Thermal Armor Reinforcer I",
    "Capital Anti-Thermal Pump I": "Capital Thermal Armor Reinforcer I",
    "Small Anti-Thermal Pump II": "Small Thermal Armor Reinforcer II",
    "Medium Anti-Thermal Pump II": "Medium Thermal Armor Reinforcer II",
    "Capital Anti-Thermal Pump II": "Capital Thermal Armor Reinforcer II",
    "Small Anti-EM Screen Reinforcer I": "Small EM Shield Reinforcer I",
    "Medium Anti-EM Screen Reinforcer I": "Medium EM Shield Reinforcer I",
    "Capital Anti-EM Screen Reinforcer I": "Capital EM Shield Reinforcer I",
    "Small Anti-EM Screen Reinforcer II": "Small EM Shield Reinforcer II",
    "Medium Anti-EM Screen Reinforcer II": "Medium EM Shield Reinforcer II",
    "Capital Anti-EM Screen Reinforcer II": "Capital EM Shield Reinforcer II",
    "Small Anti-Explosive Screen Reinforcer I": "Small Explosive Shield Reinforcer I",
    "Medium Anti-Explosive Screen Reinforcer I": "Medium Explosive Shield Reinforcer I",
    "Capital Anti-Explosive Screen Reinforcer I": "Capital Explosive Shield Reinforcer I",
    "Small Anti-Explosive Screen Reinforcer II": "Small Explosive Shield Reinforcer II",
    "Medium Anti-Explosive Screen Reinforcer II": "Medium Explosive Shield Reinforcer II",
    "Capital Anti-Explosive Screen Reinforcer II": "Capital Explosive Shield Reinforcer II",
    "Small Anti-Kinetic Screen Reinforcer I": "Small Kinetic Shield Reinforcer I",
    "Medium Anti-Kinetic Screen Reinforcer I": "Medium Kinetic Shield Reinforcer I",
    "Capital Anti-Kinetic Screen Reinforcer I": "Capital Kinetic Shield Reinforcer I",
    "Small Anti-Kinetic Screen Reinforcer II": "Small Kinetic Shield Reinforcer II",
    "Medium Anti-Kinetic Screen Reinforcer II": "Medium Kinetic Shield Reinforcer II",
    "Capital Anti-Kinetic Screen Reinforcer II": "Capital Kinetic Shield Reinforcer II",
    "Small Anti-Thermal Screen Reinforcer I": "Small Thermal Shield Reinforcer I",
    "Medium Anti-Thermal Screen Reinforcer I": "Medium Thermal Shield Reinforcer I",
    "Capital Anti-Thermal Screen Reinforcer I": "Capital Thermal Shield Reinforcer I",
    "Small Anti-Thermal Screen Reinforcer II": "Small Thermal Shield Reinforcer II",
    "Medium Anti-Thermal Screen Reinforcer II": "Medium Thermal Shield Reinforcer II",
    "Capital Anti-Thermal Screen Reinforcer II": "Capital Thermal Shield Reinforcer II",
    "Enduring Adaptive Invulnerability Shield Hardener": "Enduring Multispectrum Shield Hardener",
    "Enduring Anti-EM Shield Hardener": "Enduring EM Shield Hardener",
    "Enduring Anti-Explosive Shield Hardener": "Enduring Explosive Shield Hardener",
    "Enduring Anti-Kinetic Shield Hardener": "Enduring Kinetic Shield Hardener",
    "Enduring Anti-Thermal Shield Hardener": "Enduring Thermal Shield Hardener",
    # Converted items
    "Upgraded Armor EM Hardener I": "Experimental Enduring EM Armor Hardener I",
    "Upgraded Armor Explosive Hardener I": "Experimental Enduring Explosive Armor Hardener I",
    "Upgraded Armor Kinetic Hardener I": "Experimental Enduring Kinetic Armor Hardener I",
    "Upgraded Armor Thermal Hardener I": "Experimental Enduring Thermal Armor Hardener I",
    "Limited Armor EM Hardener I": "Prototype Compact EM Armor Hardener I",
    "Limited Armor Explosive Hardener I": "Prototype Compact Explosive Armor Hardener I",
    "Limited Armor Kinetic Hardener I": "Prototype Compact Kinetic Armor Hardener I",
    "Limited Armor Thermal Hardener I": "Prototype Compact Thermal Armor Hardener I",

}
