"""
Conversion pack for August 2020 release
"""

CONVERSIONS = {
    # Renamed items, extracted via diff file
    "Basic Energized EM Membrane": "'Basic' EM Energized Membrane",
    "Energized EM Membrane I": "EM Energized Membrane I",
    "Energized EM Membrane II": "EM Energized Membrane II",
    "Basic Energized Explosive Membrane": "'Basic' Explosive Energized Membrane",
    "Energized Explosive Membrane I": "Explosive Energized Membrane I",
    "Energized Explosive Membrane II": "Explosive Energized Membrane II",
    "Basic Energized Armor Layering Membrane": "'Basic' Layered Energized Membrane",
    "Energized Armor Layering Membrane I": "Layered Energized Membrane I",
    "Energized Armor Layering Membrane II": "Layered Energized Membrane II",
    "Basic Energized Kinetic Membrane": "'Basic' Kinetic Energized Membrane",
    "Energized Kinetic Membrane I": "Kinetic Energized Membrane I",
    "Energized Kinetic Membrane II": "Kinetic Energized Membrane II",
    "Basic Energized Thermal Membrane": "'Basic' Thermal Energized Membrane",
    "Energized Thermal Membrane I": "Thermal Energized Membrane I",
    "Energized Thermal Membrane II": "Thermal Energized Membrane II",
    "Basic Energized Adaptive Nano Membrane": "'Basic' Multispectrum Energized Membrane",
    "Energized Adaptive Nano Membrane I": "Multispectrum Energized Membrane I",
    "Energized Adaptive Nano Membrane II": "Multispectrum Energized Membrane II",
    "Dark Blood Energized Adaptive Nano Membrane": "Dark Blood Multispectrum Energized Membrane",
    "True Sansha Energized Adaptive Nano Membrane": "True Sansha Multispectrum Energized Membrane",
    "Shadow Serpentis Energized Adaptive Nano Membrane": "Shadow Serpentis Multispectrum Energized Membrane",
    "Dark Blood Energized Kinetic Membrane": "Dark Blood Kinetic Energized Membrane",
    "True Sansha Energized Kinetic Membrane": "True Sansha Kinetic Energized Membrane",
    "Shadow Serpentis Energized Kinetic Membrane": "Shadow Serpentis Kinetic Energized Membrane",
    "Dark Blood Energized Explosive Membrane": "Dark Blood Explosive Energized Membrane",
    "True Sansha Energized Explosive Membrane": "True Sansha Explosive Energized Membrane",
    "Shadow Serpentis Energized Explosive Membrane": "Shadow Serpentis Explosive Energized Membrane",
    "Dark Blood Energized EM Membrane": "Dark Blood EM Energized Membrane",
    "True Sansha Energized EM Membrane": "True Sansha EM Energized Membrane",
    "Shadow Serpentis Energized EM Membrane": "Shadow Serpentis EM Energized Membrane",
    "Dark Blood Energized Thermal Membrane": "Dark Blood Thermal Energized Membrane",
    "True Sansha Energized Thermal Membrane": "True Sansha Thermal Energized Membrane",
    "Shadow Serpentis Energized Thermal Membrane": "Shadow Serpentis Thermal Energized Membrane",
    "Brokara's Modified Energized Adaptive Nano Membrane": "Brokara's Modified Multispectrum Energized Membrane",
    "Tairei's Modified Energized Adaptive Nano Membrane": "Tairei's Modified Multispectrum Energized Membrane",
    "Selynne's Modified Energized Adaptive Nano Membrane": "Selynne's Modified Multispectrum Energized Membrane",
    "Raysere's Modified Energized Adaptive Nano Membrane": "Raysere's Modified Multispectrum Energized Membrane",
    "Vizan's Modified Energized Adaptive Nano Membrane": "Vizan's Modified Multispectrum Energized Membrane",
    "Ahremen's Modified Energized Adaptive Nano Membrane": "Ahremen's Modified Multispectrum Energized Membrane",
    "Chelm's Modified Energized Adaptive Nano Membrane": "Chelm's Modified Multispectrum Energized Membrane",
    "Draclira's Modified Energized Adaptive Nano Membrane": "Draclira's Modified Multispectrum Energized Membrane",
    "Brokara's Modified Energized Thermal Membrane": "Brokara's Modified Thermal Energized Membrane",
    "Tairei's Modified Energized Thermal Membrane": "Tairei's Modified Thermal Energized Membrane",
    "Selynne's Modified Energized Thermal Membrane": "Selynne's Modified Thermal Energized Membrane",
    "Raysere's Modified Energized Thermal Membrane": "Raysere's Modified Thermal Energized Membrane",
    "Vizan's Modified Energized Thermal Membrane": "Vizan's Modified Thermal Energized Membrane",
    "Ahremen's Modified Energized Thermal Membrane": "Ahremen's Modified Thermal Energized Membrane",
    "Chelm's Modified Energized Thermal Membrane": "Chelm's Modified Thermal Energized Membrane",
    "Draclira's Modified Energized Thermal Membrane": "Draclira's Modified Thermal Energized Membrane",
    "Brokara's Modified Energized EM Membrane": "Brokara's Modified EM Energized Membrane",
    "Tairei's Modified Energized EM Membrane": "Tairei's Modified EM Energized Membrane",
    "Selynne's Modified Energized EM Membrane": "Selynne's Modified EM Energized Membrane",
    "Raysere's Modified Energized EM Membrane": "Raysere's Modified EM Energized Membrane",
    "Vizan's Modified Energized EM Membrane": "Vizan's Modified EM Energized Membrane",
    "Ahremen's Modified Energized EM Membrane": "Ahremen's Modified EM Energized Membrane",
    "Chelm's Modified Energized EM Membrane": "Chelm's Modified EM Energized Membrane",
    "Draclira's Modified Energized EM Membrane": "Draclira's Modified EM Energized Membrane",
    "Brokara's Modified Energized Explosive Membrane": "Brokara's Modified Explosive Energized Membrane",
    "Tairei's Modified Energized Explosive Membrane": "Tairei's Modified Explosive Energized Membrane",
    "Selynne's Modified Energized Explosive Membrane": "Selynne's Modified Explosive Energized Membrane",
    "Raysere's Modified Energized Explosive Membrane": "Raysere's Modified Explosive Energized Membrane",
    "Vizan's Modified Energized Explosive Membrane": "Vizan's Modified Explosive Energized Membrane",
    "Ahremen's Modified Energized Explosive Membrane": "Ahremen's Modified Explosive Energized Membrane",
    "Chelm's Modified Energized Explosive Membrane": "Chelm's Modified Explosive Energized Membrane",
    "Draclira's Modified Energized Explosive Membrane": "Draclira's Modified Explosive Energized Membrane",
    "Brokara's Modified Energized Kinetic Membrane": "Brokara's Modified Kinetic Energized Membrane",
    "Tairei's Modified Energized Kinetic Membrane": "Tairei's Modified Kinetic Energized Membrane",
    "Selynne's Modified Energized Kinetic Membrane": "Selynne's Modified Kinetic Energized Membrane",
    "Raysere's Modified Energized Kinetic Membrane": "Raysere's Modified Kinetic Energized Membrane",
    "Vizan's Modified Energized Kinetic Membrane": "Vizan's Modified Kinetic Energized Membrane",
    "Ahremen's Modified Energized Kinetic Membrane": "Ahremen's Modified Kinetic Energized Membrane",
    "Chelm's Modified Energized Kinetic Membrane": "Chelm's Modified Kinetic Energized Membrane",
    "Draclira's Modified Energized Kinetic Membrane": "Draclira's Modified Kinetic Energized Membrane",
    "Brynn's Modified Energized Adaptive Nano Membrane": "Brynn's Modified Multispectrum Energized Membrane",
    "Tuvan's Modified Energized Adaptive Nano Membrane": "Tuvan's Modified Multispectrum Energized Membrane",
    "Setele's Modified Energized Adaptive Nano Membrane": "Setele's Modified Multispectrum Energized Membrane",
    "Cormack's Modified Energized Adaptive Nano Membrane": "Cormack's Modified Multispectrum Energized Membrane",
    "Brynn's Modified Energized Thermal Membrane": "Brynn's Modified Thermal Energized Membrane",
    "Tuvan's Modified Energized Thermal Membrane": "Tuvan's Modified Thermal Energized Membrane",
    "Setele's Modified Energized Thermal Membrane": "Setele's Modified Thermal Energized Membrane",
    "Cormack's Modified Energized Thermal Membrane": "Cormack's Modified Thermal Energized Membrane",
    "Brynn's Modified Energized EM Membrane": "Brynn's Modified EM Energized Membrane",
    "Tuvan's Modified Energized EM Membrane": "Tuvan's Modified EM Energized Membrane",
    "Setele's Modified Energized EM Membrane": "Setele's Modified EM Energized Membrane",
    "Cormack's Modified Energized EM Membrane": "Cormack's Modified EM Energized Membrane",
    "Brynn's Modified Energized Explosive Membrane": "Brynn's Modified Explosive Energized Membrane",
    "Tuvan's Modified Energized Explosive Membrane": "Tuvan's Modified Explosive Energized Membrane",
    "Setele's Modified Energized Explosive Membrane": "Setele's Modified Explosive Energized Membrane",
    "Cormack's Modified Energized Explosive Membrane": "Cormack's Modified Explosive Energized Membrane",
    "Brynn's Modified Energized Kinetic Membrane": "Brynn's Modified Kinetic Energized Membrane",
    "Tuvan's Modified Energized Kinetic Membrane": "Tuvan's Modified Kinetic Energized Membrane",
    "Setele's Modified Energized Kinetic Membrane": "Setele's Modified Kinetic Energized Membrane",
    "Cormack's Modified Energized Kinetic Membrane": "Cormack's Modified Kinetic Energized Membrane",
    "Imperial Navy Energized Thermal Membrane": "Imperial Navy Thermal Energized Membrane",
    "Imperial Navy Energized EM Membrane": "Imperial Navy EM Energized Membrane",
    "Imperial Navy Energized Explosive Membrane": "Imperial Navy Explosive Energized Membrane",
    "Imperial Navy Energized Kinetic Membrane": "Imperial Navy Kinetic Energized Membrane",
    "Imperial Navy Energized Adaptive Nano Membrane": "Imperial Navy Multispectrum Energized Membrane",
    "Federation Navy Energized Thermal Membrane": "Federation Navy Thermal Energized Membrane",
    "Federation Navy Energized EM Membrane": "Federation Navy EM Energized Membrane",
    "Federation Navy Energized Explosive Membrane": "Federation Navy Explosive Energized Membrane",
    "Federation Navy Energized Kinetic Membrane": "Federation Navy Kinetic Energized Membrane",
    "Federation Navy Energized Adaptive Nano Membrane": "Federation Navy Multispectrum Energized Membrane",
    "Prototype Energized Adaptive Nano Membrane I": "Compact Multispectrum Energized Membrane",
    "Prototype Energized Kinetic Membrane I": "Compact Kinetic Energized Membrane",
    "Prototype Energized Explosive Membrane I": "Compact Explosive Energized Membrane",
    "Prototype Energized EM Membrane I": "Compact EM Energized Membrane",
    "Prototype Energized Armor Layering Membrane I": "Compact Layered Energized Membrane",
    "Prototype Energized Thermal Membrane I": "Compact Thermal Energized Membrane",
    "Ammatar Navy Energized Adaptive Nano Membrane": "Ammatar Navy Multispectrum Energized Membrane",
    "Ammatar Navy Energized Kinetic Membrane": "Ammatar Navy Kinetic Energized Membrane",
    "Ammatar Navy Energized Explosive Membrane": "Ammatar Navy Explosive Energized Membrane",
    "Ammatar Navy Energized EM Membrane": "Ammatar Navy EM Energized Membrane",
    "Ammatar Navy Energized Thermal Membrane": "Ammatar Navy Thermal Energized Membrane",
    "Corelum C-Type Energized Adaptive Nano Membrane": "Corelum C-Type Multispectrum Energized Membrane",
    "Corelum C-Type Energized Kinetic Membrane": "Corelum C-Type Kinetic Energized Membrane",
    "Corelum C-Type Energized Explosive Membrane": "Corelum C-Type Explosive Energized Membrane",
    "Corelum C-Type Energized EM Membrane": "Corelum C-Type EM Energized Membrane",
    "Corelum C-Type Energized Thermal Membrane": "Corelum C-Type Thermal Energized Membrane",
    "Corelum B-Type Energized Adaptive Nano Membrane": "Corelum B-Type Multispectrum Energized Membrane",
    "Corelum B-Type Energized Kinetic Membrane": "Corelum B-Type Kinetic Energized Membrane",
    "Corelum B-Type Energized Explosive Membrane": "Corelum B-Type Explosive Energized Membrane",
    "Corelum B-Type Energized EM Membrane": "Corelum B-Type EM Energized Membrane",
    "Corelum B-Type Energized Thermal Membrane": "Corelum B-Type Thermal Energized Membrane",
    "Corelum A-Type Energized Adaptive Nano Membrane": "Corelum A-Type Multispectrum Energized Membrane",
    "Corelum A-Type Energized Kinetic Membrane": "Corelum A-Type Kinetic Energized Membrane",
    "Corelum A-Type Energized Explosive Membrane": "Corelum A-Type Explosive Energized Membrane",
    "Corelum A-Type Energized EM Membrane": "Corelum A-Type EM Energized Membrane",
    "Corelum A-Type Energized Thermal Membrane": "Corelum A-Type Thermal Energized Membrane",
    "Corpum C-Type Energized Adaptive Nano Membrane": "Corpum C-Type Multispectrum Energized Membrane",
    "Centum C-Type Energized Adaptive Nano Membrane": "Centum C-Type Multispectrum Energized Membrane",
    "Corpum C-Type Energized Kinetic Membrane": "Corpum C-Type Kinetic Energized Membrane",
    "Centum C-Type Energized Kinetic Membrane": "Centum C-Type Kinetic Energized Membrane",
    "Corpum C-Type Energized Explosive Membrane": "Corpum C-Type Explosive Energized Membrane",
    "Centum C-Type Energized Explosive Membrane": "Centum C-Type Explosive Energized Membrane",
    "Corpum C-Type Energized EM Membrane": "Corpum C-Type EM Energized Membrane",
    "Centum C-Type Energized EM Membrane": "Centum C-Type EM Energized Membrane",
    "Corpum C-Type Energized Thermal Membrane": "Corpum C-Type Thermal Energized Membrane",
    "Centum C-Type Energized Thermal Membrane": "Centum C-Type Thermal Energized Membrane",
    "Corpum B-Type Energized Adaptive Nano Membrane": "Corpum B-Type Multispectrum Energized Membrane",
    "Centum B-Type Energized Adaptive Nano Membrane": "Centum B-Type Multispectrum Energized Membrane",
    "Corpum B-Type Energized Kinetic Membrane": "Corpum B-Type Kinetic Energized Membrane",
    "Centum B-Type Energized Kinetic Membrane": "Centum B-Type Kinetic Energized Membrane",
    "Corpum B-Type Energized Explosive Membrane": "Corpum B-Type Explosive Energized Membrane",
    "Centum B-Type Energized Explosive Membrane": "Centum B-Type Explosive Energized Membrane",
    "Corpum B-Type Energized Thermal Membrane": "Corpum B-Type Thermal Energized Membrane",
    "Centum B-Type Energized Thermal Membrane": "Centum B-Type Thermal Energized Membrane",
    "Corpum A-Type Energized Thermal Membrane": "Corpum A-Type Thermal Energized Membrane",
    "Centum A-Type Energized Thermal Membrane": "Centum A-Type Thermal Energized Membrane",
    "Corpum A-Type Energized EM Membrane": "Corpum A-Type EM Energized Membrane",
    "Centum A-Type Energized EM Membrane": "Centum A-Type EM Energized Membrane",
    "Corpum A-Type Energized Explosive Membrane": "Corpum A-Type Explosive Energized Membrane",
    "Centum A-Type Energized Explosive Membrane": "Centum A-Type Explosive Energized Membrane",
    "Corpum A-Type Energized Kinetic Membrane": "Corpum A-Type Kinetic Energized Membrane",
    "Centum A-Type Energized Kinetic Membrane": "Centum A-Type Kinetic Energized Membrane",
    "Corpum A-Type Energized Adaptive Nano Membrane": "Corpum A-Type Multispectrum Energized Membrane",
    "Centum A-Type Energized Adaptive Nano Membrane": "Centum A-Type Multispectrum Energized Membrane",
    "Corpum B-Type Energized EM Membrane": "Corpum B-Type EM Energized Membrane",
    "Centum B-Type Energized EM Membrane": "Centum B-Type EM Energized Membrane",
    "'Pilfer' Energized Adaptive Nano Membrane I": "'Pilfer' Multispectrum Energized Membrane",
    "'Moonshine' Energized Thermal Membrane I": "'Moonshine' Thermal Energized Membrane",
    "'Mafia' Energized Kinetic Membrane I": "'Mafia' Kinetic Energized Membrane",
    "Khanid Navy Energized Adaptive Nano Membrane": "Khanid Navy Multispectrum Energized Membrane",
    "Khanid Navy Energized Kinetic Membrane": "Khanid Navy Kinetic Energized Membrane",
    "Khanid Navy Energized Explosive Membrane": "Khanid Navy Explosive Energized Membrane",
    "Khanid Navy Energized EM Membrane": "Khanid Navy EM Energized Membrane",
    "Khanid Navy Energized Thermal Membrane": "Khanid Navy Thermal Energized Membrane",
    "Large Compact Vorton projector": "Large Compact Vorton Projector",
    # Converted items
    "Experimental Energized Adaptive Nano Membrane I": "Compact Multispectrum Energized Membrane",
    "Limited Energized Adaptive Nano Membrane I": "Compact Multispectrum Energized Membrane",
    "Upgraded Energized Adaptive Nano Membrane I": "Compact Multispectrum Energized Membrane",
    "Experimental Energized Armor Layering Membrane I": "Compact Layered Energized Membrane",
    "Limited Energized Armor Layering Membrane I": "Compact Layered Energized Membrane",
    "Upgraded Energized Armor Layering Membrane I": "Compact Layered Energized Membrane",
    "Experimental Energized EM Membrane I": "Compact EM Energized Membrane",
    "Limited Energized EM Membrane I": "Compact EM Energized Membrane",
    "Upgraded Energized EM Membrane I": "Compact EM Energized Membrane",
    "Experimental Energized Explosive Membrane I": "Compact Explosive Energized Membrane",
    "Limited Energized Explosive Membrane I": "Compact Explosive Energized Membrane",
    "Upgraded Energized Explosive Membrane I": "Compact Explosive Energized Membrane",
    "Experimental Energized Kinetic Membrane I": "Compact Kinetic Energized Membrane",
    "Limited Energized Kinetic Membrane I": "Compact Kinetic Energized Membrane",
    "Upgraded Energized Kinetic Membrane I": "Compact Kinetic Energized Membrane",
    "Experimental Energized Thermal Membrane I": "Compact Thermal Energized Membrane",
    "Limited Energized Thermal Membrane I": "Compact Thermal Energized Membrane",
    "Upgraded Energized Thermal Membrane I": "Compact Thermal Energized Membrane",
}
