"""
Conversion pack for December 2015 release (no release name)
"""

CONVERSIONS = {
    # Renamed items
    "Medium 'Gremlin' Power Core Disruptor I": "Medium Gremlin Compact Energy Neutralizer",
    "Medium Coaxial Remote Armor Repairer": "Medium Coaxial Compact Remote Armor Repairer",
    "'Distributor' Tracking Disruptor I": "'Distributor' Guidance Disruptor I",
    "Type-D Power Core Modification: Shield Flux": "Type-D Restrained Shield Flux Coil",
    "Large Coaxial Remote Armor Repairer": "Large Coaxial Compact Remote Armor Repairer",
    "Heavy 'Knave' Energy Drain": "Heavy Knave Scoped Energy Nosferatu",
    "F-392 Baker Nunn Tracking Disruptor I": "Baker Nunn Enduring Tracking Disruptor I",
    "'Ditch' Medium Energy Neutralizer I": "Medium 'Ditch' Energy Neutralizer",
    "DDO Photometry Tracking Disruptor I": "DDO Scoped Tracking Disruptor I",
    "Small S95a Remote Shield Booster": "Small S95a Scoped Remote Shield Booster",
    "Large S95a Remote Shield Booster": "Large S95a Scoped Remote Shield Booster",
    "'Abandon' Tracking Disruptor I": "C-IR Compact Guidance Disruptor I",
    "500W Infectious Power System Malfunction": "Heavy Infectious Scoped Energy Neutralizer",
    "Heavy 'Gremlin' Power Core Disruptor I": "Heavy Gremlin Compact Energy Neutralizer",
    "Medium 'Solace' Remote Armor Repairer": "Medium Solace Scoped Remote Armor Repairer",
    "Small Coaxial Remote Armor Repairer": "Small Coaxial Compact Remote Armor Repairer",
    "Basic Shield Flux Coil": "'Basic' Shield Flux Coil",
    "Large I-ax Remote Armor Repairer": "Large I-ax Enduring Remote Armor Repairer",
    "Basic Shield Power Relay": "'Basic' Shield Power Relay",
    "Capital Coaxial Remote Armor Repairer": "CONCORD Capital Remote Armor Repairer",
    "Medium 'Ghoul' Energy Siphon I": "Medium Ghoul Compact Energy Nosferatu",
    "Medium S95a Remote Shield Booster": "Medium S95a Scoped Remote Shield Booster",
    "Mark I Generator Refitting: Shield Flux": "Mark I Compact Shield Flux Coil",
    "Large 'Solace' Remote Armor Repairer": "Large Solace Scoped Remote Armor Repairer",
    "Large Asymmetric Remote Shield Booster": "Large Asymmetric Enduring Remote Shield Booster",
    "M51 Iterative Shield Regenerator": "M51 Benefactor Compact Shield Recharger",
    "Small 'Knave' Energy Drain": "Small Knave Scoped Energy Nosferatu",
    "Medium Murky Remote Shield Booster": "Medium Murky Compact Remote Shield Booster",
    "Small Murky Remote Shield Booster": "Small Murky Compact Remote Shield Booster",
    "Capital Murky Remote Shield Booster": "CONCORD Capital Remote Shield Booster",
    "'Caltrop' Small Energy Neutralizer I": "Small 'Caltrop' Energy Neutralizer",
    "Small I-ax Remote Armor Repairer": "Small I-ax Enduring Remote Armor Repairer",
    "'Vrykolakas' Heavy Nosferatu I": "Heavy 'Vrykolakas' Energy Nosferatu",
    "Heavy 'Ghoul' Energy Siphon I": "Heavy Ghoul Compact Energy Nosferatu",
    "Small Asymmetric Remote Shield Booster": "Small Asymmetric Enduring Remote Shield Booster",
    "Small 'Gremlin' Power Core Disruptor I": "Small Gremlin Compact Energy Neutralizer",
    "'Strigoi' Medium Nosferatu I": "Medium 'Strigoi' Energy Nosferatu",
    "'Upir' Small Nosferatu I": "Small 'Upir' Energy Nosferatu",
    "Balmer Series Tracking Disruptor I": "Balmer Series Compact Tracking Disruptor I",
    "Small 'Solace' Remote Armor Repairer": "Small Solace Scoped Remote Armor Repairer",
    "'Moat' Heavy Energy Neutralizer I": "Heavy 'Moat' Energy Neutralizer",
    "Small 'Ghoul' Energy Siphon I": "Small Ghoul Compact Energy Nosferatu",
    "5W Infectious Power System Malfunction": "Small Infectious Scoped Energy Neutralizer",
    "50W Infectious Power System Malfunction": "Medium Infectious Scoped Energy Neutralizer",
    "Type-D Power Core Modification: Shield Power Relay": "Type-D Restrained Shield Power Relay",
    "Micro Remote Shield Booster I": "'Micro' Remote Shield Booster",
    "Medium I-ax Remote Armor Repairer": "Medium I-ax Enduring Remote Armor Repairer",
    "Medium Asymmetric Remote Shield Booster": "Medium Asymmetric Enduring Remote Shield Booster",
    "Large Murky Remote Shield Booster": "Large Murky Compact Remote Shield Booster",
    "Medium 'Knave' Energy Drain": "Medium Knave Scoped Energy Nosferatu",
    "Mark I Generator Refitting: Shield Power Relay": "Mark I Compact Shield Power Relay",

    # Converted items
    "Medium Unstable Power Fluctuator I": "Medium Gremlin Compact Energy Neutralizer",
    "'Brotherhood' Small Remote Armor Repairer": "'Beatnik' Small Remote Armor Repairer",
    "Beta Reactor Control: Shield Flux I": "Type-D Restrained Shield Flux Coil",
    "E500 Prototype Energy Vampire": "Heavy Knave Scoped Energy Nosferatu",
    "Heavy Rudimentary Energy Destabilizer I": "Heavy Infectious Scoped Energy Neutralizer",
    "Heavy Unstable Power Fluctuator I": "Heavy Gremlin Compact Energy Neutralizer",
    "Medium 'Arup' Remote Armor Repairer": "Medium Solace Scoped Remote Armor Repairer",
    "Alpha Reactor Shield Flux": "'Basic' Shield Flux Coil",
    "Marked Generator Refitting: Shield Flux": "'Basic' Shield Flux Coil",
    "Partial Power Plant Manager: Shield Flux": "'Basic' Shield Flux Coil",
    "Type-E Power Core Modification: Shield Flux": "'Basic' Shield Flux Coil",
    "Alpha Reactor Shield Power Relay": "'Basic' Shield Power Relay",
    "Marked Generator Refitting: Shield Power Relay": "'Basic' Shield Power Relay",
    "Partial Power Plant Manager: Shield Power Relay": "'Basic' Shield Power Relay",
    "Type-E Power Core Modification: Shield Power Relay": "'Basic' Shield Power Relay",
    "Small 'Arup' Remote Armor Repairer": "Small Solace Scoped Remote Armor Repairer",
    "Medium Diminishing Power System Drain I": "Medium Ghoul Compact Energy Nosferatu",
    "Local Power Plant Manager: Reaction Shield Flux I": "Mark I Compact Shield Flux Coil",
    "Large 'Arup' Remote Armor Repairer": "Large Solace Scoped Remote Armor Repairer",
    "Passive Barrier Compensator I": "M51 Benefactor Compact Shield Recharger",
    "'Benefactor' Ward Reconstructor": "M51 Benefactor Compact Shield Recharger",
    "Supplemental Screen Generator I": "M51 Benefactor Compact Shield Recharger",
    "E5 Prototype Energy Vampire": "Small Knave Scoped Energy Nosferatu",
    "Medium 'Atonement' Remote Shield Booster": "Medium Murky Compact Remote Shield Booster",
    "Small 'Atonement' Remote Shield Booster": "Small Murky Compact Remote Shield Booster",
    "Heavy Diminishing Power System Drain I": "Heavy Ghoul Compact Energy Nosferatu",
    "Small Unstable Power Fluctuator I": "Small Gremlin Compact Energy Neutralizer",
    "Local Power Plant Manager: Reaction Shield Power Relay I": "Mark I Compact Shield Power Relay",
    "'Pacifier' Large Remote Armor Repairer": "'Peace' Large Remote Armor Repairer",
    "Small Diminishing Power System Drain I": "Small Ghoul Compact Energy Nosferatu",
    "Small Rudimentary Energy Destabilizer I": "Small Infectious Scoped Energy Neutralizer",
    "Medium Rudimentary Energy Destabilizer I": "Medium Infectious Scoped Energy Neutralizer",
    "Beta Reactor Control: Shield Power Relay I": "Type-D Restrained Shield Power Relay",
    "Micro Asymmetric Remote Shield Booster": "'Micro' Remote Shield Booster",
    "Micro Murky Remote Shield Booster": "'Micro' Remote Shield Booster",
    "Micro 'Atonement' Remote Shield Booster": "'Micro' Remote Shield Booster",
    "Micro S95a Remote Shield Booster": "'Micro' Remote Shield Booster",
    "Large 'Atonement' Remote Shield Booster": "Large Murky Compact Remote Shield Booster",
    "E50 Prototype Energy Vampire": "Medium Knave Scoped Energy Nosferatu",
}
