"""
Conversion pack for December 2015 release (no release name)
"""

CONVERSIONS = {
    # Renamed items
    "Micro Remote Shield Booster I": "Micro' Remote Shield Booster",
    "Basic Shield Flux Coil": "'Basic' Shield Flux Coil",
    "Small Nosferatu I": "Small Energy Nosferatu I",
    "Basic Shield Power Relay": "'Basic' Shield Power Relay",
    "Capital Coaxial Remote Armor Repairer": "CONCORD Capital Remote Armor Repairer",
    "Capital Murky Remote Shield Booster": "CONCORD Capital Remote Shield Booster",
    "5W Infectious Power System Malfunction": "Small Infectious Scoped Energy Neutralizer",
    "Small 'Gremlin' Power Core Disruptor I": "Small Gremlin Compact Energy Neutralizer",
    "Small 'Knave' Energy Drain": "Small Knave Scoped Energy Nosferatu",
    "Small 'Ghoul' Energy Siphon I": "Small Ghoul Compact Energy Nosferatu",
    "F-392 Baker Nunn Tracking Disruptor I": "Baker Nunn Enduring Tracking Disruptor I",
    "Balmer Series Tracking Disruptor I": "Balmer Series Compact Tracking Disruptor I",
    "'Abandon' Tracking Disruptor I": "C-IR Compact Guidance Disruptor I",
    "DDO Photometry Tracking Disruptor I": "DDO Scoped Tracking Disruptor I",
    "M51 Iterative Shield Regenerator": "M51 Benefactor Compact Shield Recharger",
    "Type-D Power Core Modification: Shield Flux": "Type-D Restrained Shield Flux Coil",
    "Mark I Generator Refitting: Shield Flux": "Mark I Compact Shield Flux Coil",
    "Type-D Power Core Modification: Shield Power Relay": "Type-D Restrained Shield Power Relay",
    "Mark I Generator Refitting: Shield Power Relay": "Mark I Compact Shield Power Relay",
    "Small Murky Remote Shield Booster": "Small Murky Compact Remote Shield Booster",
    "Small Asymmetric Remote Shield Booster": "Small Asymmetric Enduring Remote Shield Booster",
    "Small S95a Remote Shield Booster": "Small S95a Scoped Remote Shield Booster",
    "Medium Murky Remote Shield Booster": "Medium Murky Compact Remote Shield Booster",
    "Medium Asymmetric Remote Shield Booster": "Medium Asymmetric Enduring Remote Shield Booster",
    "Medium S95a Remote Shield Booster": "Medium S95a Scoped Remote Shield Booster",
    "Large Murky Remote Shield Booster": "Large Murky Compact Remote Shield Booster",
    "Large Asymmetric Remote Shield Booster": "Large Asymmetric Enduring Remote Shield Booster",
    "Large S95a Remote Shield Booster": "Large S95a Scoped Remote Shield Booster",
    "Medium Nosferatu I": "Medium Energy Nosferatu I",
    "Medium Nosferatu II": "Medium Energy Nosferatu II",
    "Heavy Nosferatu I": "Heavy Energy Nosferatu I",
    "Heavy Nosferatu II": "Heavy Energy Nosferatu II",
    "Small Nosferatu II": "Small Energy Nosferatu II",
    "Dark Blood Small Nosferatu": "Dark Blood Small Energy Nosferatu",
    "True Sansha Small Nosferatu": "True Sansha Small Energy Nosferatu",
    "Dark Blood Heavy Nosferatu": "Dark Blood Heavy Energy Nosferatu",
    "True Sansha Heavy Nosferatu": "True Sansha Heavy Energy Nosferatu",
    "Dark Blood Medium Nosferatu": "Dark Blood Medium Energy Nosferatu",
    "True Sansha Medium Nosferatu": "True Sansha Medium Energy Nosferatu",
    "Brokara's Modified Heavy Nosferatu": "Brokara's Modified Heavy Energy Nosferatu",
    "Tairei's Modified Heavy Nosferatu": "Tairei's Modified Heavy Energy Nosferatu",
    "Selynne's Modified Heavy Nosferatu": "Selynne's Modified Heavy Energy Nosferatu",
    "Raysere's Modified Heavy Nosferatu": "Raysere's Modified Heavy Energy Nosferatu",
    "Vizan's Modified Heavy Nosferatu": "Vizan's Modified Heavy Energy Nosferatu",
    "Ahremen's Modified Heavy Nosferatu": "Ahremen's Modified Heavy Energy Nosferatu",
    "Chelm's Modified Heavy Nosferatu": "Chelm's Modified Heavy Energy Nosferatu",
    "Draclira's Modified Heavy Nosferatu": "Draclira's Modified Heavy Energy Nosferatu",
    "Ammatar Navy Small Nosferatu": "Ammatar Navy Small Energy Nosferatu",
    "Ammatar Navy Medium Nosferatu": "Ammatar Navy Medium Energy Nosferatu",
    "Ammatar Navy Heavy Nosferatu": "Ammatar Navy Heavy Energy Nosferatu",
    "Imperial Navy Small Nosferatu": "Imperial Navy Small Energy Nosferatu",
    "Imperial Navy Medium Nosferatu": "Imperial Navy Medium Energy Nosferatu",
    "Imperial Navy Heavy Nosferatu": "Imperial Navy Heavy Energy Nosferatu",
    "Small I-ax Remote Armor Repairer": "Small I-ax Enduring Remote Armor Repairer",
    "Small Coaxial Remote Armor Repairer": "Small Coaxial Compact Remote Armor Repairer",
    "Small 'Solace' Remote Armor Repairer": "Small Solace Scoped Remote Armor Repairer",
    "Medium I-ax Remote Armor Repairer": "Medium I-ax Enduring Remote Armor Repairer",
    "Medium Coaxial Remote Armor Repairer": "Medium Coaxial Compact Remote Armor Repairer",
    "Medium 'Solace' Remote Armor Repairer": "Medium Solace Scoped Remote Armor Repairer",
    "Large I-ax Remote Armor Repairer": "Large I-ax Enduring Remote Armor Repairer",
    "Large Coaxial Remote Armor Repairer": "Large Coaxial Compact Remote Armor Repairer",
    "Large 'Solace' Remote Armor Repairer": "Large Solace Scoped Remote Armor Repairer",
    "Medium 'Gremlin' Power Core Disruptor I": "Medium Gremlin Compact Energy Neutralizer",
    "50W Infectious Power System Malfunction": "Medium Infectious Scoped Energy Neutralizer",
    "Heavy 'Gremlin' Power Core Disruptor I": "Heavy Gremlin Compact Energy Neutralizer",
    "500W Infectious Power System Malfunction": "Heavy Infectious Scoped Energy Neutralizer",
    "Heavy 'Ghoul' Energy Siphon I": "Heavy Ghoul Compact Energy Nosferatu",
    "Heavy 'Knave' Energy Drain": "Heavy Knave Scoped Energy Nosferatu",
    "Medium 'Ghoul' Energy Siphon I": "Medium Ghoul Compact Energy Nosferatu",
    "Medium 'Knave' Energy Drain": "Medium Knave Scoped Energy Nosferatu",
    "Corpii C-Type Small Nosferatu": "Corpii C-Type Small Energy Nosferatu",
    "Corpii B-Type Small Nosferatu": "Corpii B-Type Small Energy Nosferatu",
    "Corpii A-Type Small Nosferatu": "Corpii A-Type Small Energy Nosferatu",
    "Corpum C-Type Medium Nosferatu": "Corpum C-Type Medium Energy Nosferatu",
    "Corpum B-Type Medium Nosferatu": "Corpum B-Type Medium Energy Nosferatu",
    "Corpum A-Type Medium Nosferatu": "Corpum A-Type Medium Energy Nosferatu",
    "Corpus C-Type Heavy Nosferatu": "Corpus C-Type Heavy Energy Nosferatu",
    "Corpus B-Type Heavy Nosferatu": "Corpus B-Type Heavy Energy Nosferatu",
    "Corpus A-Type Heavy Nosferatu": "Corpus A-Type Heavy Energy Nosferatu",
    "Corpus X-Type Heavy Nosferatu": "Corpus X-Type Heavy Energy Nosferatu",
    "'Distributor' Tracking Disruptor I": "'Distributor' Guidance Disruptor I",
    "'Caltrop' Small Energy Neutralizer I": "Small 'Caltrop' Energy Neutralizer",
    "'Ditch' Medium Energy Neutralizer I": "Medium 'Ditch' Energy Neutralizer",
    "'Moat' Heavy Energy Neutralizer I": "Heavy 'Moat' Energy Neutralizer",
    "'Upir' Small Nosferatu I": "Small 'Upir' Energy Nosferatu",
    "'Strigoi' Medium Nosferatu I": "Medium 'Strigoi' Energy Nosferatu",
    "'Vrykolakas' Heavy Nosferatu I": "Heavy 'Vrykolakas' Energy Nosferatu",