"""
Conversion pack for June 2020 release
"""

CONVERSIONS = {
    # Renamed items, extracted via diff file
    "Basic EM Ward Amplifier": "'Basic' EM Shield Amplifier",
    "Basic Thermal Dissipation Amplifier": "'Basic' Thermal Shield Amplifier",
    "Basic Kinetic Deflection Amplifier": "'Basic' Kinetic Shield Amplifier",
    "Basic Explosive Deflection Amplifier": "'Basic' Explosive Shield Amplifier",
    "EM Ward Amplifier I": "EM Shield Amplifier I",
    "Explosive Deflection Amplifier I": "Explosive Shield Amplifier I",
    "Explosive Deflection Amplifier II": "Explosive Shield Amplifier II",
    "Thermal Dissipation Amplifier I": "Thermal Shield Amplifier I",
    "Thermal Dissipation Amplifier II": "Thermal Shield Amplifier II",
    "Kinetic Deflection Amplifier I": "Kinetic Shield Amplifier I",
    "Kinetic Deflection Amplifier II": "Kinetic Shield Amplifier II",
    "EM Ward Amplifier II": "EM Shield Amplifier II",
    "Upgraded Explosive Deflection Amplifier I": "Compact Explosive Shield Amplifier",
    "Upgraded Thermal Dissipation Amplifier I": "Compact Thermal Shield Amplifier",
    "Upgraded EM Ward Amplifier I": "Compact EM Shield Amplifier",
    "Upgraded Kinetic Deflection Amplifier I": "Compact Kinetic Shield Amplifier",
    "Domination Explosive Deflection Amplifier": "Domination Explosive Shield Amplifier",
    "Dread Guristas Explosive Deflection Amplifier": "Dread Guristas Explosive Shield Amplifier",
    "Domination Thermal Dissipation Amplifier": "Domination Thermal Shield Amplifier",
    "Dread Guristas Thermal Dissipation Amplifier": "Dread Guristas Thermal Shield Amplifier",
    "Domination Kinetic Deflection Amplifier": "Domination Kinetic Shield Amplifier",
    "Dread Guristas Kinetic Deflection Amplifier": "Dread Guristas Kinetic Shield Amplifier",
    "Domination EM Ward Amplifier": "Domination EM Shield Amplifier",
    "Dread Guristas EM Ward Amplifier": "Dread Guristas EM Shield Amplifier",
    "Hakim's Modified Explosive Deflection Amplifier": "Hakim's Modified Explosive Shield Amplifier",
    "Tobias' Modified Explosive Deflection Amplifier": "Tobias' Modified Explosive Shield Amplifier",
    "Hakim's Modified Thermal Dissipation Amplifier": "Hakim's Modified Thermal Shield Amplifier",
    "Tobias' Modified Thermal Dissipation Amplifier": "Tobias' Modified Thermal Shield Amplifier",
    "Hakim's Modified Kinetic Deflection Amplifier": "Hakim's Modified Kinetic Shield Amplifier",
    "Tobias' Modified Kinetic Deflection Amplifier": "Tobias' Modified Kinetic Shield Amplifier",
    "Hakim's Modified EM Ward Amplifier": "Hakim's Modified EM Shield Amplifier",
    "Tobias' Modified EM Ward Amplifier": "Tobias' Modified EM Shield Amplifier",
    "Kaikka's Modified Explosive Deflection Amplifier": "Kaikka's Modified Explosive Shield Amplifier",
    "Thon's Modified Explosive Deflection Amplifier": "Thon's Modified Explosive Shield Amplifier",
    "Vepas' Modified Explosive Deflection Amplifier": "Vepas' Modified Explosive Shield Amplifier",
    "Estamel's Modified Explosive Deflection Amplifier": "Estamel's Modified Explosive Shield Amplifier",
    "Kaikka's Modified Thermal Dissipation Amplifier": "Kaikka's Modified Thermal Shield Amplifier",
    "Thon's Modified Thermal Dissipation Amplifier": "Thon's Modified Thermal Shield Amplifier",
    "Vepas' Modified Thermal Dissipation Amplifier": "Vepas' Modified Thermal Shield Amplifier",
    "Estamel's Modified Thermal Dissipation Amplifier": "Estamel's Modified Thermal Shield Amplifier",
    "Kaikka's Modified Kinetic Deflection Amplifier": "Kaikka's Modified Kinetic Shield Amplifier",
    "Thon's Modified Kinetic Deflection Amplifier": "Thon's Modified Kinetic Shield Amplifier",
    "Vepas' Modified Kinetic Deflection Amplifier": "Vepas' Modified Kinetic Shield Amplifier",
    "Estamel's Modified Kinetic Deflection Amplifier": "Estamel's Modified Kinetic Shield Amplifier",
    "Kaikka's Modified EM Ward Amplifier": "Kaikka's Modified EM Shield Amplifier",
    "Thon's Modified EM Ward Amplifier": "Thon's Modified EM Shield Amplifier",
    "Vepas' Modified EM Ward Amplifier": "Vepas' Modified EM Shield Amplifier",
    "Estamel's Modified EM Ward Amplifier": "Estamel's Modified EM Shield Amplifier",
    "Caldari Navy EM Ward Amplifier": "Caldari Navy EM Shield Amplifier",
    "Caldari Navy Kinetic Deflection Amplifier": "Caldari Navy Kinetic Shield Amplifier",
    "Caldari Navy Thermal Dissipation Amplifier": "Caldari Navy Thermal Shield Amplifier",
    "Caldari Navy Explosive Deflection Amplifier": "Caldari Navy Explosive Shield Amplifier",
    "Republic Fleet EM Ward Amplifier": "Republic Fleet EM Shield Amplifier",
    "Republic Fleet Kinetic Deflection Amplifier": "Republic Fleet Kinetic Shield Amplifier",
    "Republic Fleet Thermal Dissipation Amplifier": "Republic Fleet Thermal Shield Amplifier",
    "Republic Fleet Explosive Deflection Amplifier": "Republic Fleet Explosive Shield Amplifier",
    "Pithum C-Type Explosive Deflection Amplifier": "Pithum C-Type Explosive Shield Amplifier",
    "Pithum C-Type Thermal Dissipation Amplifier": "Pithum C-Type Thermal Shield Amplifier",
    "Pithum C-Type Kinetic Deflection Amplifier": "Pithum C-Type Kinetic Shield Amplifier",
    "Pithum C-Type EM Ward Amplifier": "Pithum C-Type EM Shield Amplifier",
    "Pithum B-Type Explosive Deflection Amplifier": "Pithum B-Type Explosive Shield Amplifier",
    "Pithum B-Type Thermal Dissipation Amplifier": "Pithum B-Type Thermal Shield Amplifier",
    "Pithum B-Type Kinetic Deflection Amplifier": "Pithum B-Type Kinetic Shield Amplifier",
    "Pithum B-Type EM Ward Amplifier": "Pithum B-Type EM Shield Amplifier",
    "Pithum A-Type Explosive Deflection Amplifier": "Pithum A-Type Explosive Shield Amplifier",
    "Pithum A-Type Thermal Dissipation Amplifier": "Pithum A-Type Thermal Shield Amplifier",
    "Pithum A-Type Kinetic Deflection Amplifier": "Pithum A-Type Kinetic Shield Amplifier",
    "Pithum A-Type EM Ward Amplifier": "Pithum A-Type EM Shield Amplifier",
    "Gistum C-Type Explosive Deflection Amplifier": "Gistum C-Type Explosive Shield Amplifier",
    "Gistum B-Type Explosive Deflection Amplifier": "Gistum B-Type Explosive Shield Amplifier",
    "Gistum C-Type Thermal Dissipation Amplifier": "Gistum C-Type Thermal Shield Amplifier",
    "Gistum B-Type Thermal Dissipation Amplifier": "Gistum B-Type Thermal Shield Amplifier",
    "Gistum C-Type Kinetic Deflection Amplifier": "Gistum C-Type Kinetic Shield Amplifier",
    "Gistum B-Type Kinetic Deflection Amplifier": "Gistum B-Type Kinetic Shield Amplifier",
    "Gistum C-Type EM Ward Amplifier": "Gistum C-Type EM Shield Amplifier",
    "Gistum B-Type EM Ward Amplifier": "Gistum B-Type EM Shield Amplifier",
    "Gistum A-Type Explosive Deflection Amplifier": "Gistum A-Type Explosive Shield Amplifier",
    "Gistum A-Type Thermal Dissipation Amplifier": "Gistum A-Type Thermal Shield Amplifier",
    "Gistum A-Type Kinetic Deflection Amplifier": "Gistum A-Type Kinetic Shield Amplifier",
    "Gistum A-Type EM Ward Amplifier": "Gistum A-Type EM Shield Amplifier",
    "'Whiskey' Explosive Deflection Amplifier": "'Whiskey' Explosive Shield Amplifier",
    "'High Noon' Thermal Dissipation Amplifier": "'High Noon' Thermal Shield Amplifier",
    "'Cactus' Modified Kinetic Deflection Amplifier": "'Cactus' Modified Kinetic Shield Amplifier",
    "'Prospector' EM Ward Amplifier": "'Prospector' EM Shield Amplifier",
    # Converted items
    "Supplemental EM Ward Amplifier": "'Basic' EM Shield Amplifier",
    "Supplemental Explosive Deflection Amplifier": "'Basic' Explosive Shield Amplifier",
    "Supplemental Kinetic Deflection Amplifier": "'Basic' Kinetic Shield Amplifier",
    "Supplemental Thermal Dissipation Amplifier": "'Basic' Thermal Shield Amplifier",
    "Dark Blood Tracking Disruptor": "'Investor' Tracking Disruptor I"
}
