CONVERSIONS = {
    # Renamed items
    "Gas Cloud Harvester I": "Gas Cloud Scoop I",
    "Gas Cloud Harvester II": "Gas Cloud Scoop II",
    "'Crop' Gas Cloud Harvester": "'Crop' Gas Cloud Scoop",
    "'Plow' Gas Cloud Harvester": "'Plow' Gas Cloud Scoop",
    "Syndicate Gas Cloud Harvester": "Syndicate Gas Cloud Scoop",
    "Mercoxit Mining Crystal I": "Mercoxit Asteroid Mining Crystal Type A I",
    "Mercoxit Mining Crystal II": "Mercoxit Asteroid Mining Crystal Type A II",
    "Ubiquitous Moon Ore Mining Crystal I": "Ubiquitous Moon Mining Crystal Type A I",
    "Ubiquitous Moon Ore Mining Crystal II": "Ubiquitous Moon Mining Crystal Type A II",
    "Common Moon Ore Mining Crystal I": "Common Moon Mining Crystal Type A I",
    "Common Moon Ore Mining Crystal II": "Common Moon Mining Crystal Type A II",
    "Uncommon Moon Ore Mining Crystal I": "Uncommon Moon Mining Crystal Type A I",
    "Uncommon Moon Ore Mining Crystal II": "Uncommon Moon Mining Crystal Type A II",
    "Rare Moon Ore Mining Crystal I": "Rare Moon Mining Crystal Type A I",
    "Rare Moon Ore Mining Crystal II": "Rare Moon Mining Crystal Type A II",
    "Exceptional Moon Ore Mining Crystal I": "Exceptional Moon Mining Crystal Type A I",
    "Exceptional Moon Ore Mining Crystal II": "Exceptional Moon Mining Crystal Type A II",
    "Industrial Core I": "Capital Industrial Core I",
    "Industrial Core II": "Capital Industrial Core II",
    # Converted items
    "Veldspar Mining Crystal I": "Simple Asteroid Mining Crystal Type A I",
    "Scordite Mining Crystal I": "Simple Asteroid Mining Crystal Type A I",
    "Pyroxeres Mining Crystal I": "Simple Asteroid Mining Crystal Type A I",
    "Plagioclase Mining Crystal I": "Simple Asteroid Mining Crystal Type A I",
    "Veldspar Mining Crystal II": "Simple Asteroid Mining Crystal Type A II",
    "Scordite Mining Crystal II": "Simple Asteroid Mining Crystal Type A II",
    "Pyroxeres Mining Crystal II": "Simple Asteroid Mining Crystal Type A II",
    "Plagioclase Mining Crystal II": "Simple Asteroid Mining Crystal Type A II",
    "Omber Mining Crystal I": "Coherent Asteroid Mining Crystal Type A I",
    "Kernite Mining Crystal I": "Coherent Asteroid Mining Crystal Type A I",
    "Jaspet Mining Crystal I": "Coherent Asteroid Mining Crystal Type A I",
    "Hemorphite Mining Crystal I": "Coherent Asteroid Mining Crystal Type A I",
    "Hedbergite Mining Crystal I": "Coherent Asteroid Mining Crystal Type A I",
    "Omber Mining Crystal II": "Coherent Asteroid Mining Crystal Type A II",
    "Jaspet Mining Crystal II": "Coherent Asteroid Mining Crystal Type A II",
    "Kernite Mining Crystal II": "Coherent Asteroid Mining Crystal Type A II",
    "Hedbergite Mining Crystal II": "Coherent Asteroid Mining Crystal Type A II",
    "Hemorphite Mining Crystal II": "Coherent Asteroid Mining Crystal Type A II",
    "Gneiss Mining Crystal I": "Variegated Asteroid Mining Crystal Type A I",
    "Dark Ochre Mining Crystal I": "Variegated Asteroid Mining Crystal Type A I",
    "Crokite Mining Crystal I": "Variegated Asteroid Mining Crystal Type A I",
    "Gneiss Mining Crystal II": "Variegated Asteroid Mining Crystal Type A II",
    "Dark Ochre Mining Crystal II": "Variegated Asteroid Mining Crystal Type A II",
    "Crokite Mining Crystal II": "Variegated Asteroid Mining Crystal Type A II",
    "Bistot Mining Crystal I": "Complex Asteroid Mining Crystal Type A I",
    "Arkonor Mining Crystal I": "Complex Asteroid Mining Crystal Type A I",
    "Spodumain Mining Crystal I": "Complex Asteroid Mining Crystal Type A I",
    "Bistot Mining Crystal II": "Complex Asteroid Mining Crystal Type A II",
    "Arkonor Mining Crystal II": "Complex Asteroid Mining Crystal Type A II",
    "Spodumain Mining Crystal II": "Complex Asteroid Mining Crystal Type A II",
}
