"""
Conversion pack for Citadel release
"""

CONVERSIONS = {
    # Renamed items
    "Capital Inefficient Armor Repair Unit": "CONCORD Capital Armor Repairer",
    "Capital Neutron Saturation Injector I": "CONCORD Capital Shield Booster",
    "Limited Mega Ion Siege Blaster I": "CONCORD Ion Siege Blaster",
    "Dual 1000mm 'Scout' Accelerator Cannon": "CONCORD Dual 1000mm Railgun",
    "Dual Modal Giga Pulse Laser I": "CONCORD Dual Giga Pulse Laser",
    "Dual Giga Modal Laser I": "CONCORD Dual Giga Beam Laser",
    "'Limos' XL Cruise Launcher I": "CONCORD XL Cruise Missile Launcher",
    "Shock 'Limos' XL Torpedo Bay I": "CONCORD XL Torpedo Launcher",
    "Quad 3500mm Gallium Cannon": "CONCORD Quad 3500mm Siege Artillery",
    "6x2500mm Heavy Gallium Repeating Cannon": "CONCORD Hexa 2500mm Repeating Cannon",
    "Capital Murky Remote Capacitor Transmitter": "CONCORD Capital Remote Capacitor Transmitter",
    "Ion Siege Blaster Cannon I": "Ion Siege Blaster I",
    "6x2500mm Repeating Cannon I": "Hexa 2500mm Repeating Cannon I",
    "Templar": "Templar I",
    "Dragonfly": "Dragonfly I",
    "Firbolg": "Firbolg I",
    "Einherji": "Einherji I",
    "Gjallarhorn": "'Gjallarhorn' Explosive Doomsday",
    "Drone Control Unit I": "Fighter Support Unit I",
    "Judgement": "'Judgment' Electromagnetic Doomsday",
    "Oblivion": "'Oblivion' Kinetic Doomsday",
    "Aurora Ominae": "'Aurora Ominae' Thermal Doomsday",
    "Advanced Drone Interfacing": "Fighter Hangar Management",
    "Remote ECM Burst I": "ECM Jammer Burst Projector",
    "Projected Electronic Counter Measures": "Burst Projector Operation",
    "Cyclops": "Cyclops I",
    "Fighter Bombers": "Heavy Fighters",
    "Malleus": "Malleus I",
    "Tyrfing": "Tyrfing I",
    "Mantis": "Mantis I",
    "XL Cruise Launcher I": "XL Cruise Missile Launcher I",
    "Armor Resistance Phasing": "Resistance Phasing",
    "Unit D-34343's Modified Drone Control Unit": "Unit D-34343's Modified Fighter Support Unit",
    "Unit F-435454's Modified Drone Control Unit": "Unit F-435454's Modified Fighter Support Unit",
    "Unit P-343554's Modified Drone Control Unit": "Unit P-343554's Modified Fighter Support Unit",
    "Unit W-634's Modified Drone Control Unit": "Unit W-634's Modified Fighter Support Unit",
    "Heavy Shadow Serpentis Stasis Grappler": "Shadow Serpentis Heavy Stasis Grappler",
    "Heavy Domination Stasis Grappler": "Domination Heavy Stasis Grappler",
}
