"""
Conversion pack for July 2020 release
"""

CONVERSIONS = {
    # Renamed items, extracted via diff file
    "Basic EM Plating": "'Basic' EM Coating",
    "EM Plating I": "EM Coating I",
    "EM Plating II": "EM Coating II",
    "Basic Explosive Plating": "'Basic' Explosive Coating",
    "Explosive Plating I": "Explosive Coating I",
    "Explosive Plating II": "Explosive Coating II",
    "Basic Layered Plating": "'Basic' Layered Coating",
    "Layered Plating I": "Layered Coating I",
    "Layered Plating II": "Layered Coating II",
    "Basic Kinetic Plating": "'Basic' Kinetic Coating",
    "Kinetic Plating I": "Kinetic Coating I",
    "Kinetic Plating II": "Kinetic Coating II",
    "Basic Thermal Plating": "'Basic' Thermal Coating",
    "Thermal Plating I": "Thermal Coating I",
    "Thermal Plating II": "Thermal Coating II",
    "Basic Adaptive Nano Plating": "'Basic' Multispectrum Coating",
    "Adaptive Nano Plating I": "Multispectrum Coating I",
    "Adaptive Nano Plating II": "Multispectrum Coating II",
    "Domination Adaptive Nano Plating": "Domination Multispectrum Coating",
    "True Sansha Adaptive Nano Plating": "True Sansha Multispectrum Coating",
    "Dark Blood Adaptive Nano Plating": "Dark Blood Multispectrum Coating",
    "Domination Kinetic Plating": "Domination Kinetic Coating",
    "True Sansha Kinetic Plating": "True Sansha Kinetic Coating",
    "Dark Blood Kinetic Plating": "Dark Blood Kinetic Coating",
    "Domination Explosive Plating": "Domination Explosive Coating",
    "True Sansha Explosive Plating": "True Sansha Explosive Coating",
    "Dark Blood Explosive Plating": "Dark Blood Explosive Coating",
    "Domination EM Plating": "Domination EM Coating",
    "True Sansha EM Plating": "True Sansha EM Coating",
    "Dark Blood EM Plating": "Dark Blood EM Coating",
    "Domination Thermal Plating": "Domination Thermal Coating",
    "True Sansha Thermal Plating": "True Sansha Thermal Coating",
    "Dark Blood Thermal Plating": "Dark Blood Thermal Coating",
    "Shadow Serpentis Adaptive Nano Plating": "Shadow Serpentis Multispectrum Coating",
    "Shadow Serpentis Kinetic Plating": "Shadow Serpentis Kinetic Coating",
    "Shadow Serpentis Explosive Plating": "Shadow Serpentis Explosive Coating",
    "Shadow Serpentis EM Plating": "Shadow Serpentis EM Coating",
    "Shadow Serpentis Thermal Plating": "Shadow Serpentis Thermal Coating",
    "Mizuro's Modified Adaptive Nano Plating": "Mizuro's Modified Multispectrum Coating",
    "Gotan's Modified Adaptive Nano Plating": "Gotan's Modified Multispectrum Coating",
    "Mizuro's Modified Kinetic Plating": "Mizuro's Modified Kinetic Coating",
    "Gotan's Modified Kinetic Plating": "Gotan's Modified Kinetic Coating",
    "Mizuro's Modified Explosive Plating": "Mizuro's Modified Explosive Coating",
    "Gotan's Modified Explosive Plating": "Gotan's Modified Explosive Coating",
    "Mizuro's Modified EM Plating": "Mizuro's Modified EM Coating",
    "Gotan's Modified EM Plating": "Gotan's Modified EM Coating",
    "Mizuro's Modified Thermal Plating": "Mizuro's Modified Thermal Coating",
    "Gotan's Modified Thermal Plating": "Gotan's Modified Thermal Coating",
    "Brokara's Modified Adaptive Nano Plating": "Brokara's Modified Multispectrum Coating",
    "Tairei's Modified Adaptive Nano Plating": "Tairei's Modified Multispectrum Coating",
    "Selynne's Modified Adaptive Nano Plating": "Selynne's Modified Multispectrum Coating",
    "Raysere's Modified Adaptive Nano Plating": "Raysere's Modified Multispectrum Coating",
    "Vizan's Modified Adaptive Nano Plating": "Vizan's Modified Multispectrum Coating",
    "Ahremen's Modified Adaptive Nano Plating": "Ahremen's Modified Multispectrum Coating",
    "Chelm's Modified Adaptive Nano Plating": "Chelm's Modified Multispectrum Coating",
    "Draclira's Modified Adaptive Nano Plating": "Draclira's Modified Multispectrum Coating",
    "Brokara's Modified Kinetic Plating": "Brokara's Modified Kinetic Coating",
    "Tairei's Modified Kinetic Plating": "Tairei's Modified Kinetic Coating",
    "Selynne's Modified Kinetic Plating": "Selynne's Modified Kinetic Coating",
    "Raysere's Modified Kinetic Plating": "Raysere's Modified Kinetic Coating",
    "Vizan's Modified Kinetic Plating": "Vizan's Modified Kinetic Coating",
    "Ahremen's Modified Kinetic Plating": "Ahremen's Modified Kinetic Coating",
    "Chelm's Modified Kinetic Plating": "Chelm's Modified Kinetic Coating",
    "Draclira's Modified Kinetic Plating": "Draclira's Modified Kinetic Coating",
    "Brokara's Modified Explosive Plating": "Brokara's Modified Explosive Coating",
    "Tairei's Modified Explosive Plating": "Tairei's Modified Explosive Coating",
    "Selynne's Modified Explosive Plating": "Selynne's Modified Explosive Coating",
    "Raysere's Modified Explosive Plating": "Raysere's Modified Explosive Coating",
    "Vizan's Modified Explosive Plating": "Vizan's Modified Explosive Coating",
    "Ahremen's Modified Explosive Plating": "Ahremen's Modified Explosive Coating",
    "Chelm's Modified Explosive Plating": "Chelm's Modified Explosive Coating",
    "Draclira's Modified Explosive Plating": "Draclira's Modified Explosive Coating",
    "Brokara's Modified EM Plating": "Brokara's Modified EM Coating",
    "Tairei's Modified EM Plating": "Tairei's Modified EM Coating",
    "Selynne's Modified EM Plating": "Selynne's Modified EM Coating",
    "Raysere's Modified EM Plating": "Raysere's Modified EM Coating",
    "Vizan's Modified EM Plating": "Vizan's Modified EM Coating",
    "Ahremen's Modified EM Plating": "Ahremen's Modified EM Coating",
    "Chelm's Modified EM Plating": "Chelm's Modified EM Coating",
    "Draclira's Modified EM Plating": "Draclira's Modified EM Coating",
    "Brokara's Modified Thermal Plating": "Brokara's Modified Thermal Coating",
    "Tairei's Modified Thermal Plating": "Tairei's Modified Thermal Coating",
    "Selynne's Modified Thermal Plating": "Selynne's Modified Thermal Coating",
    "Raysere's Modified Thermal Plating": "Raysere's Modified Thermal Coating",
    "Vizan's Modified Thermal Plating": "Vizan's Modified Thermal Coating",
    "Ahremen's Modified Thermal Plating": "Ahremen's Modified Thermal Coating",
    "Chelm's Modified Thermal Plating": "Chelm's Modified Thermal Coating",
    "Draclira's Modified Thermal Plating": "Draclira's Modified Thermal Coating",
    "Brynn's Modified Adaptive Nano Plating": "Brynn's Modified Multispectrum Coating",
    "Tuvan's Modified Adaptive Nano Plating": "Tuvan's Modified Multispectrum Coating",
    "Setele's Modified Adaptive Nano Plating": "Setele's Modified Multispectrum Coating",
    "Cormack's Modified Adaptive Nano Plating": "Cormack's Modified Multispectrum Coating",
    "Brynn's Modified Thermal Plating": "Brynn's Modified Thermal Coating",
    "Tuvan's Modified Thermal Plating": "Tuvan's Modified Thermal Coating",
    "Setele's Modified Thermal Plating": "Setele's Modified Thermal Coating",
    "Cormack's Modified Thermal Plating": "Cormack's Modified Thermal Coating",
    "Brynn's Modified EM Plating": "Brynn's Modified EM Coating",
    "Tuvan's Modified EM Plating": "Tuvan's Modified EM Coating",
    "Setele's Modified EM Plating": "Setele's Modified EM Coating",
    "Cormack's Modified EM Plating": "Cormack's Modified EM Coating",
    "Brynn's Modified Explosive Plating": "Brynn's Modified Explosive Coating",
    "Tuvan's Modified Explosive Plating": "Tuvan's Modified Explosive Coating",
    "Setele's Modified Explosive Plating": "Setele's Modified Explosive Coating",
    "Cormack's Modified Explosive Plating": "Cormack's Modified Explosive Coating",
    "Brynn's Modified Kinetic Plating": "Brynn's Modified Kinetic Coating",
    "Tuvan's Modified Kinetic Plating": "Tuvan's Modified Kinetic Coating",
    "Setele's Modified Kinetic Plating": "Setele's Modified Kinetic Coating",
    "Cormack's Modified Kinetic Plating": "Cormack's Modified Kinetic Coating",
    "Imperial Navy Thermal Plating": "Imperial Navy Thermal Coating",
    "Imperial Navy EM Plating": "Imperial Navy EM Coating",
    "Imperial Navy Explosive Plating": "Imperial Navy Explosive Coating",
    "Imperial Navy Kinetic Plating": "Imperial Navy Kinetic Coating",
    "Imperial Navy Adaptive Nano Plating": "Imperial Navy Multispectrum Coating",
    "Republic Fleet Thermal Plating": "Republic Fleet Thermal Coating",
    "Republic Fleet EM Plating": "Republic Fleet EM Coating",
    "Republic Fleet Explosive Plating": "Republic Fleet Explosive Coating",
    "Republic Fleet Kinetic Plating": "Republic Fleet Kinetic Coating",
    "Republic Fleet Adaptive Nano Plating": "Republic Fleet Multispectrum Coating",
    "Upgraded Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "Upgraded Kinetic Plating I": "Upgraded Kinetic Coating I",
    "Upgraded Explosive Plating I": "Upgraded Explosive Coating I",
    "Upgraded EM Plating I": "Upgraded EM Coating I",
    "Upgraded Thermal Plating I": "Upgraded Thermal Coating I",
    "Upgraded Layered Plating I": "Upgraded Layered Coating I",
    "Ammatar Navy Kinetic Plating": "Ammatar Navy Kinetic Coating",
    "Ammatar Navy Adaptive Nano Plating": "Ammatar Navy Multispectrum Coating",
    "Ammatar Navy Explosive Plating": "Ammatar Navy Explosive Coating",
    "Ammatar Navy EM Plating": "Ammatar Navy EM Coating",
    "Federation Navy Adaptive Nano Plating": "Federation Navy Multispectrum Coating",
    "Federation Navy Kinetic Plating": "Federation Navy Kinetic Coating",
    "Federation Navy Explosive Plating": "Federation Navy Explosive Coating",
    "Federation Navy EM Plating": "Federation Navy EM Coating",
    "Federation Navy Thermal Plating": "Federation Navy Thermal Coating",
    "Corpii C-Type Adaptive Nano Plating": "Corpii C-Type Multispectrum Coating",
    "Centii C-Type Adaptive Nano Plating": "Centii C-Type Multispectrum Coating",
    "Corpii B-Type Adaptive Nano Plating": "Corpii B-Type Multispectrum Coating",
    "Centii B-Type Adaptive Nano Plating": "Centii B-Type Multispectrum Coating",
    "Corpii A-Type Adaptive Nano Plating": "Corpii A-Type Multispectrum Coating",
    "Centii A-Type Adaptive Nano Plating": "Centii A-Type Multispectrum Coating",
    "Corpii C-Type Kinetic Plating": "Corpii C-Type Kinetic Coating",
    "Centii C-Type Kinetic Plating": "Centii C-Type Kinetic Coating",
    "Corpii C-Type Explosive Plating": "Corpii C-Type Explosive Coating",
    "Centii C-Type Explosive Plating": "Centii C-Type Explosive Coating",
    "Corpii C-Type EM Plating": "Corpii C-Type EM Coating",
    "Centii C-Type EM Plating": "Centii C-Type EM Coating",
    "Corpii C-Type Thermal Plating": "Corpii C-Type Thermal Coating",
    "Centii C-Type Thermal Plating": "Centii C-Type Thermal Coating",
    "Corpii B-Type Thermal Plating": "Corpii B-Type Thermal Coating",
    "Centii B-Type Thermal Plating": "Centii B-Type Thermal Coating",
    "Corpii B-Type Kinetic Plating": "Corpii B-Type Kinetic Coating",
    "Centii B-Type Kinetic Plating": "Centii B-Type Kinetic Coating",
    "Corpii B-Type Explosive Plating": "Corpii B-Type Explosive Coating",
    "Centii B-Type Explosive Plating": "Centii B-Type Explosive Coating",
    "Corpii B-Type EM Plating": "Corpii B-Type EM Coating",
    "Centii B-Type EM Plating": "Centii B-Type EM Coating",
    "Corpii A-Type Kinetic Plating": "Corpii A-Type Kinetic Coating",
    "Centii A-Type Kinetic Plating": "Centii A-Type Kinetic Coating",
    "Corpii A-Type Explosive Plating": "Corpii A-Type Explosive Coating",
    "Centii A-Type Explosive Plating": "Centii A-Type Explosive Coating",
    "Corpii A-Type EM Plating": "Corpii A-Type EM Coating",
    "Centii A-Type EM Plating": "Centii A-Type EM Coating",
    "Corpii A-Type Thermal Plating": "Corpii A-Type Thermal Coating",
    "Centii A-Type Thermal Plating": "Centii A-Type Thermal Coating",
    "Coreli C-Type Adaptive Nano Plating": "Coreli C-Type Multispectrum Coating",
    "Coreli C-Type Kinetic Plating": "Coreli C-Type Kinetic Coating",
    "Coreli C-Type Explosive Plating": "Coreli C-Type Explosive Coating",
    "Coreli C-Type EM Plating": "Coreli C-Type EM Coating",
    "Coreli C-Type Thermal Plating": "Coreli C-Type Thermal Coating",
    "Coreli B-Type Adaptive Nano Plating": "Coreli B-Type Multispectrum Coating",
    "Coreli B-Type Kinetic Plating": "Coreli B-Type Kinetic Coating",
    "Coreli B-Type Explosive Plating": "Coreli B-Type Explosive Coating",
    "Coreli B-Type EM Plating": "Coreli B-Type EM Coating",
    "Coreli B-Type Thermal Plating": "Coreli B-Type Thermal Coating",
    "Coreli A-Type Adaptive Nano Plating": "Coreli A-Type Multispectrum Coating",
    "Coreli A-Type Kinetic Plating": "Coreli A-Type Kinetic Coating",
    "Coreli A-Type Explosive Plating": "Coreli A-Type Explosive Coating",
    "Coreli A-Type EM Plating": "Coreli A-Type EM Coating",
    "Coreli A-Type Thermal Plating": "Coreli A-Type Thermal Coating",
    "Khanid Navy Adaptive Nano Plating": "Khanid Navy Multispectrum Coating",
    "Khanid Navy Kinetic Plating": "Khanid Navy Kinetic Coating",
    "Khanid Navy Explosive Plating": "Khanid Navy Explosive Coating",
    "Khanid Navy EM Plating": "Khanid Navy EM Coating",
    "Khanid Navy Thermal Plating": "Khanid Navy Thermal Coating",
    "Ammatar Navy Thermal Plating": "Ammatar Navy Thermal Coating",
    "Low-Grade Mimesis Alpha": "Low-grade Mimesis Alpha",
    "Low-Grade Mimesis Beta": "Low-grade Mimesis Beta",
    "Low-Grade Mimesis Gamma": "Low-grade Mimesis Gamma",
    "Low-Grade Mimesis Delta": "Low-grade Mimesis Delta",
    "Low-Grade Mimesis Epsilon": "Low-grade Mimesis Epsilon",
    "Low-Grade Mimesis Omega": "Low-grade Mimesis Omega",
    "Mid-Grade Mimesis Alpha": "Mid-grade Mimesis Alpha",
    "Mid-Grade Mimesis Beta": "Mid-grade Mimesis Beta",
    "Mid-Grade Mimesis Gamma": "Mid-grade Mimesis Gamma",
    "Mid-Grade Mimesis Delta": "Mid-grade Mimesis Delta",
    "Mid-Grade Mimesis Epsilon": "Mid-grade Mimesis Epsilon",
    "Mid-Grade Mimesis Omega": "Mid-grade Mimesis Omega",
    "High-Grade Mimesis Alpha": "High-grade Mimesis Alpha",
    "High-Grade Mimesis Beta": "High-grade Mimesis Beta",
    "High-Grade Mimesis Delta": "High-grade Mimesis Delta",
    "High-Grade Mimesis Epsilon": "High-grade Mimesis Epsilon",
    "High-Grade Mimesis Gamma": "High-grade Mimesis Gamma",
    "High-Grade Mimesis Omega": "High-grade Mimesis Omega",
    # Converted items
    "Limited Layered Plating I": "Upgraded Layered Coating I",
    "'Scarab' Layered Plating I": "Upgraded Layered Coating I",
    "'Grail' Layered Plating I": "Upgraded Layered Coating I",
    "Limited Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "'Collateral' Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "'Refuge' Adaptive Nano Plating I": "Upgraded Multispectrum Coating I",
    "Limited EM Plating I": "Upgraded EM Coating I",
    "'Contour' EM Plating I": "Upgraded EM Coating I",
    "'Spiegel' EM Plating I": "Upgraded EM Coating I",
    "Limited Explosive Plating I": "Upgraded Explosive Coating I",
    "Experimental Explosive Plating I": "Upgraded Explosive Coating I",
    "'Aegis' Explosive Plating I": "Upgraded Explosive Coating I",
    "Limited Kinetic Plating I": "Upgraded Kinetic Coating I",
    "Experimental Kinetic Plating I": "Upgraded Kinetic Coating I",
    "'Element' Kinetic Plating I": "Upgraded Kinetic Coating I",
    "Limited Thermal Plating I": "Upgraded Thermal Coating I",
    "Experimental Thermal Plating I": "Upgraded Thermal Coating I",
    "Prototype Thermal Plating I": "Upgraded Thermal Coating I"
}
