CONVERSIONS = {
    "Survey Scanner I": "Mining Survey Chipset I",
    "Survey Scanner II": "Mining Survey Chipset II",
    "ML-3 Scoped Survey Scanner": "ML-3 Compact Mining Survey Chipset",
    "Gatling Afocal Maser I": "Gatling Afocal Laser I",
    "Dual Afocal Pulse Maser I": "Dual Afocal Pulse Laser I",
    "Dual Afocal Light Maser I": "Dual Afocal Light Laser I",
    "Small Focused Afocal Pulse Maser I": "Small Focused Afocal Pulse Laser I",
    "Small Focused Afocal Maser I": "Small Focused Afocal Laser I",
    "Quad Afocal Light Maser I": "Quad Afocal Light Laser I",
    "Focused Afocal Pulse Maser I": "Focused Afocal Pulse Laser I",
    "Focused Afocal Medium Maser I": "Focused Afocal Medium Laser I",
    "Heavy Afocal Pulse Maser I": "Heavy Afocal Pulse Laser I",
    "Heavy Afocal Maser I": "Heavy Afocal Laser I",
    "Dual Heavy Afocal Pulse Maser I": "Dual Heavy Afocal Pulse Laser I",
    "Dual Afocal Heavy Maser I": "Dual Afocal Heavy Laser I",
    "Mega Afocal Pulse Maser I": "Mega Afocal Pulse Laser I",
    "Mega Afocal Maser I": "Mega Afocal Laser I",
    "Tachyon Afocal Maser I": "Tachyon Afocal Laser I",
}
