"""
Conversion pack for January 2016 (YC118.1) release
"""

CONVERSIONS = {
    # Renamed items

    # Converted items
    "Muon Coil Bolt Array I": "Crosslink Compact Ballistic Control System",
    "Multiphasic Bolt Array I": "Crosslink Compact Ballistic Control System",
    "'Pandemonium' Ballistic Enhancement": "Crosslink Compact Ballistic Control System",
    "Piercing ECCM Emitter I": "Coadjunct Scoped Remote Sensor Booster",
    "1Z-3 Subversive ECM Eruption": "Cetus Scoped Burst Jammer",
    "ECCM - Radar I": "Sensor Booster I",
    "ECCM - Ladar I": "Sensor Booster I",
    "ECCM - Magnetometric I": "Sensor Booster I",
    "ECCM - Gravimetric I": "Sensor Booster I",
    "ECCM - Omni I": "Sensor Booster I",
    "Beta-Nought Tracking Mode": "'Basic' Tracking Enhancer",
    "Azimuth Descalloping Tracking Enhancer": "'Basic' Tracking Enhancer",
    "F-AQ Delay-Line Scan Tracking Subroutines": "'Basic' Tracking Enhancer",
    "Beam Parallax Tracking Program": "'Basic' Tracking Enhancer",
    "GLFF Containment Field": "'Basic' Damage Control",
    "Interior Force Field Array": "'Basic' Damage Control",
    "F84 Local Damage System": "'Basic' Damage Control",
    "Systematic Damage Control": "'Basic' Damage Control",
    "'Boss' Remote Sensor Booster": "'Bootleg' Remote Sensor Booster",
    "'Entrepreneur' Remote Sensor Booster": "'Bootleg' Remote Sensor Booster",
    "Fleeting Progressive Warp Scrambler I": "Faint Epsilon Scoped Warp Scrambler",
    "ECCM Projector I": "Remote Sensor Booster I",
    "Sigma-Nought Tracking Mode I": "Fourier Compact Tracking Enhancer",
    "Auto-Gain Control Tracking Enhancer I": "Fourier Compact Tracking Enhancer",
    "F-aQ Phase Code Tracking Subroutines": "Fourier Compact Tracking Enhancer",
    "Monophonic Stabilization Actuator I": "'Kindred' Gyrostabilizer",
    "Initiated Ion Field ECM I": "Hypnos Scoped Magnetometric ECM",
    "Insulated Stabilizer Array": "'Basic' Magnetic Field Stabilizer",
    "Linear Flux Stabilizer": "'Basic' Magnetic Field Stabilizer",
    "Gauss Field Balancer": "'Basic' Magnetic Field Stabilizer",
    "Magnetic Vortex Stabilizer": "'Basic' Magnetic Field Stabilizer",
    "'Capitalist' Magnetic Field Stabilizer I": "'Monopoly' Magnetic Field Stabilizer",
    "Emergency Damage Control I": "IFFA Compact Damage Control",
    "F85 Peripheral Damage System I": "IFFA Compact Damage Control",
    "Pseudoelectron Containment Field I": "IFFA Compact Damage Control",
    "Micro Ld-Acid Capacitor Battery I": "'Micro' Cap Battery",
    "Micro Ohm Capacitor Reserve I": "'Micro' Cap Battery",
    "Micro F-4a Ld-Sulfate Capacitor Charge Unit": "'Micro' Cap Battery",
    "Micro Peroxide Capacitor Power Cell": "'Micro' Cap Battery",
    "Micro Capacitor Battery II": "'Micro' Cap Battery",
    "Lateral Gyrostabilizer": "'Basic' Gyrostabilizer",
    "F-M2 Weapon Inertial Suspensor": "'Basic' Gyrostabilizer",
    "Hydraulic Stabilization Actuator": "'Basic' Gyrostabilizer",
    "Stabilized Weapon Mounts": "'Basic' Gyrostabilizer",
    "'Hypnos' Multispectral ECM I": "Compulsive Scoped Multispectral ECM",
    "Fleeting Warp Disruptor I": "Faint Scoped Warp Disruptor",
    "'Mangonel' Heat Sink I": "'Trebuchet' Heat Sink I",
    "Heat Exhaust System": "'Basic' Heat Sink",
    "C3S Convection Thermal Radiator": "'Basic' Heat Sink",
    "'Boreas' Coolant System": "'Basic' Heat Sink",
    "Stamped Heat Sink": "'Basic' Heat Sink",
    "Extra Radar ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Extra Ladar ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Extra Gravimetric ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Extra Magnetometric ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Gravimetric Positional ECCM Sensor System I": "F-90 Compact Sensor Booster",
    "Radar Positional ECCM Sensor System I": "F-90 Compact Sensor Booster",
    "Omni Positional ECCM Sensor System I": "F-90 Compact Sensor Booster",
    "Ladar Positional ECCM Sensor System I": "F-90 Compact Sensor Booster",
    "Magnetometric Positional ECCM Sensor System I": "F-90 Compact Sensor Booster",
    "Conjunctive Radar ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Conjunctive Ladar ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Conjunctive Gravimetric ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Conjunctive Magnetometric ECCM Scanning Array I": "F-90 Compact Sensor Booster",
    "Supplemental Scanning CPU I": "F-90 Compact Sensor Booster",
    "'Gonzo' Damage Control I": "'Radical' Damage Control",
    "'Penumbra' White Noise ECM": "Umbra Scoped Radar ECM",
    "ECCM - Omni II": "Sensor Booster II",
    "ECCM - Gravimetric II": "Sensor Booster II",
    "ECCM - Ladar II": "Sensor Booster II",
    "ECCM - Magnetometric II": "Sensor Booster II",
    "ECCM - Radar II": "Sensor Booster II",
    "Scattering ECCM Projector I": "Linked Enduring Sensor Booster",
    "Gravimetric Backup Array I": "Signal Amplifier I",
    "Ladar Backup Array I": "Signal Amplifier I",
    "Magnetometric Backup Array I": "Signal Amplifier I",
    "Multi Sensor Backup Array I": "Signal Amplifier I",
    "RADAR Backup Array I": "Signal Amplifier I",
    "Large Ohm Capacitor Reserve I": "Large Compact Pb-Acid Cap Battery",
    "Large F-4a Ld-Sulfate Capacitor Charge Unit": "Large Compact Pb-Acid Cap Battery",
    "Large Peroxide Capacitor Power Cell": "Large Compact Pb-Acid Cap Battery",
    "ECCM Projector II": "Remote Sensor Booster II",
    "Cross-Lateral Gyrostabilizer I": "Counterbalanced Compact Gyrostabilizer",
    "F-M3 Munition Inertial Suspensor": "Counterbalanced Compact Gyrostabilizer",
    "Pneumatic Stabilization Actuator I": "Counterbalanced Compact Gyrostabilizer",
    "'Langour' Drive Disruptor I": "X5 Enduring Stasis Webifier",
    "Patterned Stasis Web I": "Fleeting Compact Stasis Webifier",
    "'Tycoon' Remote Tracking Computer": "'Enterprise' Remote Tracking Computer",
    "'Economist' Tracking Computer I": "'Marketeer' Tracking Computer",
    "Gravimetric Backup Array II": "Signal Amplifier II",
    "Ladar Backup Array II": "Signal Amplifier II",
    "Magnetometric Backup Array II": "Signal Amplifier II",
    "Multi Sensor Backup Array II": "Signal Amplifier II",
    "RADAR Backup Array II": "Signal Amplifier II",
    "Faint Phase Inversion ECM I": "Enfeebling Scoped Ladar ECM",
    "'Prayer' Remote Tracking Computer": "P-S Compact Remote Tracking Computer",
    "Partial Weapon Navigation": "Phased Scoped Target Painter",
    "Basic RADAR Backup Array": "'Basic' Signal Amplifier",
    "Basic Ladar Backup Array": "'Basic' Signal Amplifier",
    "Basic Gravimetric Backup Array": "'Basic' Signal Amplifier",
    "Basic Magnetometric Backup Array": "'Basic' Signal Amplifier",
    "Basic Multi Sensor Backup Array": "'Basic' Signal Amplifier",
    "Emergency Magnetometric Scanners": "'Basic' Signal Amplifier",
    "Emergency Multi-Frequency Scanners": "'Basic' Signal Amplifier",
    "Emergency RADAR Scanners": "'Basic' Signal Amplifier",
    "Emergency Ladar Scanners": "'Basic' Signal Amplifier",
    "Emergency Gravimetric Scanners": "'Basic' Signal Amplifier",
    "Sealed RADAR Backup Cluster": "'Basic' Signal Amplifier",
    "Sealed Magnetometric Backup Cluster": "'Basic' Signal Amplifier",
    "Sealed Multi-Frequency Backup Cluster": "'Basic' Signal Amplifier",
    "Sealed Ladar Backup Cluster": "'Basic' Signal Amplifier",
    "Sealed Gravimetric Backup Cluster": "'Basic' Signal Amplifier",
    "Surplus RADAR Reserve Array": "'Basic' Signal Amplifier",
    "F-42 Reiterative RADAR Backup Sensors": "'Basic' Signal Amplifier",
    "Surplus Magnetometric Reserve Array": "'Basic' Signal Amplifier",
    "F-42 Reiterative Magnetometric Backup Sensors": "'Basic' Signal Amplifier",
    "Surplus Multi-Frequency Reserve Array": "'Basic' Signal Amplifier",
    "F-42 Reiterative Multi-Frequency Backup Sensors": "'Basic' Signal Amplifier",
    "Surplus Ladar Reserve Array": "'Basic' Signal Amplifier",
    "F-42 Reiterative Ladar Backup Sensors": "'Basic' Signal Amplifier",
    "Surplus Gravimetric Reserve Array": "'Basic' Signal Amplifier",
    "F-42 Reiterative Gravimetric Backup Sensors": "'Basic' Signal Amplifier",
    "Amplitude Signal Enhancer": "'Basic' Signal Amplifier",
    "'Acolyth' Signal Booster": "'Basic' Signal Amplifier",
    "Type-E Discriminative Signal Augmentation": "'Basic' Signal Amplifier",
    "F-90 Positional Signal Amplifier": "'Basic' Signal Amplifier",
    "Gravimetric Firewall": "'Firewall' Signal Amplifier",
    "Ladar Firewall": "'Firewall' Signal Amplifier",
    "Magnetometric Firewall": "'Firewall' Signal Amplifier",
    "Multi Sensor Firewall": "'Firewall' Signal Amplifier",
    "RADAR Firewall": "'Firewall' Signal Amplifier",
    "'Pacifier' Large Remote Armor Repairer": "'Peace' Large Remote Armor Repairer",
    "Monopulse Tracking Mechanism I": "F-12 Enduring Tracking Computer",
    "Alumel Radar ECCM Sensor Array I": "Alumel-Wired Enduring Sensor Booster",
    "Alumel Ladar ECCM Sensor Array I": "Alumel-Wired Enduring Sensor Booster",
    "Alumel Gravimetric ECCM Sensor Array I": "Alumel-Wired Enduring Sensor Booster",
    "Alumel Omni ECCM Sensor Array I": "Alumel-Wired Enduring Sensor Booster",
    "Alumel Magnetometric ECCM Sensor Array I": "Alumel-Wired Enduring Sensor Booster",
    "Supplemental Ladar ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Supplemental Gravimetric ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Supplemental Omni ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Supplemental Radar ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Supplemental Magnetometric ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Incremental Radar ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Incremental Ladar ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Incremental Gravimetric ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Incremental Magnetometric ECCM Scanning Array I": "Alumel-Wired Enduring Sensor Booster",
    "Prototype ECCM Radar Sensor Cluster": "Alumel-Wired Enduring Sensor Booster",
    "Prototype ECCM Ladar Sensor Cluster": "Alumel-Wired Enduring Sensor Booster",
    "Prototype ECCM Gravimetric Sensor Cluster": "Alumel-Wired Enduring Sensor Booster",
    "Prototype ECCM Omni Sensor Cluster": "Alumel-Wired Enduring Sensor Booster",
    "Prototype ECCM Magnetometric Sensor Cluster": "Alumel-Wired Enduring Sensor Booster",
    "Prototype Sensor Booster": "Alumel-Wired Enduring Sensor Booster",
    "Thermal Exhaust System I": "Extruded Compact Heat Sink",
    "C4S Coiled Circuit Thermal Radiator": "Extruded Compact Heat Sink",
    "'Skadi' Coolant System I": "Extruded Compact Heat Sink",
    "'Forger' ECCM - Magnetometric I": "'Shady' Sensor Booster",
    "Insulated Stabilizer Array I": "Vortex Compact Magnetic Field Stabilizer",
    "Linear Flux Stabilizer I": "Vortex Compact Magnetic Field Stabilizer",
    "Gauss Field Balancer I": "Vortex Compact Magnetic Field Stabilizer",
    "'Broker' Remote Sensor Dampener I": "'Executive' Remote Sensor Dampener",
    "'Orion' Tracking CPU I": "Optical Compact Tracking Computer",
    "Spot Pulsing ECCM I": "F-23 Compact Remote Sensor Booster",
    "Phased Muon ECCM Caster I": "F-23 Compact Remote Sensor Booster",
    "Connected Remote Sensor Booster": "F-23 Compact Remote Sensor Booster",
    "Small Ohm Capacitor Reserve I": "Small Compact Pb-Acid Cap Battery",
    "Small F-4a Ld-Sulfate Capacitor Charge Unit": "Small Compact Pb-Acid Cap Battery",
    "Small Peroxide Capacitor Power Cell": "Small Compact Pb-Acid Cap Battery",
    "FZ-3 Subversive Spatial Destabilizer ECM": "BZ-5 Scoped Gravimetric ECM",
    "Medium Ohm Capacitor Reserve I": "Medium Compact Pb-Acid Cap Battery",
    "Medium F-4a Ld-Sulfate Capacitor Charge Unit": "Medium Compact Pb-Acid Cap Battery",
    "Medium Peroxide Capacitor Power Cell": "Medium Compact Pb-Acid Cap Battery",
    "Ballistic 'Purge' Targeting System I": "'Full Duplex' Ballistic Control System",
    "Protected Gravimetric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Protected Ladar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Protected Magnetometric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Protected Multi-Frequency Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Protected RADAR Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Reserve Gravimetric Scanners": "F-89 Compact Signal Amplifier",
    "Reserve Ladar Scanners": "F-89 Compact Signal Amplifier",
    "Reserve Magnetometric Scanners": "F-89 Compact Signal Amplifier",
    "Reserve Multi-Frequency Scanners": "F-89 Compact Signal Amplifier",
    "Reserve RADAR Scanners": "F-89 Compact Signal Amplifier",
    "Secure Gravimetric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Secure Ladar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Secure Magnetometric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Secure Radar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "F-43 Repetitive Gravimetric Backup Sensors": "F-89 Compact Signal Amplifier",
    "F-43 Repetitive Ladar Backup Sensors": "F-89 Compact Signal Amplifier",
    "F-43 Repetitive Magnetometric Backup Sensors": "F-89 Compact Signal Amplifier",
    "F-43 Repetitive Multi-Frequency Backup Sensors": "F-89 Compact Signal Amplifier",
    "F-43 Repetitive RADAR Backup Sensors": "F-89 Compact Signal Amplifier",
    "Shielded Gravimetric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Shielded Ladar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Shielded Magnetometric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Shielded Radar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Surrogate Gravimetric Reserve Array I": "F-89 Compact Signal Amplifier",
    "Surrogate Ladar Reserve Array I": "F-89 Compact Signal Amplifier",
    "Surrogate Magnetometric Reserve Array I": "F-89 Compact Signal Amplifier",
    "Surrogate Multi-Frequency Reserve Array I": "F-89 Compact Signal Amplifier",
    "Surrogate RADAR Reserve Array I": "F-89 Compact Signal Amplifier",
    "Warded Gravimetric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Warded Ladar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Warded Magnetometric Backup Cluster I": "F-89 Compact Signal Amplifier",
    "Warded Radar Backup Cluster I": "F-89 Compact Signal Amplifier",
    "'Mendicant' Signal Booster I": "F-89 Compact Signal Amplifier",
    "Wavelength Signal Enhancer I": "F-89 Compact Signal Amplifier",
    "Type-D Attenuation Signal Augmentation": "F-89 Compact Signal Amplifier",
    "Indirect Scanning Dampening Unit I": "Phased Muon Scoped Sensor Dampener",
}