"""
Conversion pack for skinned ships to their base hull. Unlike other conversion
packs, the name of this file is important as it is used in service.market to
flag as unpublished

See GH issue #67 on why this is needed
"""

CONVERSIONS = {
    "Abaddon Kador Edition": "Abaddon",
    "Abaddon Tash-Murkon Edition": "Abaddon",
    "Aliastra Catalyst": "Catalyst",
    "Bestower Tash-Murkon Edition": "Bestower",
    "Brutix Serpentis Edition": "Brutix",
    "Caracal Nugoeihuvi Edition": "Caracal",
    "Caracal Wiyrkomi Edition": "Caracal",
    "Catalyst Serpentis Edition": "Catalyst",
    "Coercer Blood Raiders Edition": "Coercer",
    "Cormorant Guristas Edition": "Cormorant",
    "Cyclone Thukker Tribe Edition": "Cyclone",
    "Ferox Guristas Edition": "Ferox",
    "Hyperion Aliastra Edition": "Hyperion",
    "Hyperion Innerzone Shipping Edition": "Hyperion",
    "Incursus Aliastra Edition": "Incursus",
    "Incursus Innerzone Shipping Edition": "Incursus",
    "Inner Zone Shipping Catalyst": "Catalyst",
    "Inner Zone Shipping Imicus": "Imicus",
    "Intaki Syndicate Catalyst": "Catalyst",
    "InterBus Catalyst": "Catalyst",
    "Iteron Inner Zone Shipping Edition": "Iteron Mark V",
    "Mackinaw ORE Development Edition": "Mackinaw",
    "Maelstrom Krusual Edition": "Maelstrom",
    "Maelstrom Nefantar Edition": "Maelstrom",
    "Mammoth Nefantar Edition": "Mammoth",
    "Merlin Nugoeihuvi Edition": "Merlin",
    "Merlin Wiyrkomi Edition": "Merlin",
    "Miasmos Amastris Edition": "Miasmos Quafe Ultra Edition",
    "Miasmos Quafe Ultramarine Edition": "Miasmos Quafe Ultra Edition",
    "Nefantar Thrasher": "Thrasher",
    "Omen Kador Edition": "Omen",
    "Omen Tash-Murkon Edition": "Omen",
    "Orca ORE Development Edition": "Orca",
    "Police Pursuit Comet": "Federation Navy Comet",
    "Prophecy Blood Raiders Edition": "Prophecy",
    "Punisher Kador Edition": "Punisher",
    "Punisher Tash-Murkon Edition": "Punisher",
    "Quafe Catalyst": "Catalyst",
    "Rifter Krusual Edition": "Rifter",
    "Rifter Nefantar Edition": "Rifter",
    "Rokh Nugoeihuvi Edition": "Rokh",
    "Rokh Wiyrkomi Edition": "Rokh",
    "Rorqual ORE Development Edition": "Rorqual",
    "Stabber Krusual Edition": "Stabber",
    "Stabber Nefantar Edition": "Stabber",
    "Sarum Magnate": "Magnate",
    "Sukuuvestaa Heron": "Heron",
    "Tash-Murkon Magnate": "Magnate",
    "Tayra Wiyrkomi Edition": "Tayra",
    "Thorax Aliastra Edition": "Thorax",
    "Thorax Innerzone Shipping Edition": "Thorax",
    "Thrasher Thukker Tribe Edition": "Thrasher",
    "Vherokior Probe": "Probe"
}
